### ISSUE TITLE
Scrobbling fails for multi-episode files

### ISSUE THREAD

**Issue by stefantalen** [trakt/Plex-Trakt-Scrobbler#145]
Yesterday I was watching The Office S03E12 and E13, this was a single file named "The Office S03E12-E13.mkv"

When I checked trakt today I noticed only E13 was scrobbled, I think the scrobbler failed scrobbling E12 because it didn't hit the 80% watched mark.

My theory is that the scrobbler updated my watching status when I was below 80% of the episode, but when it checked the watch status again Plex had already started episode 13 so it updated my watch status to watching that episode.

I'll try to find some logging for you tomorrow.

**Comment by fuzeman** [comment]
Multi-part episode scrobbling is back in [v1.1.0.6](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.1.0.6).
