### ISSUE TITLE
Sync watched from trakt.tv doesn't work properly for multi-episode files

### ISSUE THREAD

**Issue by daften** [trakt/Plex-Trakt-Scrobbler#148]
For my shows at first I like to sync the watched status from trakt to plex. It does this pretty good, but one hiccup I've clearly identified is that for 2 episodes with one file (So S01E16E17 e.g.), only the second episode is marked as watched.

**Comment by szafran81** [comment]
Same here. Only 2nd episode of each double episode file is marked as watched.

**Comment by AndreasWurm** [comment]
can confirm

**Comment by fuzeman** [comment]
This should be fixed in the develop branch.
