### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by jimeh** [trakt/Plex-Trakt-Scrobbler#152]
After running Plex with this plugin for about 2 weeks, the plugin process was using 2GB of physical memory (24% of 8GB). After restarting Plex it's only using 0.6%.

Sorry I don't have any more details for now, but I'll be keeping an eye on how it behaves over the coming days/weeks.

**Comment by fuzeman** [comment]
Have some time to look at the memory issues now, more details will be in https://github.com/trakt/Plex-Trakt-Scrobbler/issues/178

**Comment by jimeh** [comment]
Cool. I haven't noticed it using massive amounts of memory for some time, but it could be cause I've been updating the plugin more aggressively, so it hasn't really been left alone for +2 weeks like before. Currently the last PMS restart was 61 hours ago, and the Trakt plugin is using around 360MB (4.4% of 8GB).

I'll keep and eye on #178 and contribute with anything useful if I can :)
