### ISSUE TITLE
Unable to login from plex with google account

### ISSUE THREAD

**Issue by L0bit0** [trakt/Plex-Trakt-Scrobbler#154]
I just have created an account on trakt with my google account. I can access on the web, but I was not able to do on plex. I have tried with user and email.

I created a new account (regular account directly on trakt) and I can login on plex with it.

There is any specific way to use google accounts from plex?

thanks

**Comment by L0bit0** [comment]
I do not understand, i can not reset my password on trakt since i am using google account, i do not see this option on trakt profile settings. Can you give me detailed steps?

Thanks for your help.

**Comment by rectifyer** [comment]
For now, try logging out then on the sign in form, click the "forgot" link to. Type in your email there.

**Comment by L0bit0** [comment]
Thanks, it worked.

Now I have an eror on sync, but i will create a new post for this.

thanks
