### ISSUE TITLE
plex: error: authentication failed

### ISSUE THREAD

**Issue by pieter-jangoeman** [trakt/Plex-Trakt-Scrobbler#159]
when I try to connect trakt with my plex in the home theater, I always get the error: authentication failed above sync, about en preferences.
also, it looks  like the preferences don't remember my username and password.
tried to install again, didn't work.
anyone who can help me?

**Comment by scottrobertson** [comment]
Please look at the latest issues before submitting a new one: https://github.com/trakt/Plex-Trakt-Scrobbler/issues/157

**Comment by pieter-jangoeman** [comment]
thanks man, didn't see that one there!

**Comment by fuzeman** [comment]
Are you trying to setup the plugin via Plex Home Theater? there has been an issue with plugin configuration in PHT for a long time (#71), so you can try configure from http://plex.tv/web instead.
