### ISSUE TITLE
Plex Home seen data not synched

### ISSUE THREAD

**Issue by kuarthepirat** [trakt/Plex-Trakt-Scrobbler#162]
I'm using Plex Home with one PlexPass user and 3 internal Plex Home users without a myPlex Account. We mostly watch on one of these internal user accounts and the seen stats from this account are not synched to trakt at all.

**Comment by fuzeman** [comment]
I'll need to try reproduce this to figure out what's happening, will let you know when I have more details.

**Comment by fuzeman** [comment]
You should be able to enter the names of your additional users under "Filter - myPlex users" and they will be scrobbled as well.

Please note, trakt.tv has been having server issues and trying to scrobble with multiple active watch sessions might lead to some strange results.

**Comment by kuarthepirat** [comment]
I have * as "Filter - myPlex users". And scrobbling is working fine. What is not working is the data for already watched movies and ratings from the time trakt.tv and the plugin was not working. 

To me it seems, the Filter is only working for myPlex users on the server. The Plex Home users don't even have a user name in the Plex DB.

**Comment by fuzeman** [comment]
Filters are only used for scrobbling, syncing just doesn't have the ability to to push watched data from multiple plex users to trakt.

This will likely be supported in the future with a planned multi-user scrobbling/syncing feature..
