### ISSUE TITLE
v0.9.1.7 Beta Release bugs

### ISSUE THREAD

**Issue by blackley** [trakt/Plex-Trakt-Scrobbler#163]
Hi fuzeman,

As mentioned on the Plex forum, i am getting duplicates and new library additions showing up as watched when they are sent to trakt - it may be a trakt site bug, however i am not sure.  Logs attached from 2 different servers.  Also when i just finished building my new server and did a pull from trakt - very little of the media titles that i know have changed was updated in my Plex library's.  See server one logs for these details.

https://www.dropbox.com/s/oys8eqptljsq9nv/simplify-plex-trakt-logs-server1.zip?dl=0 - server 1
https://www.dropbox.com/s/oys8eqptljsq9nv/simplify-plex-trakt-logs-server1.zip?dl=0 - server 2

Cheers,
Darren (A.K.A. Simplify)

**Comment by fuzeman** [comment]
Looking at the log from "server 1", there is definitely some interesting errors coming up. The link for "server 2" doesn't appear to be correct though? (it's the same as "server 1")

I've got a few ideas of what is causing this, so might have a fix ready to test sometime (late) tomorrow.

------------------------

To provide a lot more detail on the issue, could you adjust these logging options to the following values (then retry the sync and upload the logs):

![](http://i.imgur.com/2BQalol.png)

**Comment by blackley** [comment]
G’day Dean,

Server 2 is my old server that i am about to decommission.  I will turn on the logging now and let it run overnight.  I can report that this afternoon (Western Australian time) that scrobble worked correctly - single entry added to trakt.  I will be doing some more testing this evening my time and will report back tomorrow.

Thanks for all your hard work and time on this plugin - the whole community appreciates it!  Also i have 2 servers running all the time here a windows and linux server so i am happy to be your test environment when you want to test new updates or additions :-)
-- 
Cheers,
 
Darren Blackley
ICT Consultant

I have never let my schooling interfere with my Education - Mark Twain.

**Comment by fuzeman** [comment]
Could you test out this release: https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/issue/163.zip, it includes a possible fix for the error displayed in your log files.

I'm not exactly sure how to reproduce this issue, so there might still be some other bugs that need fixing still.

**Comment by blackley** [comment]
Hi Dean,

I have installed the update and run a sync everything appears to be working correctly and as expected.  I have included a copy of the current log for your review so you can see if there is anything else that pops out in the log that may need attention.

Thanks again for your speedy fix :-)

-- 
Cheers,
 
Darren Blackley
ICT Consultant

I have never let my schooling interfere with my Education - Mark Twain.

**Comment by fuzeman** [comment]
That's good to hear, will have this fix included in the next beta release.

Hopefully will have v0.9 released onto stable this week as well (just fixing any final bugs that come up).

**Comment by blackley** [comment]
Dean i got some more duplicate entries last night - log attached.


-- 
Cheers,
 
Darren Blackley
ICT Consultant

I have never let my schooling interfere with my Education - Mark Twain.

**Comment by fuzeman** [comment]
Can't see the attachment, you might need to upload the log file to Dropbox or email it to me directly (me@dgardiner.net).

**Comment by blackley** [comment]
here you go https://www.dropbox.com/s/uetetix5fa1o62a/Trakt.logs.zip?dl=0
-- 
Cheers,
 
Darren Blackley
ICT Consultant

I have never let my schooling interfere with my Education - Mark Twain.

**Comment by fuzeman** [comment]
It appears your router is possibly blocking a lot of requests?

request to trakt.tv failed:

    Unable to send action - HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /sync/history (Caused by <class 'socket.error'>: [Errno 111] Connection refused)

and the update checker requests keep failing:

    Starting new HTTP connection (1): pts.skipthe.net
    "POST /api/ping HTTP/1.1" 302 175
    Starting new HTTP connection (1): fritz.box
    "GET /blocked HTTP/1.1" 404 2953
    Next update check scheduled to happen in 30 seconds

**Comment by blackley** [comment]
thats very strange - i have had no changes to the configuration on my router and it was working previously as far as i know.  I will investigate now.
-- 
Cheers,
 
Darren Blackley
ICT Consultant

I have never let my schooling interfere with my Education - Mark Twain.

**Comment by blackley** [comment]
here is the latest logs - i have resolved the router issue, and I am still seeing duplicates.  Also including screenshot

https://www.dropbox.com/s/js0x6mbgwy8qux7/PMS%20Plugin%20Logs.zip?dl=0 <https://www.dropbox.com/s/js0x6mbgwy8qux7/PMS%20Plugin%20Logs.zip?dl=0> - logs
https://www.dropbox.com/s/bshciabwncd2sxk/Screen%20Shot%202015-01-14%20at%203.44.48%20pm.png?dl=0 <https://www.dropbox.com/s/bshciabwncd2sxk/Screen%20Shot%202015-01-14%20at%203.44.48%20pm.png?dl=0> - screenshot

-- 
Cheers,
 
Darren Blackley
ICT Consultant

I have never let my schooling interfere with my Education - Mark Twain.

**Comment by fuzeman** [comment]
I'm guessing you have some shows/movies duplicated (in multiple libraries)?

I've found an issue with syncing that means duplicated movies/shows will cause multiple scrobbles. I should have a fix ready tomorrow.

**Comment by blackley** [comment]
Hi Dean,

yes i have been looking into that from this end - I had some anime libraries available to the kids as well as everyone else - so available from 2 locations.  I have corrected that now.
-- 
Cheers,
 
Darren Blackley
ICT Consultant

I have never let my schooling interfere with my Education - Mark Twain.

**Comment by fuzeman** [comment]
fixes included in **0.9.1.8-beta**: https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-30#entry825185
