### ISSUE TITLE
Tracktv plug-in not appearing in 0.9.11.7?

### ISSUE THREAD

**Issue by garlandkr** [trakt/Plex-Trakt-Scrobbler#165]
I'm running PLEX server 0.9.11.7 on Linux, I grabbed the develop.zip and unzipped to my plug-ins folder. Restarted PLEX to be on the safe-side and it's not appearing anywhere in the channels.

**Comment by blackley** [comment]
Do you have the folder naming correct?  should be as follows; 

$HOME/Library/Application Support/Plex Media Server/Plug-ins/trakttv.bundle

then in that folder should be a folder called Contents and a text file - readme.md

**Comment by ret50** [comment]
Hello, I had a bug just like you and fuzeman just corrected the bug tonight. Could you just retry with the last developper version ?

**Comment by garlandkr** [comment]
Yes, I have also put a check in the disable compatibility for plug-ins in the advanced settings located here - http://localhost:32400/web/index.html#!/settings/server

I am trying to locate the bundle on this page - http://localhost:32400/web/index.html#!/server/<some_hash>/directory

Is that the right location? I have gone into a few different locations but it is not appearing. I have also restarted the server.

**Comment by fuzeman** [comment]
Once the plugin installed it should be visible under:

    http://localhost:32400/web/index.html#!/server/<server_id>/channels

Send me your log files if you can't find the plugin there, they are located here on my ubuntu server:

    /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.plugins.trakttv.log

**Note:** if you can't find the "trakttv" log file under "PMS Plugin Logs", the plugin probably isn't installed correctly.

**Comment by Boren** [comment]
Make sure you haven't changed the default application data in plex settings.
![2015-01-15 08_08_46-plex](https://cloud.githubusercontent.com/assets/1568580/5753723/c8137efe-9c8d-11e4-9613-a1f10522c63b.png)

**Comment by garlandkr** [comment]
Thanks @Boren - I just blindly followed the install docs, but actually my plex application was in /plex/ not /var/lib/plexmediaserver

Now it is working.
