### ISSUE TITLE
Sync failed: IndexError('list index out of range',)]

### ISSUE THREAD

**Issue by hgelpke** [trakt/Plex-Trakt-Scrobbler#169]
I've been trying to get sync to work since Trakt moved to 2.0 with no luck. With beta 8 when sync fails I get an error stating "list index out of range". Not sure what the issue is.

**Comment by fuzeman** [comment]
Could you send me the plugin log files, see https://github.com/fuzeman/Plex-Trakt-Scrobbler/wiki/Support#log-files for the location of them.

**Comment by hgelpke** [comment]
Gladly. Which ones do you need "info" and which ones do you need "debug"

**Comment by fuzeman** [comment]
Setup the plugin "Logging" options like this:
![](http://i.imgur.com/l1rVtMP.png)

Run another sync (to reproduce the problem) and then upload the "com.plexapp.plugins.trakttv.log" file somewhere or send it to me@dgardiner.net

**Comment by hgelpke** [comment]
https://drive.google.com/file/d/0B37roVu9zhf4V3VjRXRyb1FheXc/view?usp=sharing

**Comment by fuzeman** [comment]
Should be fixed in **v0.9.1.10**: https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-32#entry831576

**Comment by hgelpke** [comment]
That seems to have done the trick. Thank you for all your hard work.
