### ISSUE TITLE
Must Use Plex On Port 32400?

### ISSUE THREAD

**Issue by dustinhansen** [trakt/Plex-Trakt-Scrobbler#170]
It seems like the Trakt scrobbler is hard-coded to use port 32400 but we run our Plex server on a different port. Is there any way to address this?

**Comment by fuzeman** [comment]
Support can be added for this, wasn't aware you could change the port PMS binds to though?

**Comment by Benni-chan** [comment]
afaik plex always uses 32400. you can only configure the port for external connection (if you want to set another port for portforwarding in your router). but in the local network (and internally) plex always uses 32400. otherwise no app would know, how to connect to pms.

**Comment by fuzeman** [comment]
Would like to know if this option is *actually* required before progressing, will be happy to re-open this when more details are provided.
