### ISSUE TITLE
Sync failed: XMLSyntaxError: invalid character in attribute value

### ISSUE THREAD

**Issue by chrisrico** [trakt/Plex-Trakt-Scrobbler#171]
Here's the relevant portion from my log: http://pastie.org/private/miengokl7vcyujinojog1g

I have PlexPass and I'm running on Ubuntu. This occurs only while syncing movies, shows work fine.

Let me know if there's any additional information you need.

**Comment by fuzeman** [comment]
Possibly fixed in **v0.9.1.10**: https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-32#entry831576

Unsure on the exact cause, so let me know if this hasn't been fixed yet.
