### ISSUE TITLE
Syncing is broken as fuck?

### ISSUE THREAD

**Issue by AndreasWurm** [trakt/Plex-Trakt-Scrobbler#172]
this is my first usage of this plugin. i used trakt + xbmc + xbmc plugin earlier. migrated to plex last month.

Well I installed the latest Beta today and wanted to synchronize.. first of it didnt work getting all kind of code 500 errors. When it worked it started to update the watched info from trakt (pull).
So far so good. Now its still in the process of pushing. and it is actually pushing everything that was marked as watched in trakt before again as watched today.. FFS

Also all Movies are now listed as Recently Viewed.. but not send to plex as watched today.. maybe that will happen after its done with the tv shows.

where does plex store the watched info? cant find a way to actually see how often and when it was watched?
would really help to figure out whats going on.

To me it feels like the Plugin is storing not the watched date it receives from trakt and just saves as watched now, and then it sees "oh shit this was watched now, trakt has only stored it was watched 2 month ago, better send it was watched today"

**Comment by fuzeman** [comment]
The plugin compares your watched media in plex against trakt to determine if there are any changes that need to be sent to trakt *(the watched timestamp doesn't come into this)*.

It's hard to really determine what happened without your log files yet, but this issue could likely come down to:
 - Running a version of the plugin earlier than v0.9.1.6 with the "Personal Media" metadata agent (or an unsupported agent)
 - Your trakt.tv watched collection wasn't built correctly (due to a trakt.tv API error, or parsing issue)

---------------

Could you upload the plugin log files (to dropbox, etc..), see this page for the location of them: https://github.com/fuzeman/Plex-Trakt-Scrobbler/wiki/Support#log-files. You might need to include some of the numbered log files (e.g. ```com.plexapp.plugins.trakttv.log.1```) as well.

**Comment by AndreasWurm** [comment]
im currently cleaning up my trakt history with a ruby script. after that ill try to recreate the issue and report back.
just to get some clarification, plex doesnt know when something was watched, only if it was watched or not?
If the later is the case, what is supposed to happen if i watch a movie i already watched some time ago?
Also does that mean the timestamp for watched in trakt is always the time the sync happend?

**Comment by fuzeman** [comment]
There is a ```lastViewedAt``` timestamp in plex. this is sent to trakt when marking items as watched.

--------------------

I previously mentioned the watched timestamp in response to this:

> To me it feels like the Plugin is storing not the watched date it receives from trakt and just saves as watched now, and then it sees "oh shit this was watched now, trakt has only stored it was watched 2 month ago, better send it was watched today"

The watched timestamp in plex isn't used to determine which items need to be sent to trakt, so something else must be causing this issue..

**Comment by marjorg** [comment]
Hey! I'm having some sync issues too, my log is attached! I'm not 100% sure, but I think it started when trakt.tv published their new site.

Log: https://www.dropbox.com/s/exza9rg2hhywa6k/trakttv.txt?dl=0

**Comment by AndreasWurm** [comment]
this time i can provide you with logs.

I Added the movies "Se7en" and "Crank High Voltage" to my movie folder.
This resulted in them now beeing marked as collected in Trakt as expected.
But besides that they got also listed in my recently watched section in Trakt, which is clearly wrong.
Both movies were already marked as watched in Trakt (May 2014).

From the Trakt History:
Crank: High Voltage Jan 28, 2015 6:55 PM
Se7en Jan 28, 2015 5:38 PM


Logs: https://gist.github.com/AndreasWurm/9aa309b0363b5043d71c

**Comment by fuzeman** [comment]
Thanks for the logs, I can see what's causing this issue now..

Should have a fix for this bug released later today.

**Comment by fuzeman** [comment]
This bug should be fixed in this development version: https://github.com/trakt/Plex-Trakt-Scrobbler/archive/f7e61c11f68eec29ef89b95b342012652c9d6d7a.zip

Will have a proper beta release later today after some more testing.

**Comment by fuzeman** [comment]
Released in **v0.9.1.12-beta**: https://forums.plex.tv/index.php/topic/102818-rel-trakt/page-34#entry837859

Will assume this is fixed for now, let me know if you are still seeing this bug in the latest beta.
