### ISSUE TITLE
Problem and help

### ISSUE THREAD

**Issue by elmamado** [trakt/Plex-Trakt-Scrobbler#174]
Hello

I have the  2.3.15 version and  0.9.11.7 version still i can't use the last master version. Anyone with the same problem?

**Comment by fuzeman** [comment]
Could you upload the plugin log file?

See https://github.com/fuzeman/Plex-Trakt-Scrobbler/wiki/Support#log-files for the location of the log files.

**Comment by elmamado** [comment]
hello
thanks for answer my call.
i send the fill attached.
Regards

Date: Mon, 16 Feb 2015 16:09:13 -0800

**Comment by fuzeman** [comment]
Have you updated to v0.9.1.18 (https://forums.plex.tv/index.php/topic/102818-rel-trakt/?p=854325)?

This bug should of been fixed in v0.9.1.18.

**Comment by elmamado** [comment]
Hello again

With the new update everything is working again thanks

Em 17/02/2015 01:41, Dean Gardiner <notifications@github.com> escreveu:
Have you updated to v0.9.1.18 (https://forums.plex.tv/index.php/topic/102818-rel-trakt/?p=854325)?

This bug should of been fixed in v0.9.1.18.

---
