### ISSUE TITLE
Trakt on Linux 64bit, Plex Version 0.9.11.7 

### ISSUE THREAD

**Issue by ucristian** [trakt/Plex-Trakt-Scrobbler#176]
After install, it doesn't appear in the channel section.

**Comment by fuzeman** [comment]
Could you upload the plugin log file?

See https://github.com/fuzeman/Plex-Trakt-Scrobbler/wiki/Support#log-files for the location of the log files.

**Comment by ucristian** [comment]
There isn't a log file created.

I've Trakt on linux 32 bits running perfectly but I don't know what happen on 64 bits

**Comment by fuzeman** [comment]
Could you check the directory structure of the plugin first, it should be installed as:
```
Plug-ins\trakttv.bundle\Contents
```

If the directory structure is correct for the plugin, restart plex media server (wait a minute for it to startup) then upload the latest ```Logs\Plex Media Server.log``` file.

**Comment by fuzeman** [comment]
This appears to be the problem:
```
Feb 17, 2015 11:09:29 [0x7fef8affd700] DEBUG - Starting plug-in /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle.
Feb 17, 2015 11:09:29 [0x7fef8affd700] ERROR - Caught exception starting plugin /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle (Empty or non-existant file.)
```
This error likely means the plugin has incorrect permissions.

Not sure how your system is setup, but the owner + group needs to be set to "plex" on my system (```chown -R plex:plex Trakttv.bundle```)

**Comment by ucristian** [comment]
Thanks a lot.
