### ISSUE TITLE
Multi-user scrobbling

### ISSUE THREAD

**Issue by fuzeman** [trakt/Plex-Trakt-Scrobbler#177]
Implement the ability to link individual plex users/clients to trakt.tv accounts and scrobble multiple sessions simultaneously.

---------------------------

**13/02/2015** - Development has started (in [feature/scrobbler-redesign](https://github.com/fuzeman/Plex-Trakt-Scrobbler/tree/feature/scrobbler-redesign)). There will be a beta version released when this feature is in a workable state.

**7/05/2015** - Multi-user scrobbling is working in the plugin, configuring multiple accounts will be difficult until the new configuration interface has been completed.

**Comment by fuzeman** [comment]
Multi-user scrobbling has been implemented in the [feature/scrobbler-redesign](https://github.com/fuzeman/Plex-Trakt-Scrobbler/tree/feature/scrobbler-redesign) branch.

----------------------------------------------------

**Note**
 - The new configuration interface is still in development, currently the only way to add more accounts is by editing the SQLite database directly
 - Still early in development, wouldn't recommend testing this branch yet.

Will update the issue when this feature is in a more finished state.

**Comment by JossiEnd** [comment]
I'm trying to get this to work but it doesn't. I share my Plex Server with two friends. I'm the only one using Trakt. But whenever they watch something it's being added to my trakt histery. How should i setup the filter? Fill in my username, or fill in the other users name? Is the "Clients" filter also part of the multi user experience?

**Comment by fuzeman** [comment]
@JossiEnd With all the filters, you enter the users/clients you would like to scrobble from *(your username or clients)*.

----------------------------------------------

**Note:** filters aren't related to this issue (they have been available on the master branch for a long time), this issue is to allow users sharing your server the ability to scrobble/sync to their own trakt.tv accounts.

**Comment by JossiEnd** [comment]
Thanks! It look like i got it working now!

**Comment by damiantje99** [comment]
Hi,

Any idea when the multi-user scrobbling option will be done? And can you explain how I use multi-scrobbling from the SQLite database?

Kind Regards

**Comment by fuzeman** [comment]
Will be released in the coming **v0.9.9** beta ([discussion](https://github.com/trakt/Plex-Trakt-Scrobbler/issues/194), [updates](https://github.com/trakt/Plex-Trakt-Scrobbler/issues/193))
