### ISSUE TITLE
Synchronize, failed (MemoryError: "")

### ISSUE THREAD

**Issue by RampantRedsFan** [trakt/Plex-Trakt-Scrobbler#178]
I am running the most recent stable release that is in the unauthorized app store (0.9.1.20-master) and I am receiving the following error when trying to Syncronize "failed (MemoryError: "")"

I have a fairly large library that includes local programs that are not on Trakt... Other than that I am just a normal Plex user.

Below is my log. I increased logging for the most recent Sync attempt.

Please let me know if you have any questions or I can provide any more info.

----------------------------------------------------------------------------------------------------

```
2015-02-24 20:55:38,747 (28b8) :  ERROR (logkit:22) - [plugin.core.task] Exception raised in triggered function 'sync.pull.show': 
Traceback (most recent call last):
  File "c:\Users\Matt\AppData\Local\Plex Media Server\Plug-ins\trakttv.bundle\Contents\Code\core\task.py", line 65, in run
    self.result = self.target(*self.args, **self.kwargs)
  File "c:\Users\Matt\AppData\Local\Plex Media Server\Plug-ins\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\code\sandbox.py", line 19, in _apply
    return apply(f, args, kwargs)
  File "c:\Users\Matt\AppData\Local\Plex Media Server\Plug-ins\trakttv.bundle\Contents\Code\sync\pull.py", line 191, in run
    p_seasons=Library.episodes(p_show.rating_key, p_show, flat=False),
  File "c:\Users\Matt\AppData\Local\Plex Media Server\Plug-ins\trakttv.bundle\Contents\Libraries\Shared\plex_metadata\library.py", line 73, in episodes
    result[season][episode] = item
MemoryError
```

**EDIT:** trimmed log file for readability

**Comment by fuzeman** [comment]
Roughly how large is your collection? the details under ```trakt -> About -> Cache Statistics``` would give me a good idea.

How much physical and virtual memory do you have?

---------------
Current virtual memory size can be found under: ```Control Panel -> System -> Advanced system settings -> Advanced -> Performance Settings -> Advanced -> "Total paging file size for all drives"```

**Comment by RampantRedsFan** [comment]
Thanks for responding...

There are two numbers on here... [matcher] Store Size: 1160 - [metadata] Store Size: 279

My Virtual memory is 8078 MB.

I am going to up the virtual memory and report back.

**Comment by dannymichel** [comment]
Where is the log located?

**Comment by RampantRedsFan** [comment]
The log is located on a 500 GB SSD with OS Drive with 150 GB of free space.

**Comment by fuzeman** [comment]
On windows, 32-bit python (used in PMS) can only use up to 2GB of memory, hitting this limit is likely triggering the ```MemoryError```.

I've started looking into what is causing these big memory allocations, will try keep this issue updated on the progress of a fix.

--------------------------------------

Memory usage on my server sits at around 1.50GB on startup and hits 1.76GB after a sync :confused:

**Comment by fuzeman** [comment]
The large memory usage reported was as a result of a tool for debugging memory usage displaying ```VmSize``` (includes: shared memory, unmapped pages, file caches, etc..) instead of ```VmRSS``` (memory currently used).

Actual memory usage sits around 180MB, which isn't too bad.. (probably could be reduced a bit :smiley: ).

---------------------------------

This doesn't really provide an answer for the ```MemoryError``` though, it appears to be windows-specific though.

Still have some more debugging + testing to do :smile:

**Comment by fuzeman** [comment]
@RampantRedsFan could you test this version: https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/issue/178.zip (upload a log if syncing still fails).

------------------------------

I've optimized some components which used a lot of memory and adjusted the caching to avoid objects being left in memory for a long time.

I haven't been able to reproduce this issue myself, so there might be something else still causing this issue.

**Comment by neogeek87** [comment]
@fuzeman, I am having the same problems. and tried it with the same 178.zip

    [matcher] Cache Size: 0, Store Size: 438
    [metadata] Cache Size: 0, Store Size: 50

Virtual Memory is 10,762MB

Not sure where the log is, but i can provide it if you give me a path

**Comment by RampantRedsFan** [comment]
@fuzeman Thanks so much for looking into this, and sorry for my delay in getting back to you.

Unfortunately this release did not fix the MemoryError issue. I have attached my logs turned on the highest logging level. I attempted the sync around 11:45 on 3/16.

https://drive.google.com/file/d/0BwuY0n1LdozRNjZQTXdwY2Zzbnc/view?usp=sharing

**Comment by fuzeman** [comment]
@RampantRedsFan could you update the plugin from https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/issue/178.zip again, set the "Matcher" option to "Plex" (in the plugin settings) and run another sync (upload another log if it still fails).

I'm currently seeing some trakt.tv API issues (overloaded?) which is causing sync to fail (the status will display "trakt.tv - 520", or something similar), so you might need to try syncing a number of times before it will work.

**Comment by RampantRedsFan** [comment]
Looks like this worked! I am still getting an error (having to do with connection), but it is no longer the memory error... I'm going to play around with the sync (maybe sync on a directory-by-directory basis) to see if this helps.

Thanks for your help!
