### ISSUE TITLE
Trakt Logo needs to be updated

### ISSUE THREAD

**Issue by sguergachi** [trakt/Plex-Trakt-Scrobbler#179]
Currently see the old Trakt.tv logo used throughout the app.

![image](https://cloud.githubusercontent.com/assets/615386/6548518/3eea6e26-c5d2-11e4-85f7-c38e3bdade4a.png)
![image](https://cloud.githubusercontent.com/assets/615386/6548521/4d0928e4-c5d2-11e4-9303-da94d4ba159f.png)

**Comment by rectifyer** [comment]
Let me know if you need any other images.

![trakt-1024](https://cloud.githubusercontent.com/assets/71046/7667255/7205e974-fbb6-11e4-8ca4-735d095646e9.png)

![trakt-b wfordarkbgs](https://cloud.githubusercontent.com/assets/71046/7667256/8139206e-fbb6-11e4-98d5-02b12806221f.png)

**Comment by fuzeman** [comment]
Thanks, might have some time to get this done later this week.

**Comment by fuzeman** [comment]
The updated icons + background are on the develop branch now, will release these in a new version later today or tomorrow.

-----------------------------------------------
**Channel Icon**
<img src="https://raw.githubusercontent.com/trakt/Plex-Trakt-Scrobbler/develop/Trakttv.bundle/Contents/Resources/icon-default.png" width="128" height="128" />

**Menu Icons**
<img src="https://raw.githubusercontent.com/trakt/Plex-Trakt-Scrobbler/develop/Trakttv.bundle/Contents/Resources/icon-sync.png" width="128" height="128" /> <img src="https://raw.githubusercontent.com/trakt/Plex-Trakt-Scrobbler/develop/Trakttv.bundle/Contents/Resources/icon-sync_up.png" width="128" height="128" /> <img src="https://raw.githubusercontent.com/trakt/Plex-Trakt-Scrobbler/develop/Trakttv.bundle/Contents/Resources/icon-sync_down.png" width="128" height="128" /> <img src="https://raw.githubusercontent.com/trakt/Plex-Trakt-Scrobbler/develop/Trakttv.bundle/Contents/Resources/icon-about.png" width="128" height="128" /> <img src="https://raw.githubusercontent.com/trakt/Plex-Trakt-Scrobbler/develop/Trakttv.bundle/Contents/Resources/icon-preferences.png" width="128" height="128" />

These icons are from the [Noun Project](https://thenounproject.com/), designed by [Marek Polakovic](https://thenounproject.com/marekpolakovic/).

**Background**
<img src="https://raw.githubusercontent.com/trakt/Plex-Trakt-Scrobbler/develop/Trakttv.bundle/Contents/Resources/art-default.png" />

**Comment by fuzeman** [comment]
Released in [v0.9.1.26](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v0.9.1.26)

**Comment by rectifyer** [comment]
This looks great!
