### ISSUE TITLE
link to unsupported appstore is b0rked

### ISSUE THREAD

**Issue by danielb2** [trakt/Plex-Trakt-Scrobbler#181]

**Comment by KrunchMuffin** [comment]
Same here

**Comment by fuzeman** [comment]
Thanks, will get this link updated shortly.

**Comment by ukdtom** [comment]
UAS is currently offline!

**Comment by fuzeman** [comment]
Fixed the link in the README and thread.

**Note:** the github repository for UAS has been disabled, but downloading UAS via http://bit.ly/ihqmEu (listed on the [thread](https://forums.plex.tv/index.php/topic/151068-unsupported-app-store-as-in-totally-unsupported-is-currently-offline/)) and installing the trakt plugin still works correctly.

**Comment by danielb2** [comment]
thanks!
