### ISSUE TITLE
Constantly Scrobbling The Same 2 Movies Everyday

### ISSUE THREAD

**Issue by 2wenty2wo** [trakt/Plex-Trakt-Scrobbler#182]
Hi,

Firstly, great plugin (has been working great up until now).
I didn't realise I was having an issue until I noticed my trakt profile has the same 2 movies scrobbled as watched everyday (sometimes more than once a day). I haven't watched these movies.
![image](https://cloud.githubusercontent.com/assets/11643336/6819716/bb976682-d319-11e4-8615-4ee11cd21699.png)

I contacted the Plex team and they told me to post here.
Any help would be great, thank you :)

**Comment by fuzeman** [comment]
Which version of the plugin are you using? (displayed in: ```Channels -> trakt -> About```)

Latest version is **0.9.1.23**, try updating if you aren't on this version.

**Comment by 2wenty2wo** [comment]
I just checked and I was running version 0.9.1.12-beta, UnSupported Appstore still tells me thats the latest version for some reason, it won't update via that. :(

I've download the latest version from GitHub to see how it goes, thank you.
