### ISSUE TITLE
Media gets scrobbled when someone plays my media that I shared with them.

### ISSUE THREAD

**Issue by Brianbrifri** [trakt/Plex-Trakt-Scrobbler#186]
So, I have an extensive Plex Library and I share with a couple friends. Sometimes (most of the time) if they watch something from their own account, Trakt (and thus plex as well) sees it as if I watched it and marks that movie/TV show as watched. Would like it so that it does not scrobble what they watch to my trakt account. It loses my place in the tv show queue.

**Comment by fuzeman** [comment]
The best way to filter out watching activity from other accounts is to add your Plex username into the ```Filter - myPlex users``` option.

The ```Filter - Clients``` option is a list of client names that are allowed to scrobble to your trakt.tv account, the client names can be found at ```Settings -> Devices``` on your Plex Media Server.

---------------------------

**Note:** I'm currently working on a big update to support multi-user scrobbling/syncing, this will mean everyone on your server could use trakt.tv (with separate accounts). Watch https://github.com/trakt/Plex-Trakt-Scrobbler/issues/177 for more updates on this feature.

**Comment by Brianbrifri** [comment]
Thank you for the clarification on both what each one does and where to find the client names. Will definitely be keeping a lookout for that feature. Now we just need Trakt to clean up their website :)
