### ISSUE TITLE
feature request: trakt login with pin

### ISSUE THREAD

**Issue by M0UL** [trakt/Plex-Trakt-Scrobbler#188]
adding support for login with pin, with is meant for media center plugins. 
see trakt [api docs] (http://docs.trakt.apiary.io/#reference/authentication-pin) for more info.

**Comment by fuzeman** [comment]
This is supported in the "develop" branch, it still needs further testing before it will be released onto the "master" branch.

**Comment by fuzeman** [comment]
Will be released in the coming **v0.9.9** beta ([discussion](https://github.com/trakt/Plex-Trakt-Scrobbler/issues/194), [updates](https://github.com/trakt/Plex-Trakt-Scrobbler/issues/193))
