### ISSUE TITLE
trakt.tv - 403: "Invalid API Key"

### ISSUE THREAD

**Issue by wingnut092** [trakt/Plex-Trakt-Scrobbler#189]
I've had this error popping up every time i tried to resync for a while now... i tried searching the forums and i haven't found anyone experiencing this issue... am i the only one?

**Comment by fuzeman** [comment]
Strange, must of missed the notification for this issue.

Which version of the plugin are you using? (can be found at ```Channels -> trakt -> About```)

**Comment by wingnut092** [comment]
not a problem.. i appreciate you getting back to me on this...
i'm currently using 0.9.1.25-master

Date: Mon, 11 May 2015 17:46:27 -0700

**Comment by fuzeman** [comment]
Bit of a strange error, my guess is the authentication token for your account isn't being accepted anymore.

Try this (to force the plugin to re-authenticate):
 - Stop Plex Media Server
 - Delete the ```Plex Media Server\Plug-in Support\Data\com.plexapp.plugins.trakttv\Dict``` file *(doing this won't reset the plugin preferences)*
 - Start Plex Media Server again

Look at [this](https://support.plex.tv/hc/en-us/articles/201106098-How-do-I-find-the-Plug-Ins-folder-) page for an idea of where the ```Plex Media Server``` folder is located.

**Comment by wingnut092** [comment]
deleting the file did indeed prompt me with an authentication error but when attempting to reinput my credentials, it tells me that the sync process is already running... it's been like that over night... is there a way to kill the trakt sync process or does restarting the plex service do that? 

Date: Sun, 17 May 2015 17:34:22 -0700

**Comment by cswelin** [comment]
I"m see this same issue, running the latest (9.1.25 master).
Also tried forcing the auth token as well.

Cold this be caused due to the new v2 api?

**Comment by wingnut092** [comment]
ok well crazy thing... it seems to be working now... i did reboot the box a few times after following the instructions above so maybe the process just needed to time out before the fix could actually be applied... i'll update if anything changes but as it stands now, it seems to be working..

**Comment by daften** [comment]
I'm getting a similar error. I did reset my password, but the problems only started occuring lately (i reset my pass a week or 2 ago). It started this evening, a couple of hours ago, when there was no more scrobbling.
