### ISSUE TITLE
Scrobbler doesn't report/scrobbles playback from a remote server.

### ISSUE THREAD

**Issue by SathyaBhat** [trakt/Plex-Trakt-Scrobbler#191]
I noticed that Plex Trakt Scrobbler doesn't seem to scrobble playback from remote servers. is this by design? Is there a way the scrobbler can scrobble plays from remote server? 

I'm on Plex Media Server v0.9.12.0.1071-7b11cfc / Plex Trakt Scrobbler 0.9.1.25-master

Thanks

**Comment by fuzeman** [comment]
The plugin runs on the server, and currently is only designed to scrobble/sync the server administrator account.

https://github.com/trakt/Plex-Trakt-Scrobbler/issues/177 will allow separate trakt.tv accounts for each user on a server, but is still awhile away from a proper release.

**Comment by SathyaBhat** [comment]
Thanks, @fuzeman :)

**Comment by SathyaBhat** [comment]
Dropping in a comment - I'm running PTS development version (.9.9.9). PTS isn't scrobbling plays from remote server - the client filter is set to `*`.

Attached the log file: http://pastebin.com/xLDWR9Xv
