### ISSUE TITLE
Media gets scrobbled when someone plays my media that I shared with them.

### ISSUE THREAD

**Issue by alltimemarr** [trakt/Plex-Trakt-Scrobbler#192]
Hi,

I have the same problem as the guy in issue #186 but wasn't sure if i could comment my problem on his issue, so I opened a new one.

I used the filtering, but it seems like I'm doing something wrong. I don't have a PlexPass, but I shared my login information/account with my sister, so she can login on her laptop, and watch shows and movies i have on mine via Plex. So she's not on another User account (I figured you need a Plex Pass for that... and I'm not really willing to pay, haha! I already pay for Trakt, and have a cinema membership card so yeah.. it must end somewhere, :-P)

I filtered by putting my computer name (MacBook-Pro-van-Marr) in the Filter - Clients field. Also got that from this page:
http://127.0.0.1:32400/clients

"<Server name="MacBook-Pro-van-Marr" host="xxxxx" address="xxxxx" port="3005" machineIdentifier="xxxxx" version="1.3.5.431-7966a4df" protocol="plex" product="Plex Home Theater" deviceClass="HTPC" protocolVersion="1" protocolCapabilities="navigation,playback,timeline,mirror,playqueues"/>"

That didn't work, things my sister played where still on my Trakt account.
So I tried filtering with IP address I found on sites i get when I google "what is my IP", but on the clients site thing, other host/address are listed. But now even my plays aren't going to Trakt.

Now I tried the host/address (both are the same) on the clients page, but that still sends my sister's watching things to Trakt.

I'm not sure what I am doing wrong with the filters? Or is it because my sister is logged in on the same user (but on web while I watch with Plex Home Theater, and she watches on web and on her own computer? So also another IP address..)

**Comment by alltimemarr** [comment]
Okay, I fixed my issue regarding not being able to share my library with other people. My sister now has her own account, but now I can't get the filters to work.

I tried using the Client and Username field, but nothing let's me scrobble..

http://prntscr.com/80gjen
<MediaContainer size="1"><Server name="MacBook-Pro-van-Marjolein" host="xxxx" address="xxxx" port="3005" machineIdentifier="xxxx" version="1.4.1.469-47a90f01" protocol="plex" product="Plex Home Theater" deviceClass="HTPC" protocolVersion="1" protocolCapabilities="navigation,playback,timeline,mirror,playqueues"/></MediaContainer>

I replaced the host/adress/indentifier things with xxxx because i don't know if it's like traceable or private information.

**Comment by Valdimarsson** [comment]
Hi. I had the same problem regarding my sister. She used to log in with my account but now my wife's sister and my brother in law, all use my account. I found out yesterday that they can register sith their own account and I just have to invite them as friends. That doesn't require a plex pass which I don't have either. PM me if you have questions :-)

**Comment by unixjeff** [comment]
I have been trying to get this to work, but every user keeps getting tracked Trakt it my mine but not scroobled so it shows what I'm watching but the marks watched for stuff my kids watch. Any ideas?

**Comment by fuzeman** [comment]
@unixjeff 
 - Which clients (PHT, DLNA, Plex/Web, etc..) are you using to connect to your plex server?
 - What version of the plugin are you using? (can be found in ```Channels -> trakt -> About```)
 - Have you set any values for the "Filter" options yet? (what are they set to?)

**Comment by unixjeff** [comment]
My main client is PHT and the other client is android tv
Version 0.9.1.29 (current master)
I set all the filters

User:user1
Client (PHT):pc
Network:user1ip

Not when I play on the pht it scrobbles correctly but when user2 watches something it shows as watched on trakt

**Comment by fuzeman** [comment]
@unixjeff Does the second user have their watching activity displayed under "(username) is watching" on your trakt account? or is it only marked as watched after a sync?

**Comment by unixjeff** [comment]
After user2's movie is completed it is marked as watched on trakt also it doesn't show "user2 is watching"

**Comment by fuzeman** [comment]
@unixjeff Could you post the latest plugin log file here (upload it to dropbox, pastebin, etc.), see https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files for the location on your system.

**Note:** You will probably need to "watch" something on the second user again so it's visible in the log file, you should be able to just slowly skip through a video instead of actually watching it.

**Comment by elgallo** [comment]
wait, so the filter is set only to yourself? I thought it was to filter (out) other users?

**Comment by fuzeman** [comment]
@elgallo The filters can be defined as:
 - Allowed users: ```one, two```
 - Blocked users (prefixed with a dash): ```-one, -two```

Setting the filter to your username will block any other users from scrobbling.
