### ISSUE TITLE
v0.9.9 (Beta) - Discussion

### ISSUE THREAD

**Issue by fuzeman** [trakt/Plex-Trakt-Scrobbler#194]
This issue will be open for anyone to ask general questions about the **v0.9.9** beta, please open new issues for any bugs/problems you find.

**Comment by lendenrk** [comment]
Hi, 

First of all, thank you for your work, I'm using your plugin since several months and it's great.

I've one question about the new features. Do the next releases will make us to have a Plex account to sign in with on your configuration interface?
Currently, I'm using Plex with local configuration and I don't sign in with my account, so I was wondering how will it be in the next releases.

Thank you.

**Comment by fuzeman** [comment]
@lendenrk you can still use the latest beta version without signing into the new configuration site, the built-in preferences dialog in plex still functions as usual.

The configuration site is just to needed to setup more accounts (for multi-user scrobbling/syncing) or for adjusting the new activity rules.

**Note:** the configuration web-app is completely client-side, everything is still stored on your server.

**Comment by lendenrk** [comment]
Ok, thank you for your answer.

**Comment by rogueosb** [comment]
I'm a bit confused about the new configuration site. I've logged in on my server, and it just shows a mostly blank page with a box labelled "Connect" with nothing inside it. I've tried removing all traces of the plugin, and reinstalling it, but it's still the same. I am on the latest beta (0.9.10.1).

**Comment by fuzeman** [comment]
@rogueosb your servers should be displayed, for example:
![](http://i.imgur.com/iIl35d7.png)

--------------------------

To help debug this issue, could you:
 1. Open the developer console (```Ctrl + Shift + J``` on chrome, ```Ctrl + Shift + K``` on firefox)
 2. Reload the page
 3. Reach the "Connect" page again

Then check the console for any error messages, for example:
![](http://i.imgur.com/ollqwxP.png)

and check the "Network" tab *(in the developer pane)* for any errors, for example:
![](http://i.imgur.com/Tt8RpXi.png)

**Comment by rogueosb** [comment]
Here's the console output:
![image](https://cloud.githubusercontent.com/assets/6019664/8795800/02adf3a4-2f88-11e5-943d-037a068bec63.png)
And the "Network" tab:
![image](https://cloud.githubusercontent.com/assets/6019664/8795831/4dc4df10-2f88-11e5-94e2-a5f993928d4c.png)

This is on the same PC as PMS is installed on, if that matters (although the same thing happens on any PC I've tried).

**Comment by fuzeman** [comment]
@rogueosb just pushed an update that should fix this bug.

Make sure you are on v1.0.8 by clicking on the ```</>``` button in the bottom left:
![](http://i.imgur.com/D8Rj5aU.png)

**Comment by rogueosb** [comment]
That fixed it. Thanks a lot!

**Comment by RykerIX** [comment]
I don't know if this is the right place to post this, but it seems my plex managed users don't get synched at what ever interval setting you choose. Always gotta sync manually. Also, I'm sure this isn't very helpful, but scrobbling is so hit on miss, which is why I'm using the Sync every X time period option.:)

**Comment by fuzeman** [comment]
@RykerIX
Could you open a new issue for the scrobbling issue.

-------------------------

Provide the following details:
 - Plex Media Server version
 - Clients used (Plex/Web, PHT, DLNA, etc..)
 - Latest plugin log file (after you notice issues with scrobbling again)
    - Set ```Logging - Plugin``` to ```DEBUG``` in the plugin preferences (via Plex/Web)
    - See https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files for the location of the log files

**Comment by xzKinGzxBuRnzx** [comment]
@fuzeman 

How do you setup multi-user? I tried switching users but I couldn't modify or even open the settings. Am I missing something? I can modify/open it when signed into my main account but I was hoping to somehow setup syncing for other users, hopefully without effecting my account.

I'm using the latest develop. I'm seeing references above to a new configuration site but I just assumed you meant the hover over Trakt channel and click the gear, bringing up settings. Now I'm not so sure anymore...

**Comment by RykerIX** [comment]
Hey sorry, fuzeman. I haven't been back to the site in awhile. Scrobbling doesn't always work, but I have it set to update every hour which solves that problem for me.  Secondary users are now showing user activity (i.e. what they're watching). I did update to the latest beta, perhaps thats when my problems disappeared. I'm assuming it was updated, anyways, since things started functioning more reliably after re-installing.

KinGz, here: http://trakt-for-plex.github.io/configuration/#/connect

I know, it's hard to find.

**Comment by xzKinGzxBuRnzx** [comment]
@RykerIX 

Thank you! :D

**Comment by NHellFire** [comment]
Configuration interface (Version: 1.2.0, Revision: 63247db) isn't working for me. After I tell it to connect to my PMS, it just sits on loading forever.
Trakttv v0.9.10.13-beta, PMS 0.9.14.6.1620-e0b7243

And the browser console:
```[036e7fe3baed2370e3ccde84f5803907bb1ba41c] Testing connection: https://10-0-0-1.d8dda14b7808451f8755133272f182c8.plex.direct:32400
[036e7fe3baed2370e3ccde84f5803907bb1ba41c] Using connection: https://10-0-0-1.d8dda14b7808451f8755133272f182c8.plex.direct:32400
[036e7fe3baed2370e3ccde84f5803907bb1ba41c] Request "system.ping" Object {args: Array[1], kwargs: undefined}
Legacy response format returned
[036e7fe3baed2370e3ccde84f5803907bb1ba41c] Response null
Potentially unhandled rejection [1] TypeError: Cannot read property 'result' of null
    at http://trakt-for-plex.github.io/configuration/scripts/scripts.4ef01a59.js:2:6277
    at O (http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:21907)
    at K (http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:21539)
    at y.when (http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:25213)
    at v.run (http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:24249)
    at a._drain (http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:27479)
    at drain (http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:27133)
    at MutationObserver.b (http://trakt-for-plex.github.io/configuration/scripts/vendor.859d191d.js:19:9721)```

**Comment by fuzeman** [comment]
@NHellFire That error usually only happens on the master branch, you might want to try a re-install of the beta branch to ensure it's installed correctly.

Also make sure you uninstall the plugin from Unsupported Appstore, otherwise it will likely revert you back to the master branch automatically.

**Comment by NHellFire** [comment]
I've reinstalled the beta branch several times, it still just stays on loading. I've never installed the Unsupported Appstore either (it was down months before I started using Plex), always cloned the git repo myself.

Just looked again, I'm seeing this in the plugin log:
`com.plexapp.plugins.trakttv      (7f8045828700) :  ERROR (com.plexapp.plugins.trakttv:107) - Unable to process API request (args: ('system.ping',), kwargs: {}) - SQLError: no such table: configuration.option`

**Comment by fuzeman** [comment]
@NHellFire Try the following:
 - Shutdown PMS
 - Delete the plugin database at ```[...]\Plex Media Server\Plug-in Support\Databases\com.plexapp.plugins.trakttv.db``` *(including the ```...trakttv.db-shm``` and ```...trakttv.db-wal``` files)*.
 - Start PMS again *(the plugin should then re-create the database with the correct schema)*

If the plugin still has errors in the log file, could you either upload it to dropbox and post a link here or send me an email (me@dgardiner.net) with it attached.

**Comment by NHellFire** [comment]
Deleted all the trakt data from Plug-in Support, still getting errors. It appears to be skipping some of the database creation scripts
[com.plexapp.plugins.trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/83980/com.plexapp.plugins.trakttv.txt)

**Comment by fuzeman** [comment]
@NHellFire Strange, it seems to be starting the database migration at "005_sync_result"...

Could you check that the directory:
```
/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/models/migrations
```
Contains all the files listed at https://github.com/trakt/Plex-Trakt-Scrobbler/tree/beta/Trakttv.bundle/Contents/Libraries/Shared/plugin/models/migrations

**Comment by NHellFire** [comment]
Yep, they're all there

```
nathan:/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/models/migrations$ ls -1
000_initial.py
001_session.py
002_rule.py
003_plex_account.py
004_scheduler.py
005_sync_result.py
006_scheduler_job.py
007_plex_account.py
008_plex_basic_credential.py
009_account.py
010_account.py
011_message.py
012_account.py
013_action.py
__init__.py
nathan:/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/models/migrations$ git status .
# On branch beta
# Your branch is up-to-date with 'origin/beta'.
#
nothing to commit, working directory clean
nathan:/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Libraries/Shared/plugin/models/migrations$ git log -1
commit 3b6ec99ee17f975e91a8d2e729e0655e01d4bcf9
Merge: c7febb8 294efae
Author: Dean Gardiner <me@dgardiner.net>
Date:   Wed Nov 18 22:10:58 2015 +1300

    Merge branch 'hotfix/0.9.10.13-beta' into beta
```

**Comment by fuzeman** [comment]
@NHellFire let's continue this in #258, will have possible fix that you can test soon.

**Comment by fuzeman** [comment]
**v1.0.0.3** has been released: https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.0.0.3

This brings an end to the v0.9.9/v0.9.10 beta :smiley:
