### ISSUE TITLE
Tv Shows Metadata Refuses to download with Trakt Plugin Installed

### ISSUE THREAD

**Issue by XxUnkn0wnxX** [trakt/Plex-Trakt-Scrobbler#204]
over the past 3 weeks the Metadata for all my shows have been really slow they do download eventually like 5-6 hours later.
i check theTVDB and the metadata is already there but plex doest seem to grab it.

![image](https://cloud.githubusercontent.com/assets/2242880/8761758/15dc6f3a-2da5-11e5-83ef-327ad4f5384b.png)

is any one else been having this issue recently cozz i tired of Metadata not being grabbed. i keep on trying to manually refresh but it doesnt download the Metadata..

when i removed the plugin and restarted plex Metadata downloaded right away after i updated library. but with this plugin installed Metadata refuses to download.

**Comment by XxUnkn0wnxX** [comment]
ok may have fixed the issue for now but it happens to often with this plugin installed...

i set matcher to Plex instead of Plex Extended & rating conflict resolution to Latest and restarted server and ran few tests & Metadata seems to download fine then...

**Comment by fuzeman** [comment]
Are you using the stable release *(v0.9.1.26)*, with "Sync - Run after library updates" enabled?

This could possibly delay metadata processing if the sync is started before plex has completely finished downloading metadata.

Having a short delay on "Sync - Run after library updates" *(waiting until all your metadata has finished processing)* would probably help quite a bit.

-----------------------

**Note:** "Plex Extended" runs an extra matcher on file names to find multiple episodes *(E01E02, E01-03, etc..)* properly, as plex itself doesn't support this very well.

**Comment by XxUnkn0wnxX** [comment]
i have it set to: Sync - Run every 3 hours & Sync - Run after library updates but i don't see any delay functions in the settings.. because when Library updates i would assume both Plex and plugin start running there scripts at the same time and stuffs up around there.. 

i am running the stable release.. and yes having the ability to run after library updates + a Timed delay  should solve it... (ATM i see no such function)

**Comment by fuzeman** [comment]
The new implementation of ```Sync - Run after library updates``` in **[v0.9.10.4-beta](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v0.9.10.4-beta)** waits until metadata has finished downloading completely.

**Note:** The ```Sync - Run every``` option doesn't wait until a library update has finished, might implement this in the future.
