### ISSUE TITLE
Problem signing in

### ISSUE THREAD

**Issue by tlauen** [trakt/Plex-Trakt-Scrobbler#207]
I've downloaded the Trakttv.bundle file (tried with both the stable and beta version) and installed it in the proper folder (~/Library/Application Support/Plex Media Server/Plug-ins). But when I try to open the Trakt settings under Channels (both locally and on plex.tv/web) there's no Trakt.tv channel to choose. 

Bottom line, can't enter my trakt.tv creditentials anywhere. What to do?

**Comment by fuzeman** [comment]
This likely means the plugin crashed on startup.

Could you upload the plugin log files, see https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log_Files for more details on the location of them.

**Comment by tlauen** [comment]
I uploaded them here: http://jmp.sh/0TvWa6w

**Comment by fuzeman** [comment]
Strange, can't see any issues in the log files..

Try this direct link to the channel:
[http://localhost:32400/web/index.html#!/server/0fb3bbe2e972c5a6ad1e0c54f745f74168b09e3d/channel/%2Fvideo%2Ftrakt](http://localhost:32400/web/index.html#!/server/0fb3bbe2e972c5a6ad1e0c54f745f74168b09e3d/channel/%2Fvideo%2Ftrakt)

If that doesn't work, the "Plex Media Server.log" log file might give some pointers, see https://support.plex.tv/hc/en-us/articles/200250417 for the location of them.

**Comment by tlauen** [comment]
I managed to add the pin in the settings using the direct link. Seems like it works now :)
