### ISSUE TITLE
Global filter problem

### ISSUE THREAD

**Issue by saitoh183** [trakt/Plex-Trakt-Scrobbler#209]
I dont think the "Global Filter - Libraries" doesnt seem to work when i use manual Push TV and show is scrobbled. I set up the filter to exclude my Kids TV show and Movies.

my current list: Anime,French TV,Movies,UFC,TV Shows. I dont have a log at the moment but will post one if you need it

**Comment by fuzeman** [comment]
Yeah, "Global Filter - Libraries" isn't applied to syncs on the current beta release. I've got it implemented on the development branch now and will be included in a new beta release later today.

**Note:** the current development version of the plugin isn't compatible with the current release of http://trakt-for-plex.github.io/configuration, the configuration interface might not work correctly if you update before the official beta release.

**Comment by saitoh183** [comment]
Ok I will wait for the beta

**Comment by fuzeman** [comment]
Released in [v0.9.10.3-beta](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v0.9.10.3-beta)
