### ISSUE TITLE
Pull from trakt failed (AttributeError: "'NoneType' object has no attribute 'rfind'").

### ISSUE THREAD

**Issue by Rumik** [trakt/Plex-Trakt-Scrobbler#211]
Hi there,

Using the latest master release on the latest trakt server, running on my QNAP NAS. Getting this error when trying to sync down from trakt.tv.

Any ideas?

Thanks!

**Comment by fuzeman** [comment]
Will look into this bug now.

**Comment by fuzeman** [comment]
This issue should be fixed in [v0.9.1.28](https://forums.plex.tv/discussion/comment/982372/#Comment_982372), let me know if the issue is still happening after updating.

**Comment by mbze430** [comment]
I am on 9.1.29-master and its been 12 days since I haven't been able to sync and the message I am getting is failed (AttributeError:"'NoneType' object has no attribute 'rfind'")
