### ISSUE TITLE
Sync intervals question

### ISSUE THREAD

**Issue by saitoh183** [trakt/Plex-Trakt-Scrobbler#215]
I would like to know if this works with the new version of trakt? Like i would like trakt to do a push pull every Day. what is the order of execution? Will pull first and then push?

I ask because given my current situation, im forced to use Emby with Kodi because the latest Plexbmc plugin is not really cutting it.(wife is nagging me) So in order to keep watched status up to date on plex, i will use trakt to pull watched and push anything i have watched when offline to trakt but i would not want it to mark stuff on trakt that i have watched via Emby to unwatched because plex has a it as unwatched still.

My goal is to run pull on Trakt on Emby every morning at 6am and run Plex at a interval of "Day" just for my account (set it in the multiuser configuration page)

Also if we are using multiuser, we should not use the configuration menu in the trakt channel except for the Global library filter?

**Comment by fuzeman** [comment]
> I would like to know if this works with the new version of trakt?

I haven't encountered any issues with the new sync intervals feature on the development branch, the official beta release has just been delayed until some features are finished up on the new configuration interface.

> Like i would like trakt to do a push pull every Day. what is the order of execution? Will pull first and then push?

It triggers a full sync (Quick Pull, then Push).

> ...i would not want it to mark stuff on trakt that i have watched via Emby to unwatched because plex has a it as unwatched still.

A full sync will update plex with any changes from trakt first, so this shouldn't happen.

> Also if we are using multiuser, we should not use the configuration menu in the trakt channel except for the Global library filter?

The configuration dialog in plex itself is still functional, any option changes are migrated into the new configuration system.

**Note:** All the account-level options *(Authentication, Scrobble, Sync)* are applied to your administrator account.
