### ISSUE TITLE
Disabling scrobbling for DLNA?

### ISSUE THREAD

**Issue by fokum8** [trakt/Plex-Trakt-Scrobbler#217]
Is there any way that I can disable scrobbling when watching from DLNA enabled devices? When other people in my house watch my plex content through DLNA, it logs on Trakt. How can I stop this?

**Comment by fuzeman** [comment]
I'll need to do some testing to work out if this is possible, will try have an answer for you later today.

**Comment by fuzeman** [comment]
This will require some changes to the plugin, will let you know here when it's been implemented.

**Comment by fokum8** [comment]
Okay, thank you :)

**Comment by fuzeman** [comment]
I've implemented this on the beta version in the [feature/TFP-124](https://github.com/fuzeman/Plex-Trakt-Scrobbler/tree/feature/TFP-124) branch, you can download it here: [feature/TFP-124.zip](https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/feature/TFP-124.zip)

After some more testing this will be merged into the beta and stable branches.

----------------------------

You just need to use the ```#dlna``` identifier in the "Global Filter - Client Names" field, for example to exclude all DLNA clients use ```-#dlna```:
![](http://i.imgur.com/wBMUjx2.png)

**Comment by fokum8** [comment]
Hey Dean. Thank you for doing this. I'll check it out when I get back from
vacation!

**Comment by fuzeman** [comment]
This feature was included back in [v0.9.10.9-beta](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v0.9.10.9-beta), let me know if you have any issues with it.
