### ISSUE TITLE
Mark items found in Plex as Collected on Trakt

### ISSUE THREAD

**Issue by Anahkiasen** [trakt/Plex-Trakt-Scrobbler#220]
The Kodi plugin for Trakt does this, but this one doesn't seem to, would be a great feature

**Comment by fuzeman** [comment]
This feature is supported, have you enabled it in the settings?
![](http://i.imgur.com/hpETAqC.png)

**Comment by Anahkiasen** [comment]
I had missed that option somehow, nevermind me :p
