### ISSUE TITLE
Is there a way to auto update the plugin ?

### ISSUE THREAD

**Issue by gotson** [trakt/Plex-Trakt-Scrobbler#225]
I had to manually update recently from my 0.8.x version, since the plugin is not offered on the plex store.
How can one automatically update the plugin when stable releases are available ?

**Comment by fuzeman** [comment]
[Unsupported App store](https://forums.plex.tv/discussion/151068/unsupported-app-store-as-in-totally-unsupported-is-currently-offline/p1) is currently the only way to automatically update the plugin. It's currently listed as "offline", but the download listed ([here](http://bit.ly/ihqmEu)) should still work and will allow you to install the master/stable version of the trakt plugin. *(there is currently no way to automatically install updates for the beta version)*

I'm planning on integrating automatic updates into the plugin itself, this will still be awhile away though.
