### ISSUE TITLE
Pull from trakt returns error: "Unable to construct task"

### ISSUE THREAD

**Issue by isadic** [trakt/Plex-Trakt-Scrobbler#228]
Full sync doesn't return any error, but it seems not to working, in fact all the content is still in unwatched status.

Latest beta plugin version, latest version Plex Media Server.

Here is my "Pull from trakt" log:
http://pastebin.com/M3kJevgM

**Comment by fuzeman** [comment]
That looks like the media server log file (```Logs\Plex Media Server.log```), could you upload the latest plugin log file (```Logs\PMS Plugin Logs\com.plexapp.plugins.trakttv.log```) after attempting another sync.

**Comment by fuzeman** [comment]
Possibly fixed on the "develop" branch, download here: https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip

**Comment by isadic** [comment]
Sorry for the late answer, now seems to work, thank you so much!
