### ISSUE TITLE
Cannot Connect to API

### ISSUE THREAD

**Issue by pcjonathan** [trakt/Plex-Trakt-Scrobbler#233]
Syncing has stopped working over the past day or two (on develop branch). Trying to sync manually gives me this error message:

`Last run just a moment ago, taking less than a second, failed (hostname 'api-v2launch.trakt.tv' doesn't match either of 'ssl276353.cloudflaressl.com', '*.altorendimientoacademico.com', '*.baseshare.com', '*.campusqueretaro.net', '*.deeliciousfastfood.co.uk', '*.destinyrescue.org', '*.digitalbhoomi.com', '*.digitaldripped.com', '*.foerstehjaelpsshoppen.dk', '*.goodtimes.com.pk', '*.mobilewebsitesbyams.com', '*.nitexcite.com', '*.northaid.com', '*.parquetecnologico.mx', '*.spiritwear.com', '*.trakt.us', '*.vinoshipper.com', '*.watersidenursery.co.uk', '*.yellow.com.mt', 'altorendimientoacademico.com', 'baseshare.com', 'campusqueretaro.net', 'deeliciousfastfood.co.uk', 'destinyrescue.org', 'digitalbhoomi.com', 'digitaldripped.com', 'foerstehjaelpsshoppen.dk', 'goodtimes.com.pk', 'mobilewebsitesbyams.com', 'nitexcite.com', 'northaid.com', 'parquetecnologico.mx', 'spiritwear.com', 'trakt.us', 'vinoshipper.com', 'watersidenursery.co.uk', 'yellow.com.mt').`

Attempting to uninstall and reinstall from the master branch only netted me a "Invalid credentials" error in the end.

**Comment by regisbsb** [comment]
me too!

**Comment by fuzeman** [comment]
I'm getting the same error here as well, looks like a cloudflare configuration issue.

@rectifyer

**Comment by w13rdo** [comment]
same issue, since the most recent Plex update though...  Before that, it was logging fine. Something in Plex?

**Comment by DPalmarRibeiro** [comment]
Same issue here. It stopped syncing yesterday

**Comment by fuzeman** [comment]
After some more testing it appears this is a result of the plugin not supporting [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication).

Working on a fix now.

**Comment by elronino83** [comment]
+1 for the issue.

**Comment by Razzeee** [comment]
@fuzeman 
@rectifyer is on vacation right now

is it really down to SNI? will you add this to trakt.py or to the plugin itself?

**Comment by GDog1985** [comment]
as of 8/21/15  this my logs <script src="https://gist.github.com/GDog1985/9a1824e11073f8da4515.js"></script>

**Comment by SolidSnke** [comment]
Working again.

**Comment by DPalmarRibeiro** [comment]
Perfect! Thanks ;)

**Comment by Razzeee** [comment]
Seems like cloudflare fixed it.

**Comment by fuzeman** [comment]
Looks like "trakt.tv" was added back to the default certificate for cloudflare, so everything should be working again.

----------------

@Razzeee 
Yeah, forgot he was away.

I was going to bundle a compiled version of pyOpenSSL with the plugin to support SNI, might still do this to avoid any future SNI issues.
