### ISSUE TITLE
Offline viewing timestamp reported to Trakt

### ISSUE THREAD

**Issue by burkasaurusrex** [trakt/Plex-Trakt-Scrobbler#234]
I regularly view content offline that I have sync'd to my tablet. When I bring that tablet back online, all of the content which I viewed is marked as watched in Trakt, which is great. However, the "viewed" timestamp that is reported to Trakt is the time that I brought the tablet back online, not the time I actually viewed the video.

I'm guessing there might be some limitations here if Plex isn't reporting the actual "viewed" timestamp?

**Comment by fuzeman** [comment]
This is likely a limitation with plex, the plugin just uses the last viewed timestamp from the plex database.
