### ISSUE TITLE
Non-watched items syncing to Trakt as watched

### ISSUE THREAD

**Issue by bpfeil** [trakt/Plex-Trakt-Scrobbler#236]
This started a week ago and items that had been previously watched in both Trakt and Plex synced again as watched.  I also had shows that had never been watched along with episodes on shows that had been watched show up in that sync.  I cleaned the issues out of Trakt, 30+ pages, rebuild by library in Plex and the issue continues to come back.  Even with the issues out of Trakt the same shows get marked as watched in Plex and Trakt.  I verified the only thing feeding Trakt is my Plex plug in.

**Comment by fuzeman** [comment]
What version of the plugin are you using? *(visible in ```Channels -> trakt -> About```)*

The plugin logs after a sync will help to work out what's happening:
 - Change the "Logging" options in the plugin settings to "DEBUG"
 - Run a full sync
 - Upload the plugin logs to dropbox, or pastebin, etc.. (see https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files for the location of them)

**Comment by bpfeil** [comment]
0.9.1.29-master

Here's my log.  https://dl.dropboxusercontent.com/u/6035546/com.plexapp.plugins.trakttv.log I haven't seen the issue since I turned "Sync - Watched" to Pull and not on push + pull.

**Comment by fuzeman** [comment]
Can't see any obvious bugs in the log file, this issue might be already fixed in the beta version if you wanted to enable pushing for "Sync - Watched" again.

**Comment by tmThEMaN** [comment]
I faced a similar issue. I suspect this is because the Library is shared with other users and their watching status is being counted as well. Could that be the reason? and can you make an option to choose which user watched list is scrobbled
