### ISSUE TITLE
View status on plex not syncing in master or devloper

### ISSUE THREAD

**Issue by MadCat1** [trakt/Plex-Trakt-Scrobbler#237]
Hello,
First let me begin by stating that this is something I am probably doing wrong with that being said, any help at all would be great! 

Basically I have a home pc running windows 7 that has plex media server installed on it that we use for the rokus in my house. I also run a remote server, seedbox, running Ubuntu 12 that also has plex media server. Whenever I am away from my home due to the speed and amount of bandwidth that I can get from my remote server vs the slow internet speed at my house I access the remote server to view content. 

I have installed the trakt channel on both and I see that my trakt channel is sending info to the trakt.tv website because I added just a show to my seedbox and not on my home computer and did a trakt sync and it appears in my trakt collection. Also I have several shows on my home server that is not on my seedbox and they appear in my trakt collection after a sync. 

The wall that I keep running up against is that I can not get a tv show or movie that is on both servers to sync up the view status, so that I can stop watching on one and then pick back up from where I left off at on the other one.  Currently if I start watching something on the seedbox and then try to finish it on my home server, plex thinks I have not started it all and starts from the beginning again, and vice versa, and thoughts?

I have tried both the master channel and the developer channel with the same results, any help at all would be great.

**Comment by MadCat1** [comment]
Sorry I had to respond to my self, i just learned that what I was talking about is not what trakt does, it syncs your completed watched status or unwatched status, it does not sync the place where  you stopped at during a show between servers.

**Comment by fuzeman** [comment]
The "Sync - Playback Progress" option allows you to sync your movie/episode watched progress between clients/servers via trakt. You just need to run another sync on the "destination" server to retrieve the latest watched progress from trakt.
