### ISSUE TITLE
Wrong title on trakt.tv

### ISSUE THREAD

**Issue by mchiareli** [trakt/Plex-Trakt-Scrobbler#242]
I am watching Shameless UK on netflix and the plugin is sending my current watch status as Shameless US to trakt.tv.

My account is from a country that does not have the UK version, but i use an VPN to watch series from another countries, this may be the problem.

**Comment by fuzeman** [comment]
I'll try have a look this week, moving this issue to https://github.com/fuzeman/trakt-for-netflix/issues/1
