### ISSUE TITLE
v0.9.10.13-beta Issue Debian Wheezy

### ISSUE THREAD

**Issue by firsttris** [trakt/Plex-Trakt-Scrobbler#244]
Installing v0.9.10.13-beta on Debian Wheezy 

Plex Server Version 0.9.12.19

Im getting the following error:

http://pastebin.com/Dc3NUTY6

Did i miss something?

Regards
firsttris

**Comment by fuzeman** [comment]
This probably means the native libraries aren't compatible with your system.  Which processor architecture do you have Debian running on (x86, arm, etc..)?

**Comment by firsttris** [comment]
root@tvserv:~# uname -a
Linux tvserv 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6~bpo70+1 (2015-11-11) x86_64 GNU/Linux

**Comment by fuzeman** [comment]
Could you check the permissions set for this file:
```
/media/aae44b83-e5cb-47b3-8782-f1da3bfb7da9/plexmediaserver/Library/Application Support/Plex Media Server/Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries/Linux/x86_64/ucs4/apsw.so
```

The user running PMS needs execute permissions on all the ```*.so``` files in ```Plug-in Support/Data/com.plexapp.plugins.trakttv/Libraries```.

**Comment by firsttris** [comment]
Hello,

was on holiday sorry for the late reply..

the file exists and has the following premissions: 0777 (means all user can access,read,modify)
user and group is "plex"

i have not changed premissions.

regards
tristan

**Comment by fuzeman** [comment]
Strange, not really sure what the issue could be... I'll try start up a VM and do some tests this week.

**Comment by ExXxtr3me** [comment]
Any news on this? Have the same error on my server using OpenMediaVault 3. All permissions set right.

**Comment by fuzeman** [comment]
Sorry this issue wasn't updated sooner, see [this comment](https://github.com/trakt/Plex-Trakt-Scrobbler/issues/278#issuecomment-197817330) for a solution.

**Note:** you don't need to install the version of the plugin mentioned in the comment, these changes are available in the latest release.
