### ISSUE TITLE
v0.9.1.29 not scrobbling watched shows with Plex Media Server version 0.9.14.4 on Windows 10

### ISSUE THREAD

**Issue by camtf** [trakt/Plex-Trakt-Scrobbler#245]
Guys please forgive me if I am doing something wrong. I've used Plex with Trakt on Linux systems before and it has worked well. I've recently set up a new server using Windows 10 and while it was able to successfully pull the watched status of all shows, it is not scrobbling any new watched shows. I've had a quick look at the logs and can't see anything unusual. Here are the system details:

Windows 10 version 1511
Plex Media Server Plex Pass version 0.9.14.4.1556-a10e3c2
Trakt plugin version v0.9.1.29-master

I should also mention that I've got 12 different libraries on the server, I'm using the filter functionality to limit scrobbling to three of them only. I am wondering if this could be causing the issue I am experiencing.

Please let me know if you would like me to submit any further info to assist in resolving this issue.

Thanks for all all your hard work. I find this plugin to be very useful.

**Comment by fuzeman** [comment]
I'm not aware of any scrobbling issues currently (except the odd trakt.tv server issues).

Could you send me the latest plugin log file (after watching something in plex again), either post a link here, or email me a link (me@dgardiner.net) if you don't want the log file public.

**Comment by camtf** [comment]
Sorry for wasting your time with this. Upon further investigation it was an error with the way I set the filters and the plugin is working correctly.
