### ISSUE TITLE
Out of memory with 0.9.10.13-beta

### ISSUE THREAD

**Issue by Dahlgren** [trakt/Plex-Trakt-Scrobbler#247]
Doing sync or push, either all or just one section, exhausts all memory on the host forcing the OS to kill the python trakt process. This is on a 64bit Linux OS with 64GB RAM. At around 50-60GB it's killed. Usage was confirmed in top and htop. The process restarts afterwards. Scrobbling after playing works fine most of the time.

**Comment by fuzeman** [comment]
That's strange, never seen the beta branch consume anywhere near that amount of memory on my server (usually sits around 100 - 200MB for me, with a small increase during syncs).

-----------

Could you send me the plugin log files after the process is killed? feel free to email me a link (me@dgardiner.net) if you don't want it public.

Could you also give me a rough idea of how many movies/episode you have in plex? this will help me reproduce the issue if there isn't anything obvious in the log file.

**Comment by Dahlgren** [comment]
I've sent you an email with logs and some plex statistics

**Comment by fuzeman** [comment]
Can't see any obvious problems in that log file, could you send me another log file after setting the log level options to this (and running another sync):
![](https://i.imgur.com/JlwJ5fA.png)

**Comment by Dahlgren** [comment]
New log file sent

**Comment by fuzeman** [comment]
I'm currently thinking this is an issue with the "Plex Extended" matcher (required to support ```S01E01-02``` and ```S01E01E02``` style episodes).

--------------------------

I've made some changes in the ```issue/247``` branch which fixes a bug with the "Matcher" preference and adds some extra debug messages, so could you install this version of the plugin: https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/issue/247.zip

In the settings change the "Matcher" option from "Plex Extended" to "Plex", then run another sync and let me know what happens *(+ send me the latest log file)*.

**Comment by Dahlgren** [comment]
Downloading the 247 version and using Matcher "Plex" worked great! New logs sent in separate mail

**Comment by fuzeman** [comment]
Interesting, so there must be an episode that causes the "Plex Extended" matcher to start consuming all your memory.

Would you be able to run another sync with the "Matcher" option set back to "Plex Extended" and send me the log files again, this should tell us exactly which episode is causing the issue.

**Comment by Dahlgren** [comment]
Sadly I'm unable to provide it due to switching from Plex

**Comment by fuzeman** [comment]
This issue should be fixed on the "develop" branch now.
