### ISSUE TITLE
Scobbler not working under 0.9.12.19

### ISSUE THREAD

**Issue by rays23** [trakt/Plex-Trakt-Scrobbler#248]
Hi there,

installed the scrobbler under 0.9.12.19.

When opening http://127.0.0.1:32400/web/index.html#!/server/my_machine_id/channel/%2Fvideo%2Ftrakt

i get: "This Channel is not reacting." (in German)

The scrobbler file path is:  
![scobbler](https://cloud.githubusercontent.com/assets/10528245/11838850/ce038f2a-a3e9-11e5-89b0-b12a9153325d.JPG)

**Comment by fuzeman** [comment]
Could you send me the latest plugin log file ([details](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files)), either post a link here, or email me a link (me@dgardiner.net) if you don't want the log file public.

**Comment by rays23** [comment]
Well... would love to, but there are only agents (com.plexapp.agents.nameofagent.log) and com.plexapp.system,logs available. Within the logs there was no traktv related log file.

**Comment by fuzeman** [comment]
That usually means the plugin isn't installed correctly, or PMS isn't starting the plugin for some reason.

--------------

Could you check the ```Plug-ins/Trakttv.bundle``` folder looks like this:
![](https://i.imgur.com/9xxVmoC.png)

If you have another ```Trakttv.bundle``` folder inside, move it out into the ```Plug-ins``` directory.

**Comment by rays23** [comment]
Everything is in the place where
![screenshot 2015-12-19 10 27 34](https://cloud.githubusercontent.com/assets/10528245/11912403/a14a92f4-a63b-11e5-9f07-12ed0a3abfcd.png)
 it should be.

**Comment by fuzeman** [comment]
Hmm, not sure what could be causing this..

Could you restart PMS (so the server attempts to start the plugin again), then send me the latest ```Plex Media Server.log``` file ([details](https://support.plex.tv/hc/en-us/articles/200250417-Plex-Media-Server-Log-Files)).

**Comment by rays23** [comment]
Hi Dean,

please find the Logfile attached.

Kind regards,

Rainer

**Comment by casperstorm** [comment]
Any update on this? I get `ServerError: Gateway Timeout - "server timeout"`

**Comment by fuzeman** [comment]
@rays23 Attachments aren't available through github issues, could you either send it to me directly (me@dgardiner.net) or upload it to dropbox or pastebin, etc..

Sorry for the late response, had a break over christmas :smile:

**Comment by fuzeman** [comment]
Snippet from your log file:
> Dec 19, 2015 17:56:07 ERROR - Couldn't check for the existence of file /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Info.plist: boost::filesystem::status: **Permission denied: "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Info.plist"**

> Dec 19, 2015 17:56:07 WARN - Couldn't determine bundle identifier for plug-in at: /var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle

----------------------------------

Looks like plex doesn't have permissions to access the plugin bundle?

Something like the following command should correct this *(assuming PMS runs under the "plex" user)*:
```
chown -R plex:plex "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle"
```

**Comment by mxlian** [comment]
Setting the permissions right seems to fix the problem :+1:

**Comment by rays23** [comment]
Big thanks to fuzeman and mxlian... you guys are awesome!
