### ISSUE TITLE
New show The Magicians (2016) is synced as the old show from 2011 by the same name

### ISSUE THREAD

**Issue by Wyled** [trakt/Plex-Trakt-Scrobbler#249]
Folder name on my computer is "The Magicians (2016)",
The show appears correctly in PMS, but not on Trakt.

Using version 0.9.1.29-master

**Comment by fuzeman** [comment]
Could you do the following steps to get the episode "guid":

1. Open one of the episodes in Plex/Web

2. Click "Info"
![](https://i.imgur.com/bW0IjpG.png)

3. Click "View XML"
![](https://i.imgur.com/GtJL9FG.png)

4. Post the value of the "guid" attribute here (should look similar to ```guid="com.plexapp.agents.thetvdb://71656/1/1?lang=en"```)

**Comment by Wyled** [comment]
guid="com.plexapp.agents.thetvdb://299139/1/1?lang=en"

**Comment by fuzeman** [comment]
Maybe the show was synced before Plex finished matching the show, this could mean it was sent to trakt without the year and tvdb identifier.

I'm pretty sure this issue has been fixed in the beta branch with the new syncing scheduler, will need to do some testing to confirm this.
