### ISSUE TITLE
Realtime data push not working to Trakt.com

### ISSUE THREAD

**Issue by dietler** [trakt/Plex-Trakt-Scrobbler#250]
Manual and scheduled syncs are working but I no longer get real time progress status on trakt.com. I was on an older version but upgraded to 0.9.1.29 and the same problem persits. Maybe something on Trakt's API side has changed? Just started having this problem about 4 days ago.

**Comment by fuzeman** [comment]
Could you send me the latest plugin log file ([details](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files)), either post a link here, or email me a link (me@dgardiner.net) if you don't want the log file public.

Before uploading the log file, could you:
 - Set the ```Logging - Plugin``` and ```Logging - Libraries``` options to ```DEBUG``` (in the plugin settings at Plex/Web)
 - Watch something on the server (you can just slowly skip through it)

**Comment by dietler** [comment]
I did some more testing and it seems that everything works as expected from both the web client and Plex Home Theater, but when you use the new Plex Media Player as the client it doesn't to the real time scrobbling.

Here is the log file:
https://gist.github.com/dietler/b1718fd5df494309b090

**Comment by fuzeman** [comment]
I'm seeing these messages in your log file:
```
2015-12-19 08:38:00,960 - [plugin.pts.scrobbler] Ignoring item [11556](Teachers (2016)) played by filtered "scrobble_names": ''
2015-12-19 13:54:27,670 - [plugin.pts.scrobbler] Ignoring item [11538](Fargo) played by filtered "scrobble_names": ''
```

These messages indicate a client is being filtered, possibly Plex Media Player? as the client doesn't have a name it won't match the clients filter correctly.

I can confirm Plex Media Player v1.0.3 (on Windows 10) does return a client name correctly, so maybe it's something specific with your setup?

---------------------

You could also try the beta branch, it has a new client filtering interface (in the web interface at http://trakt-for-plex.github.io/configuration).

Example:
![](https://i.imgur.com/a7z8NqQ.png)

**Comment by dietler** [comment]
The beta branch version worked. Thanks!
