### ISSUE TITLE
Plugin not loading under PMS 0.9.15.0

### ISSUE THREAD

**Issue by pax0707** [trakt/Plex-Trakt-Scrobbler#251]
[com.plexapp.plugins.trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/73129/com.plexapp.plugins.trakttv.txt)

**Comment by fuzeman** [comment]
I've just tested the plugin with PMS v0.9.15.0 (upgraded from v0.9.14.5) and don't see any issues. So there must be something else causing this issue on your system.

--------------------------------

Could you first make sure the VC++ 2013 runtime is installed ([vcredist_x86.exe](https://www.microsoft.com/en-us/download/details.aspx?id=40784)), then restart PMS to see if the plugin starts up correctly.

**Comment by pax0707** [comment]
Installing VC++ 2013 fixed it.

It stopped working on same day I updated to PMS v0.9.15.0.
I see it installed VC++ 2015.

**Comment by flosoft** [comment]
This fixed it for me too. It did take a restart of the computer as well and then a bit of time for the channel to re-appear in the channel list.

**Comment by fuzeman** [comment]
I'll keep this open to ensure people are aware of this issue, planning on fixing it with #255 in a future release.

**Comment by fuzeman** [comment]
VC14 / VS2015 libraries have been added to the "develop" branch, will be available in the next beta release.
