### ISSUE TITLE
This plugin is AWESOME

### ISSUE THREAD

**Issue by danielb2** [trakt/Plex-Trakt-Scrobbler#252]
Really, this is just to say that, and to say THANK YOU for writing this and keeping it up to date.

I'm also curious. Why is this not a plugin available from plex in the plex channels?

**Comment by fuzeman** [comment]
Thanks :smiley:

I know updates have been a bit slow lately, will be trying to get the beta branch finished up this month though. After the current beta is finished up and released onto the stable channel I can start looking at new improvements/features that have been requested.

-------------------------------------------

> Why is this not a plugin available from plex in the plex channels?

Channels available from the "Channel Directory" are usually very basic wrappers of specific services/websites, so this plugin doesn't really fit as it has quite a large code-base and requires many third-party libraries *(+ native libraries compiled for each platform)*.

Never talked to anyone at Plex about the plugin, so have no idea what their view is. They don't seem too interested in continuing to support plugins though *(very little in the way of plugin framework improvements in years)*

**Comment by danielb2** [comment]
Awesome answer. Thanks :) The FAQ looks very empty, this could be in it :P

**Comment by fuzeman** [comment]
Yeah, finishing up the wiki is on the to-do list :smile:
