### ISSUE TITLE
Database migrations are skipped on some systems

### ISSUE THREAD

**Issue by fuzeman** [trakt/Plex-Trakt-Scrobbler#258]
Database migrations are skipped on some systems leading to an invalid database schema.

```
2016-01-10 04:54:00,602 - INFO - Start migrations
2016-01-10 04:54:00,604 - INFO - Run "005_sync_result"
2016-01-10 04:54:00,606 - INFO - Start migration 005_sync_result
2016-01-10 04:54:00,606 - ERROR - SQLError: no such table: sync.result
```

-----------------------

Issue was initially reported here: https://github.com/trakt/Plex-Trakt-Scrobbler/issues/194#issuecomment-170302506

**Comment by fuzeman** [comment]
@NHellFire I've made some changes in my **[issue/258](https://github.com/fuzeman/Plex-Trakt-Scrobbler/tree/issue/258)** branch ([zip](https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/issue/258.zip)). Delete the plugin database (as described in https://github.com/trakt/Plex-Trakt-Scrobbler/issues/194#issuecomment-170314187), then start PMS again. 

This branch also writes some more messages into the log file, so send me the log file again if there is still an issue.

**Comment by NHellFire** [comment]
That's working now, thanks :D
