### ISSUE TITLE
Plugin not loading under PMS 0.9.15.1

### ISSUE THREAD

**Issue by TheLuckiest** [trakt/Plex-Trakt-Scrobbler#262]
Neither the master or beta versions will load under the new PMS version.

Logs:
* [com.plexapp.plugins.trakttv_master.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/91537/com.plexapp.plugins.trakttv_master.log.txt)
* [com.plexapp.plugins.trakttv_beta.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/91539/com.plexapp.plugins.trakttv_beta.log.txt)

As was suggested in another issue, I tried installing VC++ 2013 and rebooting, but no change.

Any help here would be much appreciated, this is by far my favorite Plex plugin!!

Thank you!

**Comment by fuzeman** [comment]
It doesn't look like the plugin has been installed correctly as the log files mention missing modules and DLLs.

**Note:** Just tested the latest version of Plex Media Server (v0.9.15.1.1639-26325ea) and haven't seen any issues with the plugin, so there must be something specific with your system that is causing this issue.

--------------------------------

Could you try install the plugin again by following these steps:

1. Shutdown Plex Media Server
2. Delete the existing ```Trakttv.bundle``` folder in your plex ```Plug-ins``` folder
3. Extract + Copy the latest beta version into your plex ```Plug-ins``` folder ([zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/beta.zip))
4. Start Plex Media Server

Post the latest log file here if the plugin still isn't visible under "Channels" on your server.

**Comment by TheLuckiest** [comment]
That worked! Thanks so much. I have no idea why it worked this time and not the times I had done it previously.

Cheers! :)

**Comment by fuzeman** [comment]
No problem, glad you got it working :smiley:
