### ISSUE TITLE
add plugin to the unsupported appstore v2

### ISSUE THREAD

**Issue by M0UL** [trakt/Plex-Trakt-Scrobbler#264]
plz add this plugin to  the new unsupported appstore
http://forums.plex.tv/discussion/202282/unsupported-appstore-v2-as-in-totally-unsupported

**Comment by fuzeman** [comment]
Looks like the plugin can be added soon, just waiting for the enhancement in https://github.com/dagalufh/WebTools.bundle/issues/116 to be released.

**Comment by ukdtom** [comment]
Just needs to round up another thing, and then we'll go :-)

Do feel free to add to the Repo now, and I'll postpone the merge, until next release

**Comment by fuzeman** [comment]
PR: https://github.com/ukdtom/UAS2Res/pull/5

**Comment by hilljd00** [comment]
Was the merger held back as I cannot find this anywhere within the USA_V2?

**Comment by M0UL** [comment]
the appstore itself needs to be update before it gets added. it wil be in the next release.

**Comment by hilljd00** [comment]
Thank you, by chance do you know when this is meant to be happening?

**Comment by ukdtom** [comment]
He doesn't :-)

But I can tell you, that we just started a closed beta for WebTools

**Comment by hilljd00** [comment]
Great! I know you said a closed beta but if you are looking for more testers please give me a shout :) I'd like to help if possible.

Thanks for your update :)

**Comment by SpoBo** [comment]
How can I be notified as soon as installation is supported?

**Comment by ukdtom** [comment]
Follow this git:

https://github.com/ukdtom/UAS2Res

/T

**Comment by fuzeman** [comment]
The Trakt.tv plugin is now available in WebTools [v2.2](https://github.com/dagalufh/WebTools.bundle/releases/tag/2.2)

**Comment by ukdtom** [comment]
Maybe add another PR against [UASRes](https://github.com/ukdtom/UAS2Res) with options for like different branches ;-)

**Comment by jaminroe** [comment]
@fuzeman does that mean it's working for UAS2 now?

**Comment by ukdtom** [comment]
Only if you upgrade to the latest version of WebTools!
V2.2

**Comment by jaminroe** [comment]
@ukdtom ah okay! I didn't realize that was a plug-in/bundle I had to install. I shall do that, thank you! 👍

**Comment by fuzeman** [comment]
> Maybe add another PR against UASRes with options for like different branches ;-)

The "beta" branch is currently out of date as there is no active beta tests, so thought leaving that option out of UAS would probably be a good idea currently.

-------------------

@ukdtom 
I'm thinking about working on support for releases (https://github.com/dagalufh/WebTools.bundle/issues/110) in UAS - where it installs beta releases if available, but will switch back to the stable branch if a newer release (by major + minor version numbers) is available there.

I would also likely implement platform-specific release assets, as this plugin has grown way too large... *(currently: 56MB zipped, 146MB unzipped)*

**Comment by ukdtom** [comment]
Heh......That's going to take a couple of minutes ;-)
