### ISSUE TITLE
Console logging

### ISSUE THREAD

**Issue by ukdtom** [trakt/Plex-Trakt-Scrobbler#265]
Any chance, that Console logging could be in the prefs?

And default switched off?

Kinda hard to trace stuff to console for other stuff, since Trakt is very "chatty" ;-)

**Comment by fuzeman** [comment]
> Any chance, that Console logging could be in the prefs?

Honestly not sure what you mean by *console* logging, do you mean the usual plugin log files or are you talking about something else?

------------------------

There is "Logging" options in the preferences, changing these to "ERROR" should reduce the number of messages written to the log file.

**Comment by ukdtom** [comment]
Well.....Logging to log files is great, but see a screen dump here from my console on my PMS box (QNAPx86)

https://gist.github.com/ukdtom/30c20496702986b74c0e

**Comment by fuzeman** [comment]
Have you tried changing the "Logging" options in the preferences? from my tests these options change the console log level as well.

**Comment by ukdtom** [comment]
Ohhh....and works, but not my point here.....

Point is, why log to console?

**Comment by fuzeman** [comment]
Ohh.. I've never specifically enabled console logging, it must be caused by our other logger changes.

I'll have a look this weekend :smiley:

**Comment by ukdtom** [comment]
Thanks mate ;-)

**Comment by fuzeman** [comment]
This issue should be fixed on the "develop" branch, turns out it was just an option in the "Info.plist" file.

**Comment by ukdtom** [comment]
And found it, and confirmed ;-)
