### ISSUE TITLE
Error Unable to construct task

### ISSUE THREAD

**Issue by montizzl3** [trakt/Plex-Trakt-Scrobbler#266]
I am running Plex Media Server 0.9.15.1 on server 2008 R2 and trakt plugin version 0.9.10.15-develop.  Just installed this plugin by copying the Trakttv.bundle into the PMS plugins folder.  I used the online configuration tool at http://trakt-for-plex.github.io/configuration/#/configuration/accounts?id=1 to link my trakt account to my plex account.  I get a little green arrow on both the trakt and plex tabs, however my trakt image did not load in when i logged into my trakt account.  Although I have it set to scrobble in the settings it is not picking it up.

I went to the trakt channel in the Plex web app and clicked on sync.  I clicked on Full and it immediately says unable to construct task.  I have attached my log file.  Any help would be appreciated.

[com.plexapp.plugins.trakttv.log.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/98180/com.plexapp.plugins.trakttv.log.zip)

**Comment by fuzeman** [comment]
Looking into this issue now, will let you know when there is a fix ready to test.

**Comment by fuzeman** [comment]
Could you test the fixes in the ```issue/266``` branch of the plugin, download it from here: https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/issue/266.zip

**Comment by montizzl3** [comment]
Thanks for looking into this!  This seems to have worked.  It did a full sync successfully.

There still seems to be some issue with my trakt account since when I login to the web configuration tool it doesn't show the image like it does for the other accounts I have set up there.  Also, if I try to login again in the web configuration tool it says "Account details are unavailable until changes have been saved".  There is a green check mark so this doesn't seem to matter.  There is also a message in the Trakt Channel in the PLEX webapp that says "ConstraintError: UNIQUE constraint failed: trakt.account.username"  I have 2 different plex servers that are set up the same way and they both do the same thing on this trakt account but no others.

Maybe all of that is irrelevant because this fix you so promptly provided has allowed the sync to work again. I hope it will kick off automatically on the triggers I set again.  Thanks for your awesome work on this plugin.  I love both Plex and Trakt so your work on providing this plugin and especially the multi-user support is hugely appreciated.

**Comment by fuzeman** [comment]
> Thanks for looking into this! This seems to have worked. It did a full sync successfully.

That's good, will include those fixes in the next beta release.

> There still seems to be some issue with my trakt account since when I login to the web configuration tool it doesn't show the image like it does for the other accounts I have set up there.

Which image is being displayed? the image in the account list defaults to your plex avatar.

> Also, if I try to login again in the web configuration tool it says "Account details are unavailable until changes have been saved". There is a green check mark so this doesn't seem to matter.

Are you clicking the blue save button after logging in again?

> There is also a message in the Trakt Channel in the PLEX webapp that says "ConstraintError: UNIQUE constraint failed: trakt.account.username" I have 2 different plex servers that are set up the same way and they both do the same thing on this trakt account but no others.

That error usually means you have two accounts connected to the same trakt account.

Linking multiple accounts to one trakt account might be supported in the future, it will require some improvements to syncing to get it working correctly though.

> Maybe all of that is irrelevant because this fix you so promptly provided has allowed the sync to work again. I hope it will kick off automatically on the triggers I set again. Thanks for your awesome work on this plugin. I love both Plex and Trakt so your work on providing this plugin and especially the multi-user support is hugely appreciated.

Thanks, let me know if you have any other questions or issues.

**Comment by montizzl3** [comment]
Which image is being displayed? the image in the account list defaults to your plex avatar.
-- There is no image displayed on the Trakt tab.  My Plex avatar does show up in the account list

Are you clicking the blue save button after logging in again?
-- Yes I clicked the save and on other Trakt accounts it goes away.  On my montizzl3 account it doesn't for some reason.

That error usually means you have two accounts connected to the same trakt account.
-- I do have this same setup on 2 different servers, both on my PLEX account.  So one Trakt account is linked to one PLEX account but on 2 different servers.  The odd thing about this is that I tested the same thing with another PLEX user and another Trakt account on both of my PLEX servers and that one has no issues.

If you want to close this issue I'm ok with that.  All seems to be functioning ok with the fix you posted.  The Trakt account thing doesn't seem to be causing any functionality degradation.  Thanks again for your help and response.
<img width="581" alt="screen shot 2016-01-22 at 10 44 12 pm" src="https://cloud.githubusercontent.com/assets/16807269/12528119/3a6bf89e-c15b-11e5-87e3-0da508a2f37f.png">

**Comment by fuzeman** [comment]
Sounds a bit strange.. but if everything is working there is probably no point spending more time on it :smile:

**Comment by montizzl3** [comment]
My thought exactly, thanks!

**Comment by Kwart1001** [comment]
Hi Montizzl3 and fuzeman,

I had also problems first to save my trakt.tv avatar. I first had to clear the trakt pin in the trakt channel on my plex server and then I used the online configuration tool. This time using the save button worked to let the avatar stick.
