### ISSUE TITLE
plex trakt failed attributeerror socketobject object has no attribute set_tlsext_host_name

### ISSUE THREAD

**Issue by thesatman** [trakt/Plex-Trakt-Scrobbler#267]
Running Trakt 0.9.1.29-master on Plex 0.9.12.19 Win7-x64.

When Trakt tries syncing, It gives this error: 

Last run xx minutes ago, taking 7 seconds, failed (AttributeError: "'_socketobject' object has no attribute 'set_tlsext_host_name'").

Trakt.TV is not updated
[com_plexapp_plugins_trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/102976/com_plexapp_plugins_trakttv.txt)

**Comment by fuzeman** [comment]
This issue should be fixed on the "develop" branch now, download it here: https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip

**Comment by thesatman** [comment]
Thx, seems to be working now.
