### ISSUE TITLE
Wrong show being marked as watched on trakt

### ISSUE THREAD

**Issue by Kreutertee** [trakt/Plex-Trakt-Scrobbler#268]
Plex version: 0.9.15.2
Scrobbler: latest, 0.9.1.29

I had troubles getting the new "Mad Dogs (US)" show from 2015 into Plex correctly, not going with the "old" series from the UK, 2011. My naming is according to the Plex guidelines (I even tried different variations -> "Mad Dogs (2015) - s01e01" , "Mad Dogs (US) (2015) - s01e01", also doing full rescan in Plex and also restarting Plex in between). But Plex wouldn't just recognize it correctly and I had  to manually adjust the association. It's shown correctly in Plex now, however, on Trakt the old show from 2011, UK, is being marked as watched.

**Comment by fuzeman** [comment]
Try deleting the "metadata" cache at:
```
Plug-in Support\Caches\com.plexapp.plugins.trakttv\metadata
```

**Note:** This caching issue was fixed in the beta verison *(which will hopefully be released this week)*.

**Comment by XenitXTD** [comment]
Hi, Sometimes shows pick up incorrectly... I have noticed this several times with my anime picking up as a TV show... 

just go into the show and select fix incorrect match... it should bring up a list to choose from... sometimes this doesnt work either and you have to tweak the search options manually until the correct one comes up... 

if Plex Indexes it as a certain show it will push it as that to Trakt... to you need to ensure that your shows are correctly indexed... and its only that 1% that fails and that's pretty good... as this would be that edge case scenario where it incorrectly classifies your TV Show
