### ISSUE TITLE
Multi User Support Needed

### ISSUE THREAD

**Issue by XenitXTD** [trakt/Plex-Trakt-Scrobbler#269]
Hi, I have several Users setup in the Home... Originally I was signed into the Trakt channel plugin but i have noticed that you cannot separate it from other users or sign them in separately... 

So when they watch something it will push that to your plex account as watched when you havent watched it... so it will scrobble your account etc

Can you please devise a way to disable it for other users on the same server or support multiple users somehow...

I really love this plex plugin as it is extremely useful but this bug or unforseen issue is destroying my trakt history with other users stuff pushing to my timeline

**Comment by fuzeman** [comment]
Multi-user support is currently available in the beta version, you can find a download for the latest beta version on the [releases](https://github.com/trakt/Plex-Trakt-Scrobbler/releases) page.

The current beta version has a new configuration interface so you can setup each plex user with their own trakt account, look here for a basic guide: https://github.com/trakt-for-plex/configuration/issues/1

---------------

Another option is updating your filters to block watching activity from other users, this would just require setting the "Global Filter - Users" option to *your* plex username (which will block activity from other users).

**Comment by XenitXTD** [comment]
Thanks... I finally got to check in here and glad to see the active and responsive development on this
