### ISSUE TITLE
Unable to start package on Synology (ARMv5)

### ISSUE THREAD

**Issue by christiga** [trakt/Plex-Trakt-Scrobbler#272]
Hello,

I installed Plex package on my Synology 212J, it works well.
When I add the plugin in the plugin folder, Plex won't start again until I delete the scrobbler folder.
Log file doesn't give any useful information.
What should I do?

Thank you

**Comment by fuzeman** [comment]
The Synology 212J has an ARMv5 processor, currently we only support ARMv6 and ARMv7. I'll look at supporting ARMv5 in the future, it might be awhile before this is available though.

**Comment by christiga** [comment]
Ok thank you

**Comment by fuzeman** [comment]
Could you try the `feature/libraries/armv5` branch ([download](https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/feature/libraries/armv5.zip)) of the plugin. Please post the latest plugin log file if the plugin still doesn't startup correctly.

**Comment by christiga** [comment]
Plex package has started ok after plugin installation, but I can't see the scrobbler plugin anywhere on my plex homepage. Do I have to do something else?

**Comment by christiga** [comment]
Actually, the channel appeared after rebooting the nas.
Then I had a "no soup for you" message every time I clicked on the tracktv icon.
I had to disconnect and then reconnect on plex to make it work.
I still haven't tested it but I think the plugin will work.
Thank you

**Comment by fuzeman** [comment]
Released in [v1.0.1.0](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.0.1.0)

**Comment by christiga** [comment]
Hi again,
It has stopped working for a few feeks now (nothing shows up in the chanels), maybe it has something to do with new version of DSM?
Thank you

**Comment by fuzeman** [comment]
Could you send me the latest plugin log file?

-------------------

The latest plugin log file should be located at:
```
Plex/Library/Application Support/Plex Media Server/Logs/PMS Plugin Logs/com.plexapp.plugins.trakttv.log
```

*See Q13 at https://forums.plex.tv/discussion/191000/faqs-read-this-first for more details.*

**Comment by christiga** [comment]
Nothing interesting in log, seems that it hasn't been updated from april 12.
[com.plexapp.plugins.trakttv.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/233339/com.plexapp.plugins.trakttv.zip)

There is something interesting in PMS server log, maybe it will help :

10:18:27 [0x45888400] DEBUG - Scanning for plug-ins in /volume1/@appstore/Plex Media Server/Resources/Plug-ins-81a3bf0
Apr 24, 2016 10:18:28 [0x45888400] DEBUG - Scanning for plug-ins in /volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins
Apr 24, 2016 10:18:28 [0x45888400] ERROR - Couldn't check for the existence of file /volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Info.plist: boost::filesystem::status: Permission denied: "/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle/Contents/Info.plist"
Apr 24, 2016 10:18:28 [0x45888400] WARN - Couldn't determine bundle identifier for plug-in at: /volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle
Apr 24, 2016 10:18:28 [0x45888400] DEBUG - Starting plug-in /volume1/@appstore/Plex Media Server/Resources/Plug-ins-81a3bf0/System.bundle.
Apr 24, 2016 10:18:28 [0x45888400] DEBUG - [com.plexapp.system] Setting plug-in to always running (daemon mode).
Apr 24,

I checked permission, plex user has all permission on the plugin folders and files.

**Comment by christiga** [comment]
Ok, resolved.
I deleted permissions and add them again for every user AND groups.
That seemed to do the trick. Not the first time I have permissions issues since update.
Sorry for having reopening issue.

**Comment by fuzeman** [comment]
No problem :smile:, glad you figured out what the issue was.
