### ISSUE TITLE
ServerError: Server Error - "server error"

### ISSUE THREAD

**Issue by mbeckford88** [trakt/Plex-Trakt-Scrobbler#273]
Hi there,

I'm getting this error any time I try do a trakt pull, although I think there is a mention of this that it should be getting ignored in the changelog?

Running v1.0.0.3 (stable), have done a clean install too. Shall send the log once I get access to the machine.

**Comment by fuzeman** [comment]
This error just means there was a problem with the Trakt.tv API.

The change-log entry you are referring to was related to the error reporter, these errors will still result in syncs being cancelled as we can't continue without certain data being returned from trakt.

**Comment by mbeckford88** [comment]
Fresh log file attached after trying a full pull. No antivirus/firewall either, tried both local address and plex.tv web interface, not sure if the trakt API is particularly more unstable lately?

[com.plexapp.plugins.trakttv.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/131531/com.plexapp.plugins.trakttv.zip)

**Comment by fuzeman** [comment]
The Trakt API does tend to fall over randomly, looks like they are working on it: https://twitter.com/trakt/status/699366646842961920

**Comment by mbeckford88** [comment]
Will try again once they've been resolved, just to make sure it isn't anything to do with the plugin.

**Comment by mbeckford88** [comment]
This looks to be pulling through now, must have been the trakt API having difficulty.
