### ISSUE TITLE
Plex Friends

### ISSUE THREAD

**Issue by matrix1983uk** [trakt/Plex-Trakt-Scrobbler#276]
Hi please can you help me. I have a plex media server which i share with many friends. but only i have a trakt account so when they watch something it shows up on trakt as if i'm watching it. Is there any way that i can track what their watching through my trakt account. So when ever one of my friends is watching something on my plex server it will tell me on my trakt account what they are watching. so that i can keep track of what everyone is watching on my server. i know you can do this through the plex media server it self but thought their might be a way to do this on my trakt account as it has much more detail. Thanks

**Comment by fuzeman** [comment]
The only way to do this is by setting up each user with their own Trakt.tv account and linking it in the plugin (available on v1.0.0 and later).

All you can see on Trakt.tv is a history of watched media from friends though, no real-time "currently watching" view is available..

**Comment by mbxIO** [comment]
@fuzeman Is there a way to stop Trakt Scrobbler from picking up on my friends? I was to track what I PERSONALLY watch, not my Plex Friend included.

**Comment by fuzeman** [comment]
@mbxIO https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/FAQ---Scrobbling#2-why-are-videos-watched-by-other-users-being-scrobbled-to-my-profile
