### ISSUE TITLE
Norton Virus Warning

### ISSUE THREAD

**Issue by panesarg** [trakt/Plex-Trakt-Scrobbler#279]
http://i.imgur.com/SKW7UqA.png including a bunch of *.pyd files

**Comment by fuzeman** [comment]
VirusTotal confirms ```apsw.pyd``` is clean: https://www.virustotal.com/en/file/4032e383d7e8654e36788d161fe47ac98f7ce85233de53dca371965b121a5953/analysis/1456092524/

Not sure why Norton would flag it.. does it provide any other details (category, etc..) on the file?

**Comment by panesarg** [comment]
Seems like that was a one-off thing. I just re-scanned the folder in my downloads and it's not returning with any viruses. Looks good now! Sorry for the trouble.

**Comment by fuzeman** [comment]
No worries :smile:
