### ISSUE TITLE
Trakt tv bundle folder disappears

### ISSUE THREAD

**Issue by movieaddct** [trakt/Plex-Trakt-Scrobbler#280]
just within the last few days my plex hasnt been scrobbling, Then i found out what has been happening.  The trakt tv bundle folder keeps disappearing.  ill shut off plex and put in trakt tv bundle in plugin folder but once i turn it back on it disappears.

**Comment by fuzeman** [comment]
Don't think the plugin would be triggering this, did you originally install the plugin with "Unsupported App store"? it might be trying to update the plugin but is failing for some reason..

**Comment by gdolla** [comment]
Yes I think idid go thru the unsupported store.  No wonder!  Omg thank you

**Comment by gdolla** [comment]
No I'm on a mac  I removed that  external hard drive

**Comment by movieaddct** [comment]
i went here :
https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Installation%20-%20Windows
and i follow the instructions and when it starts it disappears.  This time
i turned off updates and it still does it?  weird
