### ISSUE TITLE
Where are the Trakt credentials stored (Linux)?

### ISSUE THREAD

**Issue by krikmo** [trakt/Plex-Trakt-Scrobbler#281]
I have a script that updates the repository, deletes the old `Trakttv.bundle` and copies the new one to `/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle`.

I want to ignore the login data so that I don't have to re-login, where can I find them?

**Comment by gdolla** [comment]
I can't find them..  I need help also. thank you!!

**Comment by fuzeman** [comment]
Your settings are stored under the ```Plug-in Support``` directory at:
 - ```Plug-in Support\Preferences\com.plexapp.plugins.trakttv.xml```
 - ```Plug-in Support\Databases\com.plexapp.plugins.trakttv.db```

**Comment by krikmo** [comment]
So there is no need to ignore those files after all. Thank you.
