### ISSUE TITLE
plugin not showing in Channels

### ISSUE THREAD

**Issue by reimannje** [trakt/Plex-Trakt-Scrobbler#282]
Hello!

I was trying to install version 1.0.0.5 of the Plugin earlier today. I cannot get it running. An older version (i can`t remember which exact version it was but it was a 0.9 release) was running perfect. 
But now, neither the old nor the new version is working. 
I use Plex Version 0.9.15.6 on a Synology DS215j (ARMv7).

I attached a log file.

I hope you folks can help. 
Thanks a lot!

Kind regards! 

Jens
[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/149331/com.plexapp.plugins.trakttv.log.txt)

**Comment by gdolla** [comment]
Good morning!  I'm updating my ram  my comp wouldn't get online. Would it

**Comment by fuzeman** [comment]
This issue is being handled in https://github.com/trakt/Plex-Trakt-Scrobbler/issues/277, check the latest update there for a possible fix to test :smiley:
