### ISSUE TITLE
Raspbian Jessie  Plex not detecting.

### ISSUE THREAD

**Issue by 3xisted** [trakt/Plex-Trakt-Scrobbler#285]
So the commands you offer to start and stop plex were not working so I used
 `sudo service plexmediaserver stop` and `sudo service plexmediaserver start`. But now the Plex won't even detect trakt.tv plugin.
Any work arounds?

**Comment by fuzeman** [comment]
Could you post the latest plugin log file? see https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files for details on the location.
