### ISSUE TITLE
Movie playback progress sync does not work

### ISSUE THREAD

**Issue by Deihmos** [trakt/Plex-Trakt-Scrobbler#287]
Episode playback progress works fine but it has never worked with Movies.

**Comment by fuzeman** [comment]
Could you test the fix in this version of the plugin: https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/issue/287.zip

**Note:** you will need to run a "Pull" sync to import your past playback progress correctly, any new playback progress changes will be imported with a "Full" or "Quick Pull" sync.

**Comment by Deihmos** [comment]
It works. Thanks.

**Comment by joreilly02** [comment]
I have the same problem - the issue 287 plugin didn't fix my issue.

**Comment by fuzeman** [comment]
Fix released in [v1.0.1.2](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.0.1.2)

--------------

@joreilly02 You will need to run a "Pull" sync to import old playback progress.

Please open a new issue with the plugin log files (after a sync) if you still are encountering problems with playback sync.
