### ISSUE TITLE
Nothing will scrobble using plex on mac.  

### ISSUE THREAD

**Issue by joreilly02** [trakt/Plex-Trakt-Scrobbler#288]
I can't get the Trakt.tv scrobbler to send any data to the site.  Whether I manually or automatically sync, it just doesn't work.   I've fiddled around with almost every setting - had a couple people troubleshoot it with me on reddit, but nothing worked.    Anyone have an idea of what may be causing this?

**Comment by sheykh-sleky** [comment]
Throw up your log mate!

**Comment by joreilly02** [comment]
http://pastebin.com/uc0H4Vns

I think that's the right log.   If there's any more info you need, or if I didn't do it right, let me know! :)

**Comment by fuzeman** [comment]
The plugin appears to be detecting your watching activity, but is failing to send any actions to Trakt.tv.

Few questions:
 - Which Plex client are you using? (PHT, DLNA, Plex/Web, etc..)
 - Have you set any of the filter options via Plex/Web?
 - Have you set any rules via the configuration site (http://trakt-for-plex.github.io/configuration)?

**Comment by joreilly02** [comment]
Hey fuzeman, 

1) I'm using Plex/Web for this.  We also use Plex on our Apple TV, but don't think that changes anything. 
2 + 3) I've tried just about every combination of filter options and rules.  What are the ones you recommend?

**Comment by gdolla** [comment]
I'm using home media theater right now..  What did I do wrong.  Why doesn't
it act right?

**Comment by gdolla** [comment]
Thanx to all wonderful wonderful ppl helping!!

**Comment by fuzeman** [comment]
> 2 + 3) I've tried just about every combination of filter options and rules. What are the ones you recommend? 

I would first set your filters/rules back to defaults to determine where the issue is first *(see below for default values)*. When scrobbling is working we can look at setting up your filters/rules again to ignore activity from other users on your server.

-------------------

#### Filters
![](https://i.imgur.com/xt22thW.png)

#### Rules
![](https://i.imgur.com/SHX3F8V.png)

![](https://i.imgur.com/GGpTplA.png)

**Comment by joreilly02** [comment]
Now, http://trakt-for-plex.github.io/configuration stopped working.   If I try to connect, it just says 'unknown error'.   Any idea of how to fix that?     

Thank you for all of your help!

**Comment by joreilly02** [comment]
I have reinstalled everything, used those settings, and it's still not working.  Here's my new log file: http://pastebin.com/kv93hKTW

**Comment by fuzeman** [comment]
It appears you have a lot of unmatched movies + shows:
```
2016-03-09 01:30:32,742 - plugin.sync.modes.fast_pull.movies :  INFO - Found 952 unsupported movie(s)
    [     2] GUID agent 'none' is not supported
```

```
2016-03-09 01:30:38,835 - plugin.sync.modes.fast_pull.shows :  INFO - Found 358 unsupported show(s)
    [  1592] GUID agent 'none' is not supported
```

-----------------------------

How are your libraries configured? they need to be using a supported metadata agent, for example:
 - **Movies:** Freebase, The Movie Database
 - **TV Shows**: TheTVDB, The Movie Database

*(see [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/FAQ---General#3-which-metadata-agents-are-supported) for the full list of supported metadata agents)*

**Comment by joreilly02** [comment]
So I figured out what is wrong, but I have no idea on how to fix it.  It appears that you were correct in that it's a problem with the metadata agent.   I have converted and properly tagged movies in my folder, and plex seems to be taking the information directly from the file instead of matching it with the online sources, even though I have it properly set to not take the local metadata.   Is there a way to force it to take the online info?

**Comment by fuzeman** [comment]
>  Is there a way to force it to take the online info? 

You can disable (or change the order of) the "Local Media Assets" agent under ```Settings -> Agents``` (in Plex/Web).

**Note:** You might need to run a "Force Refresh" to bring your library up to date after adjusting your agents.

**Comment by joreilly02** [comment]
The force refresh didn't work, but moving the media folder, updating the library, then moving it back did.  It's now working great.  Thank you for all your help! :)
