### ISSUE TITLE
Write documentation as a webpage.

### ISSUE THREAD

**Issue by tester22** [trakt/Plex-Trakt-Scrobbler#29]

**Comment by jmagnusson** [comment]
It would be nice with a page describing all settings. For example I don't know what "Sync - Instant Actions" and "Scrobble" actually do...

**Comment by jmagnusson** [comment]
@fuzeman Why was this closed?

**Comment by fuzeman** [comment]
Documentation is being added to the [wiki](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki), might port this to [RTD](https://readthedocs.org/) in the future though.

**Comment by jmagnusson** [comment]
Sweet! A link to this documentation in the app would be awesome.
