### ISSUE TITLE
Can't see channel on Plex running on DS216play

### ISSUE THREAD

**Issue by phuture2k** [trakt/Plex-Trakt-Scrobbler#292]
I have a Synology DS216play NAS running DSM 6.0rc (had this issue with 5.2 too). I did a clean manual install, checked if the folder was ok, restarted Plex (multiple times) and still not working.

My gues is that it is related with apsw but I have no idea what that is

Log here: http://pastebin.com/wwrTRigH

**Comment by fuzeman** [comment]
This log file appears to be from an older version of the plugin, are you using [v1.0.1.1](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.0.1.1)?

**Comment by phuture2k** [comment]
Fixed. Had no idea you updated that fast. Good job!
