### ISSUE TITLE
Plugin not loading on Synology DSM 6.0-7321 and Plex 0.9.16.3

### ISSUE THREAD

**Issue by reimannje** [trakt/Plex-Trakt-Scrobbler#295]
Hello!

Sorry, its me again. I recently updated my Synology to DSM Version 6.0-7321 and Plex to the latest Version 0.9.16.3.
After that the plugin is no longer loading. 

I attached the log file.

I hope someone can help. 

Thanks

J
[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/190388/com.plexapp.plugins.trakttv.log.txt)

**Comment by Wolf666** [comment]
Running plex 0.9.16.3 on DSM 6 final and Trakt works.

**Comment by fuzeman** [comment]
@reimannje Looks like the plugin isn't detecting your system as a Synology device anymore.

Could you post the output of this command:
```
cat /proc/cpuinfo
```

**Comment by reimannje** [comment]
@fuzeman Here is the output. Thanks for looking into this.

Processor	: ARMv7 Processor rev 1 (v7l)
processor	: 0
BogoMIPS	: 1594.16

processor	: 1
BogoMIPS	: 1594.16

Features	: swp half thumb fastmult vfp edsp neon vfpv3 tls
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x4
CPU part	: 0xc09
CPU revision	: 1

Hardware	: Marvell Armada-375 Board
Revision	: 0000
Serial		: 0000000000000000

**Comment by fuzeman** [comment]
@reimannje Could you test the changes in this version of the plugin: https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/issue/295.zip

**Comment by reimannje** [comment]
@fuzeman Sorry, not working with this either.

[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/193050/com.plexapp.plugins.trakttv.log.txt)

**Comment by fuzeman** [comment]
@reimannje Try the latest changes in https://github.com/fuzeman/Plex-Trakt-Scrobbler/archive/issue/295.zip again.

**Comment by reimannje** [comment]
@fuzeman It works again!  

Thank you soooo much for your help.

**Comment by fuzeman** [comment]
Great :smile:, will have that fix included in the next plugin release.

**Comment by fuzeman** [comment]
Changes released in [v1.0.2.0](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.0.2.0)
