### ISSUE TITLE
Synced scrobble not working

### ISSUE THREAD

**Issue by duramato** [trakt/Plex-Trakt-Scrobbler#296]
I remeber it used to scrobble as when i was watching my media, i would go to my trakt profile and see  Watching xyz and a progress bar.
Did something got broke between upgrades? Or an issue?
Any additional info needed please ask, i am running the latest master version

**Comment by fuzeman** [comment]
Not aware of any issues currently, could you tell me what Plex client(s) you are using and attach the latest plugin [log file](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files) after watching something in Plex.

**Comment by duramato** [comment]
The client i use the most is OpenPHT and i see the progress on the plex server status page, if its important info.
i'll get the logs as soon asap

**Comment by duramato** [comment]
full log https://gist.github.com/duramato/c0c0f6209060af0470c87cd9eb3c4bc2

**Comment by fuzeman** [comment]
These messages appear to be related to your issue:
```
No machine identifier available, unable to create session
```

```
[logging.playing] Exception raised in: Logging.on_playing - 'utf8' codec can't decode byte 0xe7 in position 3: invalid continuation byte
```

-----------------------------

What have you selected for the "Activity mode" option? (found at ```Plex/Web -> Channels -> trakt -> Settings```)

Are you watching (or have previously watched) movies/shows that have titles outside of the ASCII character table (characters with diacritic marks)?

**Comment by duramato** [comment]
I have "Logging" enabled

Regarding the show titles with non ASCII char dont think i have any show like that. The file themselvs theres the possibility of having ç and accented char.

**Comment by fuzeman** [comment]
> I have "Logging" enabled

Could you try switching that back to "Automatic" and restart Plex Media Server (so the plugin is restarted)? then start playing something in Plex and post the latest plugin log file again.

> Regarding the show titles with non ASCII char dont think i have any show like that. The file themselvs theres the possibility of having ç and accented char.

The "ç" character (```0xE7```) is mentioned in that error message, so there must be some issue with encoding going on.. I'll need to do some more testing to try identify this issue..

**Comment by duramato** [comment]
New log: https://gist.github.com/duramato/5382cb895314908bf3df4f6a2ffd4a94

**Comment by jaminroe** [comment]
I'm also having the same issue. Not syncing my watched episodes. I never changed anything for months.

**Comment by jaminroe** [comment]
Never mind, authentication error.

**Comment by jaminroe** [comment]
Seems that it's not accepting my credentials. I double rechecked and using the same as I just did on the website.

**Comment by fuzeman** [comment]
@duramato Looks like it's working now, from your log file:
```
2016-04-03 14:22:34,861 - Sending action u'scrobble/start' (account: <Account name: u'supergonkas'>, interface: u'scrobble', method: u'start')
2016-04-03 14:22:34,862 - request: {u'progress': 75.33, u'episode': {u'season': 1, u'number': 3, u'title': u'98 Seconds'}, u'show': {u'title': u'Colony', u'ids': {u'tvdb': 284210}, u'year': 2016}}
```

Are items being correctly scrobbled to your Trakt.tv profile now?

--------------------------------

@jaminroe Are you using the latest version of the plugin ([v1.0.1.2](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.0.1.2))? UASv2 doesn't support this plugin yet so you will need to manually update it, see [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Installation%20-%20Windows) for more details.

The plugin settings should look like this with the latest version *(the username + password fields were removed)*:
![](https://i.imgur.com/IJbGb2R.png)

**Comment by duramato** [comment]
I did not saw them there. I will do some more testing to e sure if it really is, or not.

**Comment by jaminroe** [comment]
@Fuzeman ah!! I did just download the latest version yesterday but I'll look again thank you!

**Comment by jaminroe** [comment]
I had extracted the root folder instead of the Trakttv.bundle one LOL! Silly me. Working now. Looking forward to UAS 2 support 😁

**Comment by duramato** [comment]
ok it is working now :)
