### ISSUE TITLE
loading plugin fails

### ISSUE THREAD

**Issue by matthewdias** [trakt/Plex-Trakt-Scrobbler#297]
just installed the plugin and its not loading.

Plex Media Server.log
```
Mar 31, 2016 04:29:50 [0x10cd94000] ERROR - Timeout or error reading status line from plug-in pipe [com.plexapp.plugins.trakttv], we're killing it.
Mar 31, 2016 04:29:50 [0x10cd94000] DEBUG - Stopping [com.plexapp.plugins.trakttv].
Mar 31, 2016 04:29:50 [0x10cd94000] DEBUG - [com.plexapp.plugins.trakttv] Killing.
Mar 31, 2016 04:29:50 [0x10cd94000] ERROR - Error received reading configuration for com.plexapp.plugins.trakttv
Mar 31, 2016 04:29:50 [0x10cd94000] DEBUG - Stopping [com.plexapp.plugins.trakttv].
```

**Comment by fuzeman** [comment]
Could you upload the latest plugin [log file](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files)? Can't really see what's happening with just the Plex Media Server log file..

**Comment by matthewdias** [comment]
@fuzeman No logs have been generated since I updated the plugin. The earliest logs are from 3/20, which was before I downloaded the updated .bundle and replaced the old one.

**Comment by fuzeman** [comment]
Hmm, that makes identifying this issue hard...

-------------------

Only things that come to mind are:
 - Ensure the ```Plug-ins/Trakttv.bundle/Contents``` directory exists
 - Ensure the ```Plug-ins/Trakttv.bundle``` directory is owned by the "plex" user *(```chown -R plex:plex Plug-ins/Trakttv.bundle```)*

**Comment by matthewdias** [comment]
@fuzeman When I do that I get `plex: illegal group name`. (I'm on os x btw). Doing `ps aux | grep Plex` it just shows my user account.

**Comment by fuzeman** [comment]
What version of Plex Media Server are you using? I'll need to reproduce this issue in a virtual machine to try debug the issue.

**Comment by matthewdias** [comment]
0.9.16.3

**Comment by fuzeman** [comment]
Tested the plugin on OS X 10.9.5 and couldn't see any issues.

-------------------

The only way we can really find out why the plugin isn't starting up is by running the following command in "Terminal" *(replace ```<USERNAME>``` with your account username)*:
```
PYTHONHOME="/Applications/Plex Media Server.app/Contents/Resources/Python" PYTHONPATH="/Applications/Plex Media Server.app/Contents/Resources/Python/lib/python2.7" PLEXBUNDLEDEXTS=1 "/Applications/Plex Media Server.app/Contents/Resources/Plex Script Host" "/Applications/Plex Media Server.app/Contents/Resources/Plug-ins-cece46d/Framework.bundle/Contents/Resources/Versions/2/Python/bootstrap.py" --server-version 0.9.16.3.1840-cece46d "/Users/<USERNAME>/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle"
```

This command will start the plugin up in your terminal and display any error that is causing the plugin to crash.

**Note:** This command assumes your "Plex Media Server" application is installed at: ```/Applications/Plex Media Server.app```

**Comment by matthewdias** [comment]
result:
`Error starting framework core for /Users/Matthew/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle.`

**Comment by fuzeman** [comment]
I think this is an issue with Plex Media Server itself, there has been some discussions on the forum about this issue here:
 - https://forums.plex.tv/discussion/127904/made-the-mistake-of-updating-pms
