### ISSUE TITLE
trakt.tv plug-in not visible in PLEX channels

### ISSUE THREAD

**Issue by Oli1990** [trakt/Plex-Trakt-Scrobbler#298]
Hi,

i have installed the newest trakt.tv plug-in in my plex.
Now i can't find the plug-in in my plex channels. The directories are correct and the plex service is running normal. I hope you can help me. 

Thak you

[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/199433/com.plexapp.plugins.trakttv.log.txt)
[Plex Media Server.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/199440/Plex.Media.Server.log.txt)

**Comment by fuzeman** [comment]
Can't see any obvious issues in the log files...

--------------

You could try manually opening it by clicking on "Channels" in Plex/Web and replacing ```/channels``` at the end of the URL with ```/channel/%2Fvideo%2Ftrakt```.

For example, the URL should look like:
```
http://app.plex.tv/web/app#!/server/[Your Server ID]/channel/%2Fvideo%2Ftrakt
```

**Comment by Oli1990** [comment]
Hi,

thank you for the answer.
I've tested the new url. My Plex says this site is not existing. 
So i think this solution is not working for me.
