### ISSUE TITLE
trakt.tv liked list not completely importing to plex

### ISSUE THREAD

**Issue by cgacord** [trakt/Plex-Trakt-Scrobbler#299]
As mentioned [here](https://github.com/trakt/Plex-Trakt-Scrobbler/issues/238#issuecomment-203644291), I am having an issue with my trakt.tv list syncing as playlists.  I'm not sure if it is a size limitation but when I try to import the [MARVEL Cinematic Universe list](https://www.trakt.tv/users/donxy/lists/marvel-cinematic-universe), the last items do not show up in my plex playlist.  It also happens on the [Arrowverse list](https://www.trakt.tv/users/donxy/lists/arrowverse), which is also lengthy.

The episodes are all marked as collected in trakt and I have verified they are in my plex library.

Plug-in version: 1.0.1.2-master

[Logs after running a Full Sync](https://github.com/trakt/Plex-Trakt-Scrobbler/files/200948/com.plexapp.plugins.trakttv.log.zip)

Screen shot of the end of the Plex Playlist
<img width="1592" alt="plex playlist" src="https://cloud.githubusercontent.com/assets/15983047/14228216/466958f8-f90f-11e5-9bcc-b4f2fd83a804.png">

Screen shot of the end of the trakt.tv list
<img width="1250" alt="trakttv list" src="https://cloud.githubusercontent.com/assets/15983047/14228217/469e1e6c-f90f-11e5-81a3-3fd76c6c4234.png">

**Comment by fuzeman** [comment]
I think the plugin is only fetching the first "page" of items currently, so large playlists are being trimmed. This issue likely causes some playlists to be ignored as well (if you have a lot of liked/personal playlists).

Will try have a look at this issue later this week.

**Comment by fuzeman** [comment]
[v1.0.2.0](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.0.2.0) fixes an issue where only 10 liked lists could be pulled/imported into Plex.

I haven't been able to find any issues with long lists not syncing correctly though, could you check if the error still occurs with the latest release? make sure you test using a "Pull" sync, as a "Full" or "Quick Pull" sync might not bring everything up to date correctly.

**Comment by cgacord** [comment]
Since installing the newest version my playlists have been keeping up to date... thanks for all your work :)
