### ISSUE TITLE
Make Plex-Trakt-Scrobbler compatible with Unsupported AppStore

### ISSUE THREAD

**Issue by dwellexity** [trakt/Plex-Trakt-Scrobbler#301]
Unsupported AppStore has an option to install channels with github link. But putting Plex-Trakt-Scrobbler's .bundle link in UAS gives error while some other channels install fine. Can Plex-Trakt-Scrobbler .bundle be made compatible with UAS?

**Comment by fuzeman** [comment]
UASv2 will support this plugin in the next release of WebTools, see https://github.com/trakt/Plex-Trakt-Scrobbler/issues/264 and https://github.com/ukdtom/UAS2Res/pull/5 for more details.
