### ISSUE TITLE
Facebook doesn't track

### ISSUE THREAD

**Issue by alaris1983** [trakt/Plex-Trakt-Scrobbler#302]
When I'm watching an episode it appears on Activity but not on TV Programs tab... but the movies appear ok... It's my problem or it's the scrobble? Thanks!
![captura de pantalla 2016-04-07 a las 17 11 41](https://cloud.githubusercontent.com/assets/16371257/14356329/b32bc0a6-fce4-11e5-8b9b-8168a5127bca.png)
![captura de pantalla 2016-04-07 a las 17 11 58](https://cloud.githubusercontent.com/assets/16371257/14356331/baed750a-fce4-11e5-8cab-2d738fc5f65b.png)
![captura de pantalla 2016-04-07 a las 17 19 37](https://cloud.githubusercontent.com/assets/16371257/14356390/fdb96628-fce4-11e5-8b11-2e37a8dd41fe.png)

**Comment by rectifyer** [comment]
This is actually something facebook controls. Since it's showing up in the activity feed, that indicates its working from Trakt. We don't have control over the TV tab that I know of, facebook should auto populate that, maybe it takes a certain time?

**Comment by alaris1983** [comment]
@rectifyer maybe! I have no idea 🤔 just asking if it was my problem hehe
but I've been using this months and nothing appears

**Comment by rectifyer** [comment]
Hmm, yeah I'm not sure. We have an option to force a post to your timeline, but that is different then showing up in the tabs. I'll make a note to look into this, but I don't think we can force it to show on the tabs at all.

**Comment by alaris1983** [comment]
@rectifyer ok thanks! :) actually It was just to know, It's not very important!

**Comment by alaris1983** [comment]
if it's worth... Facebook ask me to import movies from trakt app
![captura de pantalla 2016-04-07 a las 22 30 44](https://cloud.githubusercontent.com/assets/16371257/14365945/a25bcf06-fd10-11e5-98d1-e4ca3d6e9067.png)
nothing on TV programs
![captura de pantalla 2016-04-07 a las 22 33 23](https://cloud.githubusercontent.com/assets/16371257/14365970/cf13155e-fd10-11e5-99b2-570d4633a726.png)
