### ISSUE TITLE
This channel is not responding.

### ISSUE THREAD

**Issue by Frank4383** [trakt/Plex-Trakt-Scrobbler#306]
Hello  i have installed the last trakt version on my plex 0.9.16.4 (openmediavault). I can not see the trakt channel on plex.

Wenn i open http://192.168.178.71:32400/web/index.html#!/server/c02effb77ed4dd2b9a77fe184ec123d462cff69e/channels/%2Fvideo%2Ftrakt

i see: This channel is not responding.

Can you help me? Sorry for my english.

Thanks
Frank

**Comment by fuzeman** [comment]
Could you provide the full plugin [log file](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files)?

------------

There was recently some talk about OMV in issue #278, so this solution https://github.com/trakt/Plex-Trakt-Scrobbler/issues/278#issuecomment-197817330 might help if you have a similar issue.

**Comment by Frank4383** [comment]
Hello fuzeman,

the Log:
[com.plexapp.plugins.trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/224458/com.plexapp.plugins.trakttv.txt)

I tast the solution #278 in the next days.

**Comment by fuzeman** [comment]
Definitely looks like a duplicate of #278:
```
Fehler beim Mappen des Shared Objects: Die Operation ist nicht erlaubt
```

**Comment by Frank4383** [comment]
Thank you, it works
