### ISSUE TITLE
Pull not updating Filtered user

### ISSUE THREAD

**Issue by Adthrawn** [trakt/Plex-Trakt-Scrobbler#307]
I have the Scrobbler set up to sync things for my Plex user "Mike", however when doing the initial pull for my reinstalled Plex Server it updated everything under the Admin account, not the sub user. 

[trakttvlog.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/222376/trakttvlog.txt)

**Comment by fuzeman** [comment]
Did you configure your other account with the [configuration site](http://trakt-for-plex.github.io/configuration)? filters (via the settings in Plex/Web) only apply to your real-time watching activity, not syncs. See https://github.com/trakt-for-plex/configuration/issues/1 for a basic account configuration guide.

If you've already linked your Trakt.tv account to the Plex administrator user, you might need to reset the plugin settings by deleting the ```com.plexapp.plugins.trakttv.db``` files in ```Plug-in Support\Databases``` and restarting Plex Media Server.

**Comment by Adthrawn** [comment]
Ok, went into the Config site, changed the Plex side to the Plex Home user Mike, saved it. Deleted the DB in the Plug-In Support folder, restarted Plex. Still not updating things under the right user. Are there some specific logs you want besides the everything dumb  from before?

**Comment by fuzeman** [comment]
Try this:

1. Delete the plugin database (mentioned above)
2. Restart Plex Media Server
3. Create a **new** account via the configuration site and link your Plex User and Trakt.tv account
4. In Plex/Web you should see both accounts visible under "Sync", select your new account and try another sync

**Comment by Adthrawn** [comment]
That did it. Thanks much for the help.

**Comment by RykerIX** [comment]
Glad I found this. I was having the same issue. Great info!
