### ISSUE TITLE
Won't start on oDroid XU-* 

### ISSUE THREAD

**Issue by justin0a0** [trakt/Plex-Trakt-Scrobbler#309]
I'm running server version 0.9.15.2 through a plugin in openmediavault on a odroid xu-4
Attached is the plugin log.
[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/232195/com.plexapp.plugins.trakttv.log.txt)
forgot to add the cpuinfo
[cpuinfo.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/232205/cpuinfo.txt)

**Comment by fuzeman** [comment]
Make sure you are using the latest version of the plugin and try these solutions:
 - https://github.com/trakt/Plex-Trakt-Scrobbler/issues/278#issuecomment-197817330
 - https://github.com/trakt/Plex-Trakt-Scrobbler/issues/293#issuecomment-206683427 *(possibly not required)*

**Comment by justin0a0** [comment]
Using method one from https://github.com/trakt/Plex-Trakt-Scrobbler/issues/278#issuecomment-197817330 helped solve the problem.

**Comment by fuzeman** [comment]
Great :smile:, planning on adding this kind of information to the wiki for easier access, haven't had time to do that yet..
