### ISSUE TITLE
Trakt disappeared from my server

### ISSUE THREAD

**Issue by chrisperra** [trakt/Plex-Trakt-Scrobbler#313]
I noticed today after rebooting my media server, that the trakt app has not been working for some time and is now missing from the web interface. It seems to still be installed, but cannot, even after following the troubleshooting instructions, get it to work and come back again.

Log files : @[https://www.dropbox.com/sh/tua3x4g21wekh6v/AAD_BZ_a68tnsjUz2bibsIvxa?dl=0](url)

Hopefully someone can see the issue...

Best!
Chris

**Comment by fuzeman** [comment]
See my response here: https://github.com/trakt-for-plex/configuration/issues/13#issuecomment-217082538

Let me know if you have any issues with the workaround described.
