### ISSUE TITLE
Scrobbler not working

### ISSUE THREAD

**Issue by Kabloomasd** [trakt/Plex-Trakt-Scrobbler#317]
I have tried to reinstall it. 

[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/271256/com.plexapp.plugins.trakttv.log.txt)

**Comment by fuzeman** [comment]
Looks like this is causing your problems:
```
2016-05-18 21:24:29,497 - WebSocket connection has closed, reconnecting...
2016-05-18 21:24:32,223 - WebSocket connection unavailable, activity monitoring not available
```

Not really sure what would cause this though... Could you post your `Plex Media Server.log` file? maybe that will have some clues.

**Comment by Kabloomasd** [comment]
[Plex Media Server.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/275995/Plex.Media.Server.log.txt)

**Comment by fuzeman** [comment]
Forgot to mention, could you post the latest `Plex Media Server.log` file after restarting Plex Media Server and waiting a minute for it to start up completely. As the error is happening on plugin startup, I need to see why the server isn't accepting the request.

**Comment by Kabloomasd** [comment]
[Plex Media Server.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/284269/Plex.Media.Server.log.txt)

**Comment by Kabloomasd** [comment]
![untitled](https://cloud.githubusercontent.com/assets/16331310/15590450/327325fa-2398-11e6-8979-ddeae7e091eb.png)
Everytime i try to change it to the plex username it changes back after a restart of the server. Is that supposed to happen?

**Comment by fuzeman** [comment]
```
Couldn't determine bundle identifier for plug-in at: E:\PMS APP DATA\Plex Media Server\Plug-ins\Plex-Trakt-Scrobbler.bundle
```

```
Starting plug-in E:\PMS APP DATA\Plex Media Server\Plug-ins\Trakttv.bundle.
```

Looks like there is an issue with the plugin installation, how did you install it (Manual or WebTools/UAS)?

-------------------------

I would delete both ```Plug-ins\Plex-Trakt-Scrobbler.bundle``` and ```Plug-ins\Trakttv.bundle```, then re-install the plugin manually by following these steps:

1. Shutdown Plex Media Server
2. Download the latest version: [v1.0.2.1.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/v1.0.2.1.zip)
3. Open/Extract the zip file, move the ```Trakttv.bundle``` directory into your ```Plug-ins``` directory
4. Start Plex Media Server

**Comment by Kabloomasd** [comment]
Ive done it both manually and with UAS. It wont start working.

**Comment by Kabloomasd** [comment]
![bundle](https://cloud.githubusercontent.com/assets/16331310/15743897/e1d1302a-28c8-11e6-8ad9-714f52b24ec6.png)

> 
E:\PMS APP DATA\Plex Media Server\Plug-ins\Plex-Trakt-Scrobbler.bundle 
> 

I do not even have such a folder.

**Comment by Kabloomasd** [comment]
Is there any way that i can delete the enire app with all the settings saved? Since the trakt login is saved everytime i reinstall the app.

I've deleted every file named "Trakt" but the settings are still saved.

**Comment by Kabloomasd** [comment]
It's working again. I deleted the Webtools.bundle and now its working again!
