### ISSUE TITLE
Can't make it start on MELE A1000 A10 ARMv7 package

### ISSUE THREAD

**Issue by raver2046** [trakt/Plex-Trakt-Scrobbler#318]
Hello
same problem like this issue : https://github.com/trakt/Plex-Trakt-Scrobbler/issues/294
cat /proc/cpuinfo

```
Processor       : ARMv7 Processor rev 2 (v7l)
BogoMIPS        : 1006.38
Features        : swp half thumb fastmult vfp edsp neon vfpv3
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x3
CPU part        : 0xc08
CPU revision    : 2

Hardware        : sun4i
Revision        : 0000
Serial          : 0000000000000000
```

fixed with 

```
[libraries]
cpu_type = marvell-pj4
```

**Comment by fuzeman** [comment]
Thanks, will make sure this is noted in the wiki soon.

**Comment by fuzeman** [comment]
This information is finally available on the wiki: https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Installation%20-%20Mele%20A1000#fix-cpu-type-detection
