### ISSUE TITLE
Push don't work

### ISSUE THREAD

**Issue by katar25** [trakt/Plex-Trakt-Scrobbler#320]
when i try push my tv shows for plex , trakt stop in 44% and don't work, don't push tvshows for plex... why don't work??
one example: i see all episodes for "Alias" and trakt have "Watched 105 of 105 episodes for 435 plays" but in plex have all episodes not whatched. why don't syncronize??

**Comment by fuzeman** [comment]
Could you post the latest plugin log file (after attempting another sync)? see [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files) for the location.

**Comment by fuzeman** [comment]
> one example: i see all episodes for "Alias" and trakt have "Watched 105 of 105 episodes for 435 plays" but in plex have all episodes not whatched. why don't syncronize??

As removing watched states from Trakt.tv could cause huge data loss if anything went wrong, I've decided to just ignore syncing these changes currently.

I might consider enabling removal of watched states when we have better backup functionality built into the plugin, but currently this would be a very risky feature to implement.
