### ISSUE TITLE
Recommended settings for Trakt Scrobbler on PMS

### ISSUE THREAD

**Issue by mbxIO** [trakt/Plex-Trakt-Scrobbler#321]
Hey guys,

I am new to trakt and I have been trying to get the "perfect" configuration setup with the scrobbler in Plex Media Server. 

I am running the latest master version of the scrobbler but I'm having a hard time getting my shows to constantly sync and I've noticed that Trakt is picking up on the currently watched show "status" 50% of the time. 

I was hoping someone could let me know what the recommended settings are and what settings are recommended to enable, based on the default setup. 

Thanks,

**Comment by fuzeman** [comment]
I'm guessing you sorted this out (based on your discussion in Gitter)?
