### ISSUE TITLE
How to sync multiple users (trakt + plex) and enable filter per client by name

### ISSUE THREAD

**Issue by elwin1234** [trakt/Plex-Trakt-Scrobbler#324]
Hi,

We have the following situation. We have one Plex server without a Plex pass which is shared to multiple users (by using friend list). We want to scrobble multiple plex/trakt users that use the same Plex server, playing content on chromecast and web.

When we add all accounts (plex + trakt combinations) at the following url
http://trakt-for-plex.github.io/configuration/#/configuration/accounts?id=1 and add one user rule, namely **account: Map** and **name: Any** (leave client rules empty) at http://trakt-for-plex.github.io/configuration/#/configuration/rules, the played content on Plex is scrobbled to the right account (when testing with multiple accounts). But, as soon as we try to add a client rules (because we want to filter out Kodi to scrobble, we use an other plugin for that), it doesn't work any more. It seems that everything is scrobbled to one user in this scenario.

**Comment by fuzeman** [comment]
Will need to try reproduce this issue myself, how are you accessing Plex in Kodi (DLNA, PlexBMC, PlexKodiConnect)?

**Comment by elwin1234** [comment]
Using PlexBMC

**Comment by elwin1234** [comment]
Any update on this?

**Comment by Karmalakas** [comment]
Can confirm the problem still exists. Players used - OpenPHT, Plex Media Player and Plex Web Player. While no Client Rules, it seems all good. As soon as I add any Client Rule, all activity from all users goes to main Plex user account and syncs to that user's Trakt account. Using latest Server, Players and Trakt plugin.
