### ISSUE TITLE
Scrobbler does not work in Plex Media Server

### ISSUE THREAD

**Issue by miteyema** [trakt/Plex-Trakt-Scrobbler#325]
I have a FreeNAS system with a Plex Media Server (PMS) on it.
FreeNAS runs FreeNAS-9.10-STABLE-201605240427.
PMS runs version 0.9.16.6.1993, I have installed it using a plugin.

I have followed the tutorial on [https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Installation%20-%20Linux%20(Shell)](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Installation%20-%20Linux%20(Shell)) to install the Plex-Trakt-Scrobbler.

Instead of
`cp -r Plex-Trakt-Scrobbler-*/Trakttv.bundle "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/"`
I had to use the following command:
`cp -r Plex-Trakt-Scrobbler-master/Trakttv.bundle "/usr/pbi/plexmediaserver-amd64/share/plexmediaserver/Resources/Plug-ins-5089475/"`

The Trakt.tv channel appears on my PMS and I could configure it with a PIN-code.
If I watch a movie using PMS, this is not reflected (scrobbler) on [https://trakt.tv](https://trakt.tv).
I don't find why... Can someone help me?

The log is attached.
[log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/295548/log.txt)

**Comment by fuzeman** [comment]
```
/usr/pbi/plexmediaserver-amd64/share/plexmediaserver/Resources/Plug-ins-5089475
```

This directory is the system plugins directory, and is only for plugins bundled with Plex Media Server.

-----------------------

It looks like the user `Plug-ins` directory should be located here (according to this [page](https://forums.freenas.org/index.php?threads/where-is-the-path-to-the-plex-media-server-plugin-folder.40005/)):
```
/var/db/plexdata
```
