### ISSUE TITLE
Plugin not working on server 0.9.17.0

### ISSUE THREAD

**Issue by Doonga** [trakt/Plex-Trakt-Scrobbler#326]
I realize that the server version is a preview, so I'm not expecting that this would be fixed right away, but I did want to report that the plugin is having issues with this version.

I think it is scrobbling correctly, I'm not 100% sure because I use trakt on Emby also and I was testing with both today. If you try to load the channel in Plex, it will usually come back and say that the channel isn't responding. Sometimes it will load, but not all of the tasks will have icons, if I try to run any of the sync tasks, they just hang and fail.

Again, just wanted to pass this along before this version comes out of preview.

Thanks!

**Comment by Troklon** [comment]
I'm running the preview release 0.9.17.0 as well but did not see any such behaviour. Are you running the newest version of the plugin?

**Comment by Doonga** [comment]
I am, in fact I did a clean install while trying to fix it. My Plex server is on Ubuntu 16.04.

**Comment by Troklon** [comment]
I'm running on a Windows 10 machine. Perhaps that's the difference?

**Comment by Doonga** [comment]
Certainly possible. On the Plex forums, I've seen some people say it's broken and others say it's fine. Wouldn't be surprised if the OS was a factor.

**Comment by mrcirillo** [comment]
I am having an issue with the 9.17 release as well running on Archlinux. This plugin is new to me - so I can't comment on previous versions. I was able to install the plugin but it is nearly impossible to get the settings for it to open in the Channel pane (takes many tries before I can even see it, otherwise the loading indicator just spins and goes away) and when I try to save my settings the plugin reports that the settings weren't saved (although they actually have).

**Comment by Doonga** [comment]
That's the behavior I was seeing. I ended up rolling back to 0.9.16.6 for now. Looks like Linux might be the common theme.

**Comment by ewascome** [comment]
Having the same issue with Trakt not working with Plex 0.9.17 on Ubuntu.  Similar functionality as @mrcirillo

**Comment by fuzeman** [comment]
This might be causing some issues:
> (Preferences) Hide plugin time-out preference, ensure it's always at least fifteen seconds. (#4406)

This means the plugin needs to start up within 15s, otherwise Plex Media Server will just kill the process and attempt to start the plugin up again.

I'll need to do some more testing to determine what can be done about this issue.

---------------------------------------------------

@Doonga It looks like the plugin might be crashing when it attempts an HTTPS connection as all your logs are ending with:
```
Starting new HTTPS connection (1): plex.tv
```

What kind of machine are you running PMS on? posting the output of `cat /proc/cpuinfo` will help.

**Comment by Doonga** [comment]
It's just a 64 bit Ubuntu 16.04 install. Info below.

I'm wondering if using a custom access url was irritating it. It would be odd that it would break off of a sudden. I was having chromecast issues with the custom URL so I removed it. I'll try installing 0.9.17.0 again now that I'm back to a more vanilla Plex config. I'll post the results of that later on.

processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Xeon(R) CPU E3-1270 v3 @ 3.50GHz
stepping        : 3
microcode       : 0x1d
cpu MHz         : 3536.230
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts
bugs            :
bogomips        : 6999.52
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 1
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Xeon(R) CPU E3-1270 v3 @ 3.50GHz
stepping        : 3
microcode       : 0x1d
cpu MHz         : 3490.019
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 1
cpu cores       : 4
apicid          : 2
initial apicid  : 2
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts
bugs            :
bogomips        : 6999.52
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 2
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Xeon(R) CPU E3-1270 v3 @ 3.50GHz
stepping        : 3
microcode       : 0x1d
cpu MHz         : 3198.125
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 2
cpu cores       : 4
apicid          : 4
initial apicid  : 4
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts
bugs            :
bogomips        : 6999.52
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 3
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Xeon(R) CPU E3-1270 v3 @ 3.50GHz
stepping        : 3
microcode       : 0x1d
cpu MHz         : 3613.613
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 3
cpu cores       : 4
apicid          : 6
initial apicid  : 6
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts
bugs            :
bogomips        : 6999.52
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 4
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Xeon(R) CPU E3-1270 v3 @ 3.50GHz
stepping        : 3
microcode       : 0x1d
cpu MHz         : 2404.609
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts
bugs            :
bogomips        : 6999.52
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 5
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Xeon(R) CPU E3-1270 v3 @ 3.50GHz
stepping        : 3
microcode       : 0x1d
cpu MHz         : 2424.160
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 1
cpu cores       : 4
apicid          : 3
initial apicid  : 3
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts
bugs            :
bogomips        : 6999.52
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 6
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Xeon(R) CPU E3-1270 v3 @ 3.50GHz
stepping        : 3
microcode       : 0x1d
cpu MHz         : 3500.546
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 2
cpu cores       : 4
apicid          : 5
initial apicid  : 5
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts
bugs            :
bogomips        : 6999.52
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

processor       : 7
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Xeon(R) CPU E3-1270 v3 @ 3.50GHz
stepping        : 3
microcode       : 0x1d
cpu MHz         : 3522.832
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 3
cpu cores       : 4
apicid          : 7
initial apicid  : 7
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm epb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt dtherm ida arat pln pts
bugs            :
bogomips        : 6999.52
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

**Comment by fuzeman** [comment]
Just pushed some changes to the [develop](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip) branch which should resolve this issue, just needs some further testing (on BSD and OS X) to make sure nothing has been broken with these changes.

-----------------

It appears changes in this release of Plex Media Server broke the compiled version of pyOpenSSL bundled with the plugin. The changes on the develop branch allows the plugin to fallback to the built-in SSL library if any issue is detected with pyOpenSSL, this isn't ideal ([details](https://github.com/pypa/pip/issues/2681#issuecomment-92541888)) but will at least resolve this issue for now..

**Comment by KingJ** [comment]
As an FYI, 0.9.17.2 has just been released as a Plex Pass download (i.e. stable) rather than just a preview release like 0.9.17.0/1 were.

**Comment by fuzeman** [comment]
@KingJ Thanks, will try to get an update out this weekend. *(and merge the changes into the "beta" branch)*

**Comment by fuzeman** [comment]
Fix released in [v1.0.3.1](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.0.3.1)
