### ISSUE TITLE
Support for üöä letters and blank space in Global Filter - Users

### ISSUE THREAD

**Issue by Oli1990** [trakt/Plex-Trakt-Scrobbler#330]
Hello,

is it possible to add a support for äöü letters and blank space in the field Global Filters - Users?
In my case i need to add my user in this field and in my user name is a ö and a blank space. So when i will save the settings i become an error that the settings could not be saved correctly. Thank you.

![error](https://cloud.githubusercontent.com/assets/18211509/16332418/0ccfedbe-39f6-11e6-8692-1ab7e6bf8ad3.JPG)
![error2](https://cloud.githubusercontent.com/assets/18211509/16332419/0cef1158-39f6-11e6-9eb7-0fc4292f107c.JPG)

**Comment by fuzeman** [comment]
This is a bug with the Plex Plugin Framework, as a workaround the plugin supports matching the characters without diacritic marks.

**Example:**
If your username is `äöü`, you can just enter `aou` in the "Global Filters - Users" option.

**Comment by Oli1990** [comment]
Okay, thank you for the fast answer.
