### ISSUE TITLE
Difference between Plex Chanel Configuration and Web Configuration 

### ISSUE THREAD

**Issue by Bazzu85** [trakt/Plex-Trakt-Scrobbler#331]
Hi,

I trying to understand some configuration, for example Rules/User Rules under web configuration.
When modifing User Rules for track only my plex user, It isn't show in plex chanel configuration.

I've tried with Account/Sync interval and the change is synced..

What's the current best method to configure the plugin?

**Comment by fuzeman** [comment]
The configuration in Plex/Web and at http://trakt-for-plex.github.io/configuration are synchronized, so either interface can be used. Plex/Web does have a few extra options that aren't available on the configuration site though.

**Note:** User rules are different to the "Global Filter - Users" option in Plex/Web. Filters are applied first, then rules are used to find a matching account for your watching activity.

Hopefully that makes sense :smiley:, let me know if you have any other questions.

**Comment by Bazzu85** [comment]
Thx for the reply..
Another question, but about scrobling..
Scrobble is an auto activity right? I sync all to my plex media server, marked 2 episodes of excel saga as watched and can't find in my trakt history..

**Comment by fuzeman** [comment]
@Bazzu85 "Scrobble" will automatically update your Trakt.tv profile while you are watching something with Plex Media Server. 

If you manually mark items as watched in Plex Media Server, these changes will only be sent to Trakt.tv if you run a "Full" or "Push" sync via the channel menu in Plex/Web.
