### ISSUE TITLE
Plex account is missing the token server

### ISSUE THREAD

**Issue by onepartscissors** [trakt/Plex-Trakt-Scrobbler#335]
I previously has this channel installed with no problems, but when i had to reinstall my plex server, i've started getting this error when i try and sync.

Plex account is missing the token server

I've entered my settings, added the Authentication PIN.
I have tried the master branch as well as develop branch. I've tried installing through the unsupported App Store v2's Web Tools, still getting the same issue.

When i log into http://trakt-for-plex.github.io/configuration, i see my server listed three times - when i click on the first 2, they give the same error: "Unable to find valid connection"
and the third one says "Unknown error".

I'm at a bit of a loss on what to do next. Can you advise me on what info i need to provide for you to get some clarify on this issue?

**Comment by fuzeman** [comment]
Could you attach the latest plugin log file, see [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files) for more details.

**Comment by onepartscissors** [comment]
Ok, here it is attached.

Incidentally, I checked out tag v0.9.1.29 which is the last version that used normal username and password authentication instead of the pin, and that works perfectly.

So it's falling down in the new pin authentication.

[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/344907/com.plexapp.plugins.trakttv.log.txt)

**Comment by fuzeman** [comment]
Found some issues that might be causing this issue, install the development branch ([develop.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip)) and try syncing or scrobbling to see if this error is still happening.

**Comment by VeronicaEC** [comment]
Hi, i had the same problem but found a workarround in the latest v1.0.3.3 (Stable):
1. Install and fully setup the Trakt.tv channel FROM Plex: http://localhost:32400/web/index.html , that includes the Authentication PIN option.
2. Login to the Configuration web-app: http://trakt-for-plex.github.io/configuration , select your Plex Server and then go to Accounts. There you should find TWO tabs, the Trakt tab should have a green check mark while the Plex tab most likely won't.
3. Select the Plex tab and right below to Authenticate select MODE > HOME > Select your USER, done!. You should now see your user name in big letters, photo and also your email at the top and to the left.
4. Finally you must click on the "save changes" button at the top-right (It has a floppy disk icon).

**Comment by onepartscissors** [comment]
@fuzeman the latest develop.zip that you linked to works perfectly! You can commit that whenever you happy, but it works awesome. Sorry for the 22 day delay in answering!

**Comment by fuzeman** [comment]
Fix has been released in [v1.1.0.6](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.1.0.6).

**Comment by fiveoone** [comment]
> Hi, i had the same problem but found a workarround in the latest v1.0.3.3 (Stable):
> 
> 1. Install and fully setup the Trakt.tv channel FROM Plex: http://localhost:32400/web/index.html , that includes the Authentication PIN option.
> 2. Login to the Configuration web-app: http://trakt-for-plex.github.io/configuration , select your Plex Server and then go to Accounts. There you should find TWO tabs, the Trakt tab should have a green check mark while the Plex tab most likely won't.
> 3. Select the Plex tab and right below to Authenticate select MODE > HOME > Select your USER, done!. You should now see your user name in big letters, photo and also your email at the top and to the left.
> 4. Finally you must click on the "save changes" button at the top-right (It has a floppy disk icon).

6 years later, this solve my problem! Thanks!

**Comment by Escondido** [comment]
To piggyback off the prior instructions, you have to click on the pencil icon (EDIT) under your name in order to access MODE.

**Comment by user4302** [comment]
> Hi, i had the same problem but found a workarround in the latest v1.0.3.3 (Stable):
> 
> 1. Install and fully setup the Trakt.tv channel FROM Plex: http://localhost:32400/web/index.html , that includes the Authentication PIN option.
> 2. Login to the Configuration web-app: http://trakt-for-plex.github.io/configuration , select your Plex Server and then go to Accounts. There you should find TWO tabs, the Trakt tab should have a green check mark while the Plex tab most likely won't.
> 3. Select the Plex tab and right below to Authenticate select MODE > HOME > Select your USER, done!. You should now see your user name in big letters, photo and also your email at the top and to the left.
> 4. Finally you must click on the "save changes" button at the top-right (It has a floppy disk icon).

this might have worked for me, along with this 
https://github.com/trakt/Plex-Trakt-Scrobbler/issues/596#issuecomment-862643646

**Comment by jimmyrat** [comment]
Thank you, Angelo!
My install was updating current watched items, but didn't catch up with the two months that Trakt was disconnected from Plex.  After following steps 1-4, now everything's up to date.

Jim ***@***.*** 

    On Saturday, April 2, 2022, 09:22:36 AM CDT, Angelo ***@***.***> wrote:  
 
 



Hi, i had the same problem but found a workarround in the latest v1.0.3.3 (Stable):
   
   - Install and fully setup the Trakt.tv channel FROM Plex: http://localhost:32400/web/index.html , that includes the Authentication PIN option.
   - Login to the Configuration web-app: http://trakt-for-plex.github.io/configuration , select your Plex Server and then go to Accounts. There you should find TWO tabs, the Trakt tab should have a green check mark while the Plex tab most likely won't.
   - Select the Plex tab and right below to Authenticate select MODE > HOME > Select your USER, done!. You should now see your user name in big letters, photo and also your email at the top and to the left.
   - Finally you must click on the "save changes" button at the top-right (It has a floppy disk icon).


this might have worked for me, along with this
#596 (comment)
