### ISSUE TITLE
Can't connect plex with trakt

### ISSUE THREAD

**Issue by raveymoo** [trakt/Plex-Trakt-Scrobbler#336]
I've installed this on Windows and Openmediavault, and in both cases when I try to select a server on the web based configuration screen it just sits there trying to connect indefinately. On both plex servers if I click on the channel I just get a 0 in the top left and no options. I've downloaded again to make sure I have the current version and it's still the same.

In my trakt account I do have a history, so I've managed to sync from my openmediavault server at some point, but it's not up to date, and non of the shows from the windows server show up. 
[Plex Media Server.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/344814/Plex.Media.Server.zip)
[com.plexapp.plugins.trakttv.log.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/344815/com.plexapp.plugins.trakttv.log.zip)

**Comment by fuzeman** [comment]
From the plugin log file:
> ```
> C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-5089475\Trakttv.bundle
> ```

Looks like you've installed the plugin into the wrong directory, on Windows you should be installing the plugin under:
```
C:\Users\<username>\AppData\Local\Plex Media Server\Plug-ins
```

The `Plug-ins-5089475` directory is **only** for plugins bundled with Plex Media Server, the user `Plug-ins` directory is for everything else.

------------

Not sure about the issue on your OMV server, attach the plugin log file if you want me to look at that as well.

**Comment by raveymoo** [comment]
Okay thanks, I have that working now on windows. On OMV I think I had the addon installed the one which is only for bundled plugins:

/usr/lib/plexmediaserver/Resources/Plug-ins-7be11e1/

Now I'm pretty sure there was also 
/usr/lib/plexmediaserver/Plex Media Server/Resources/Plug-ins-7be11e1/

I could see that both had exactly the same contents (including some tvheadend addons that I know I didn't put in 2 locations). I'm sure I copied the trackt addon to the latter of these 2 and it appeared in the first. What is wierd, and why I'm saying "I'm sure" above, is that now when I try to cd to sub directory Plex Media Server it says it's not a directory, but it's not a text tile either.

bash: cd: Plex Media Server: Not a directory
******** Plex Media Server: Not a text file ********

Anyway, I've removed the plugin from /usr/lib/plexmediaserver/Resources/Plug-ins-7be11e1/ (but as I can no longer access /usr/lib/plexmediaserver/Plex Media Server/Resources/Plug-ins-7be11e1/ I don't know what's in there, or if I was simply mad). 

I've added the plugin to my plex install :/media/6e408d91-cc67-40ef-8591-0d90f7c4386e/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins

And it doesn't show up in my channels. Incidently I tried putting it back in the wrong location and it no longer shows up in my channels, so that's a bit bemusing, plus somehow my viewing history did propagate into trakt at some point in the last couple of weeks, though perhaps because I had a trakt addon in kodi along with plexbmc (but if it was because of that it's no longer updating trakt with viewed shows).

Sorry for rambling, just trying to provide as much info as possible.

[com.plexapp.plugins.trakttv.log.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/345309/com.plexapp.plugins.trakttv.log.zip)
[Plex Media Server.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/345310/Plex.Media.Server.zip)

**Comment by fuzeman** [comment]
Just remembered OMV requires some extra setup steps, see this comment: https://github.com/trakt/Plex-Trakt-Scrobbler/issues/278#issuecomment-197817330

**Note:** You don't need to install the "issue/278" version of the plugin, the latest stable release includes these changes.

**Comment by raveymoo** [comment]
superb, that's it working now. thanks so much :)

**Comment by Dan0sz** [comment]
Just wanted to stop by and let everyone know, that I was struggling with Plex Trakt Scrobbler and OMV as well. Same issues as above, method one and two didn't work for me. What did work was this: http://forum.openmediavault.org/index.php/Thread/12871-Plex-Plugin-looks-in-wrong-directory/?postID=109487#post109487
