### ISSUE TITLE
CorruptError: database disk image is malformed

### ISSUE THREAD

**Issue by hakuseki** [trakt/Plex-Trakt-Scrobbler#338]
I'm getting this error message when syncing from Plex.
Performing manual sync creates this message but it looks like scrobbling TV-shows works…

What more info can I append to the issue?

Plex version 1.0.0.2261
trakt.tv version installed 	2016-07-05 19:31:36 
OSX 10.11.5

**Comment by fuzeman** [comment]
Deleting the plugin cache at the following directory might resolve this issue:
```
Plug-in Support\Caches\com.plexapp.plugins.trakttv
```

**Note:** Might be a good idea to shutdown Plex Media Server first, delete the directory and then start Plex Media Server up again.

-----------------

If that doesn't work post the latest plugin log file here (after attempting to run another sync), see [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files) for more details.

**Comment by hakuseki** [comment]
Worked. Thx

**Comment by shayonpal** [comment]
> Deleting the plugin cache at the following directory might resolve this issue

@fuzeman any idea where can I find the directory on macOS?

**Comment by gavla** [comment]
I had the same error end deleted every file in every sub directory /Application Suppor/Plex Media Server/⁨Plug-in Support⁩ that had com.plexapp.plugins.trakttv in the name or dirt anew the restarted PMS and all was working after adding a new south pin

**Comment by CBearman** [comment]
Thanks, this worked for me
