### ISSUE TITLE
The channel is not responding.

### ISSUE THREAD

**Issue by Sawy7** [trakt/Plex-Trakt-Scrobbler#342]
The plugin was working until few days ago when I noticed that my Trakt stats don't match my Plex library. I tried to look into it but the plugin stopped working. I can't configure it and I can't initiate any kind of sync. I tried reinstalling the plugin and even the whole Plex. I am running Raspberry Pi 2 with Raspbian Jessie and latest version of Plex Media Server.

**Comment by fuzeman** [comment]
Could you attach the plugin log file? see [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files) for more details.

**Comment by Sawy7** [comment]
Here is the log. Changed from .log to .txt, because GitHub didn't want to accept it.
[com.plexapp.plugins.trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/371502/com.plexapp.plugins.trakttv.txt)

**Comment by fuzeman** [comment]
I think this is similar to an issue that was reported on the forum thread, try install the development branch ([develop.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip)) and let me know if this works or not.

**Comment by Sawy7** [comment]
Development branch works. I installed, started full sync and it merged my watched content. Great! Thank you.
