### ISSUE TITLE
How to disable Trakt for other users?

### ISSUE THREAD

**Issue by mobiousblack** [trakt/Plex-Trakt-Scrobbler#343]
I finally got this plugin to work on plex however I have friends who also use my Plex server with separate accounts. Now Trakt seems to be syncing their progress on shows to my account which in turn is causing stuff to me marked as viewed on my end when it shouldn't. How do I disable their use of the plugin?

**Comment by fuzeman** [comment]
You can filter out other users by entering **your** Plex username into the "Global Filter - Users" field (via Plex/Web).

-------------------

> This has been bugging me for while.
> I followed https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/FAQ---Scrobbling 
> And I still can't figure out if I should assign my trakt user to my Plex account or map to any as the GIF shows. & Is the Global Filter is for users who I want to them to be excluded or should it be my plex user ?

If you just want to filter out all the other users, enter **your** Plex username into the "Global Filter - Users" field. The configuration site should only be used to setup individual Trakt.tv accounts for each user on your server. *(see [this](https://github.com/trakt-for-plex/configuration/issues/1) guide)*

**Comment by F-AlFaris** [comment]
> If you just want to filter out all the other users, enter your Plex username into the "Global Filter - Users" field. The configuration site should only be used to setup individual Trakt.tv accounts for each user on your server. (see this guide)

> So should I delete user rules in the configuration site ? or do as shown and map/any ?

**Comment by fuzeman** [comment]
All you should need is "Global Filter - Users" set to your Plex username and one user rule on the configuration site set to your account with "Any" specified for the name field.
