### ISSUE TITLE
Playback progress

### ISSUE THREAD

**Issue by elemis** [trakt/Plex-Trakt-Scrobbler#348]
When I watch a video on Plex, then stop and open it with Infuse (iOS or tvOS), Infuse lets me resume from where I left. But I couldn't make it work the other way around. Not sure if this is the right place to ask but how can I pick up from where I left on Infuse when I go back to Plex? (I have the Trakt plugin installed via Unsupported AppStore and it appears under Channels, and Playback Progress is set as Push + Pull, scrobble is on)

**Comment by elemis** [comment]
Anyone?

Plex Media Server version: 1.0.3.2461-35f0caa
Trakt plugin version: 1.0.3.3

Here are my logs: 
[traktlogs.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/418258/traktlogs.txt)

**Comment by fuzeman** [comment]
Looks like playback progress is being imported for some items:
```
2016-08-15 17:30:45,629 :  DEBUG - "GET /:/timeline?ratingKey=3935&state=stopped&time=671921&duration=8502218 HTTP/1.1" 200 175
2016-08-15 17:30:45,647 :  DEBUG - "GET /:/timeline?ratingKey=4306&state=stopped&time=1549131&duration=5416411 HTTP/1.1" 200 175
2016-08-15 17:30:46,358 :  DEBUG - "GET /:/timeline?ratingKey=5153&state=stopped&time=1281658&duration=4841800 HTTP/1.1" 200 175
2016-08-15 17:30:46,374 :  DEBUG - "GET /:/timeline?ratingKey=5409&state=stopped&time=838574&duration=2828662 HTTP/1.1" 200 175
2016-08-15 17:30:46,417 :  DEBUG - "GET /:/timeline?ratingKey=5439&state=stopped&time=407949&duration=2466008 HTTP/1.1" 200 175
```

Are you aware a sync is required to import playback progress from Trakt.tv? or is playback progress still not updating correctly after a sync?

**Comment by elemis** [comment]
I tried all sync options: full, pull, quick pull from trakt etc. But none of them work. Playback progress fails to update on Plex. While Infuse successfully updates the progress everytime I watch.

**Comment by elemis** [comment]
I finally figured out what the problem is. Currently I'm rewatching a show which I completed watching before. Today when I watched a new episode from a different show, the playback progress updated! So I marked the episodes of the old show as unwatched, and its progress gets updated now as well. But I had to disable the sync for "watched" :( not sure how it will effect me in the long run. Also now I'm afraid to do a full sync. I don't want the show to become completely unwatched on Trakt. So I had to disable auto sync too.

**Comment by fuzeman** [comment]
@elemis 
> I finally figured out what the problem is. Currently I'm rewatching a show which I completed watching before. Today when I watched a new episode from a different show, the playback progress updated! So I marked the episodes of the old show as unwatched, and its progress gets updated now as well. But I had to disable the sync for "watched"

I'll take another look at how playback progress syncing has been implemented, it really should support importing the playback progress of shows that are being re-watched.

----------

@elemis 
> Also now I'm afraid to do a full sync. I don't want the show to become completely unwatched on Trakt. So I had to disable auto sync too.

The only changes that can be applied to your Trakt.tv profile are:
 - **Collection:**
    - add
    - *remove (if "Clean collection" is enabled)*
 - **Ratings:**
    - add
    - change
 - **Watched:**
    - add

*(the plugin doesn't support removing items from your Trakt.tv watched history)*
