### ISSUE TITLE
Trakt Channel not showing up in Plex

### ISSUE THREAD

**Issue by writzthecat** [trakt/Plex-Trakt-Scrobbler#352]
Hello,

i've tried to install the trakt plugin several times on my machine, but it's not showing up :-(

I've aleady checked the permissions but it won't work.

Im runnig it under OMV 2.0 on my Intel® Octa Core Avoton C2750.

Hopefully you can help me out

br

Writz

[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/431166/com.plexapp.plugins.trakttv.log.txt)
[com.plexapp.plugins.trakttv.log1.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/431167/com.plexapp.plugins.trakttv.log1.log.txt)
[Plex Media Server.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/431168/Plex.Media.Server.log.txt)

**Comment by fuzeman** [comment]
OMV requires some extra installation steps, see [this comment](https://github.com/trakt/Plex-Trakt-Scrobbler/issues/278#issuecomment-197817330) for more details.

**Note:** the latest version of the plugin supports the changes mentioned in the comment, don't install the version of the plugin mentioned there.

**Comment by lovesprung** [comment]
Hi! I have the same issue. I installed the plugin (several times), but for some reason it won't appear on my channel page. I am using Windows 10 x64. Could you please help me out? Thanks.

[com.plexapp.plugins.trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/439226/com.plexapp.plugins.trakttv.txt)
[Plex Media Server.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/439225/Plex.Media.Server.txt)
