### ISSUE TITLE
Can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by timbooo** [trakt/Plex-Trakt-Scrobbler#356]
After a trakt full sync and trakt pull I got a lot of exceptions. Log file is attached.
I'm using scrobbler version #354 on a Synology DS 216play (DSM 6.0.2-8451 Update 1) with Plex server 1.1.3.2700-6f64a8d.

[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/453261/com.plexapp.plugins.trakttv.log.txt)

**Comment by fuzeman** [comment]
Try the latest development version of the plugin, download here: https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip

**Comment by timbooo** [comment]
I stopped plex, removed all logs, updated plugin, started and attached the log.
[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/456412/com.plexapp.plugins.trakttv.log.txt)
