### ISSUE TITLE
Trakt.TV scrobber plugin not working.

### ISSUE THREAD

**Issue by Markmaster** [trakt/Plex-Trakt-Scrobbler#359]
Hi.
I use Plex-Trakt-Scrobber {"version": [1, 0, 3, 3], "branch": "master"}. I am on Windows 10 Pro x64, Plex Server 1.1.3.2700.
I have TV Series in my collection, I download, install and enable Plugin, start watching the series, but there were no watched marks on my Trakt.TV account. What I am doing wrong?
Please help.

**Comment by fuzeman** [comment]
Sorry for the slow response, but could you post the latest plugin log file after watching something in Plex. See [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files) for more details on where log files are stored.
