### ISSUE TITLE
Sync triggers This Channel Is Not Responding Error and [Exception] invalid load key, 'Z'

### ISSUE THREAD

**Issue by wellingssimon** [trakt/Plex-Trakt-Scrobbler#361]
Hi. Firstly, great work with the scrobbler. I've been using this on and off for over a year now and not really given it any more thought as it was working. However, when running manual syncs I'm now noticing the error in the title. I attach the latest log in the hope you can advise.
[com.plexapp.plugins.trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/499071/com.plexapp.plugins.trakttv.txt)

**Comment by fuzeman** [comment]
The Trakt.tv data cache is probably corrupt, try the following:

1. Shutdown Plex Media Server
2. Delete the following file:

    ```
    /Users/simon/Library/Application Support/Plex Media Server/Plug-in Support/Caches/com.plexapp.plugins.trakttv/trakt.db
    ```
3. Start Plex Media Server, and attempt another sync

**Comment by wellingssimon** [comment]
@fuzeman - that seems to have resolved my issue. Many thanks for your time and help.

**Comment by ExtraKiller** [comment]
Hi, I have the same issue, I tried deleting the db, but it didn't help. here is my log
[com.plexapp.plugins.trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/502552/com.plexapp.plugins.trakttv.txt)
