### ISSUE TITLE
Multiple user one plex/trakt account config

### ISSUE THREAD

**Issue by slbevis** [trakt/Plex-Trakt-Scrobbler#364]
Hi Guys,

More of a question than an issue I think. I have been playing with the config for a while and cannot seem to get the correct setup. Please confirm that what I am trying to achieve is possible:
- One Plex user account (no Plex Pass) used by multiple devices (PS4, Smart TV, PHT/OpenPHT) on one LAN
- PMS is running on the same PC that runs PHT/OpenPHT
- Only want to scrobble watched / progress flags from one of the clients (the PHT/OpenPHT client)
- Sync from Trakt back to Plex and overwrite watched / progress flags from other devices, basically ignoring the actions from these other devices and keeping the library up to date based on the PHT/OpenPHT actions 

I have tried to filter scrobbles by both IP address (static) and Client Name but actions from the other devices continue to show in my Trakt account and in Plex. 

Thanks!

**Comment by fuzeman** [comment]
>  - Only want to scrobble watched / progress flags from one of the clients (the PHT/OpenPHT client)

Real-time watching activity from other devices can be filtered with the "Global Filter" options in the channels settings and the "Rules" on the configuration site. If all your devices are connected to a single Plex account, a sync will ignore these filters and push the history to your Trakt.tv profile anyway though.

>  - Sync from Trakt back to Plex and overwrite watched / progress flags from other devices, basically ignoring the actions from these other devices and keeping the library up to date based on the PHT/OpenPHT actions

Syncs can only push the entire watched history for your Plex account, there is no way we can filter out your watched history per-device during syncs (limitation in how Plex stores watched history).

--------------------

I've got plans to support merged accounts, where multiple Plex accounts could be merged together and synchronized with a single Trakt.tv account. But this will still be months away.

**Comment by slbevis** [comment]
So basically at the moment there is no way to completely disregard / not record watched events from other devices on the same Plex account either through Trakt or Plex? Plex Pass is the only option?

**Comment by fuzeman** [comment]
> So basically at the moment there is no way to completely disregard / not record watched events from other devices on the same Plex account either through Trakt or Plex?

Yeah, Plex stores your watched history without any device identifiers - so the plugin is unable to filter it to only push watched history for certain devices to your Trakt.tv profile.

Plex clients could technically have an option to disable watched state updates and timeline events, but I'm not aware of any clients that support this feature.

> Plex Pass is the only option?

Yeah, Plex Pass is probably the only solution.
