### ISSUE TITLE
Sync watched episodes from mobile with server off

### ISSUE THREAD

**Issue by Bazzu85** [trakt/Plex-Trakt-Scrobbler#365]
Hi, I sync my episodes on phone and watch with server shuted off..

When I synv phone and server status for watched episodes this changes are not updated on trakt

There's a sort of configuration for this situation?

**Comment by fuzeman** [comment]
The plugin can synchronize watched history for items watched while the server is offline, but you will need to:

1. Start Plex Media Server
2. Run "Sync now" on the device
3. Run a full profile sync by opening Plex/Web and clicking: `Channels -> Trakt.tv -> Sync -> Full`

**Comment by Bazzu85** [comment]
Thx for the reply..

I known the steps to manually sync, infact I do this every 2 days..

My question was if there was an automatic method..

Bazzucco Cristian

Il 07/ott/2016 12:00 AM, "Dean Gardiner" <notifications@github.com> ha
scritto:

**Comment by fuzeman** [comment]
Changing "Sync - Run every" (in the plugin settings) to something like "Day" should force the plugin to update your Trakt.tv profile at the specified interval.

I'm not sure how Plex handles the syncing of watched history though... I'm guessing it must automatically sync when the server is available?
