### ISSUE TITLE
Trakt not visible within Recorded TV

### ISSUE THREAD

**Issue by Starminder** [trakt/Plex-Trakt-Scrobbler#366]
Had to reinstall everything from scratch.  This time, Trakt refuses to work properly.  Pulls take seconds because they don't appear to really be working.

I've tried everything I can think of including starting completely over, to no avail.

Appreciate any insight you can provide.  Thanks!

[PMS Plugin Logs.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/533360/PMS.Plugin.Logs.zip)

**Comment by fuzeman** [comment]
Are you triggering a "Pull" sync, or a "Quick Pull" sync?

 - "Quick Pull" will import changes from your Trakt.tv account since your last sync
 - "Pull" will compare your entire Trakt.tv account against your Plex database, and apply any changes that have been found

Running a "Pull" sync should bring everything up to date after reinstalling Plex, if that isn't working post the latest plugin log file (right after running a "Pull" sync).

----------------

> PMS Plugin Logs.zip

Looks like this zip file is empty?

**Comment by Starminder** [comment]
Yep, I've done a "pull" (as opposed to quick pull) a number of times to no avail.  Despite putting the plugin in the plugins folder and "installing" it, it only appears to be there as a channel.  None of the Trakt backgrounds are visible within the recorded tv area - which is my first clue something is amiss.  Further, the syncs and pulls all run in a matter of seconds and despite appearing to be successful don't really seem to do anything.

[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/549257/com.plexapp.plugins.trakttv.log.txt)

**Comment by fuzeman** [comment]
These messages indicate you have movies/shows with unsupported metadata agents:

```
2016-10-24 19:21:43,905 - plugin.sync.modes.pull.movies :  INFO - Unsupported agent: None (8 items)
2016-10-24 19:21:43,905 - plugin.sync.modes.pull.movies :  INFO - Unsupported agent: com.plexapp.agents.none (1 items)
2016-10-24 19:21:43,907 - plugin.sync.modes.pull.movies :  INFO - Unsupported agent: local (50 items)
2016-10-24 19:21:43,907 - plugin.sync.modes.pull.movies :  INFO - Found 51 unsupported movie(s)
```

```
2016-10-24 19:21:44,989 - plugin.sync.modes.pull.shows :  INFO - Unsupported agent: local (9 items)
2016-10-24 19:21:44,990 - plugin.sync.modes.pull.shows :  INFO - Found 9 unsupported show(s)
```

This can be caused if you are using an unsupported agent for your libraries, this can be changed at `<Library> -> Edit Library -> Advanced` *(see [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/FAQ---General#3-which-metadata-agents-are-supported) for a list of supported metadata agents)*.

Running "Refresh All" on your libraries might also fix this, there might just be media that wasn't matched correctly in your libraries.

-----------

#### Plex DVR

Not sure if you were referring to Plex DVR, but I believe the Gracenote metadata agent is used for live and recorded media which currently isn't supported.

You might be able to change the metadata agent for the libraries where recorded content is stored, but live content probably can't be detected correctly by the plugin.

I would like to support Gracenote, but this would probably require specific mappings to be created and published via [OpenEntityMap](https://github.com/OpenEntityMap) (similar to how AniDB is supported currently). Will need to have a look how hard this would be to support...

**Comment by Starminder** [comment]
Thanks Fuzeman - So, I waited until Trakt was available late today, reinstalled, and also tried above but to no avail.  I tried following along with the above but Library - Edit Library - Advanced doesn't seem to exist?

I do have PLeX DVR, but as far as I can tell I'm only using the tvdb agent, which should be ok?

When I look at trakt, the things I watch are being scrobbled.  BUT, inside of Plex it no longer shows me, for example, missing tv shows, the trakt background screens, etc.  It's as if it is partially installed?

[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/565227/com.plexapp.plugins.trakttv.log.txt)
[Plex Media Server Logs_2016-11-01_18-40-19.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/565228/Plex.Media.Server.Logs_2016-11-01_18-40-19.zip)

**Comment by Starminder** [comment]
@fuzeman - Did a complete uninstall of Plex using their instructions.  Did a complete reinstall, then added Recorded TV Library, then installed Trakt using your instructions.  No dice.  I guess it is the data?  I'm at a complete loss.

[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/588026/com.plexapp.plugins.trakttv.log.txt)

[Plex Media Server.2.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/588030/Plex.Media.Server.2.log.txt)

[Plex Media Server.3.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/588033/Plex.Media.Server.3.log.txt)

[Plex Media Server.4.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/588037/Plex.Media.Server.4.log.txt)

**Comment by fuzeman** [comment]
> BUT, inside of Plex it no longer shows me, for example, missing tv shows, the trakt background screens, etc. It's as if it is partially installed?

This plugin doesn't actually provide metadata or background screens for your media, that's all handled by the library metadata agent.

-----------------

The metadata agent can be changed here *(might not be available for Plex DVR libraries)*:

![](https://i.imgur.com/D4AOMCw.png)

**Comment by Starminder** [comment]
The plugin WAS showing which TV shows I was missing.  It no longer does that.  

My settings are as above.  

Inside of each TV show there was very obvious "trakt" info and logos.  They are no longer there.  I have reinstalled everything from scratch, and created a very small library for recorded tv.  Nothing.   I am so at a total loss to try and understand whats going on here.

**Comment by fuzeman** [comment]
It sounds like you are talking about [Transmogrify](https://github.com/Transmogrify-for-Plex/Transmogrify-for-Plex-chrome), that extension can display missing episodes and insert links to Trakt.tv in the show/movie pages.

**Comment by Starminder** [comment]
OH.MY.GOD.  I feel like an idiot.  I thought that functionality was part of this plugin.  Well, there's the explanation and solution.  Thank you.

**Comment by fuzeman** [comment]
No worries :smile:
