### ISSUE TITLE
Syncing a friends library share

### ISSUE THREAD

**Issue by Mohounter** [trakt/Plex-Trakt-Scrobbler#367]
I got things set up and it is marking everything watched that I have in my personal server. I am wanting to see what I need to do to get this set up where it will track what I watch on my friends shared libraries. I am assuming that I will have to ask them to enable it but wanted to know what the process was. Thank you in advance.

**Comment by fuzeman** [comment]
The owner of the shared server will need to install the plugin, and setup your account on the server as described here: https://github.com/trakt-for-plex/configuration/issues/1

Let me know if you have any questions or issues setting this up, happy to help.
