### ISSUE TITLE
Seagate personal cloud and plex

### ISSUE THREAD

**Issue by Dhop84** [trakt/Plex-Trakt-Scrobbler#368]
Hi is there anyway of this working with a seagate personal cloud installed version of plex?

**Comment by fuzeman** [comment]
I believe this hardware is supported by the plugin, but some extra installation steps might be required if the plugin can't detect the platform correctly.

Could you attach the latest plugin log file? this will help me identify what steps might be required to get it working correctly. See [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files) for details on where the log files are located.
