### ISSUE TITLE
Not scrobbling episodes as watched that are watched and then immediately deleted

### ISSUE THREAD

**Issue by eallison978** [trakt/Plex-Trakt-Scrobbler#373]
If I watch something on Plex, most notably a TV episode, and then immediately delete it, it does not get scrobbled to Trakt as watched.  I've even made sure to watch the episode in it's entirety and confirmed that Plex marked it as watched.

**Comment by fuzeman** [comment]
Sounds like real-time scrobbling isn't working, does your Trakt.tv profile display "You are watching ..." while you are watching something in Plex?

------------

Attaching the plugin log files after watching something in Plex will help me determine what is happening, see [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files) for more details.

**Note:** Plex Media Server v1.3.0+ broke real-time scrobbling, this has been fixed in v1.1.0.7+ of the plugin.

**Comment by eallison978** [comment]
Scrobbling is working. Trakt does show what I am watching. I have noticed
that thia behavior isn't always there. It may be when I stop playing the
episode short. I'm not certain yet.

On Nov 29, 2016 4:09 PM, "Dean Gardiner" <notifications@github.com> wrote:

Sounds like real-time scrobbling isn't working, does your Trakt.tv profile
display "You are watching ..." while you are watching something in Plex?
------------------------------

Attaching the plugin log files after watching something in Plex will help
me determine what is happening, see this page
<https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files> for more
details.

*Note:* Plex Media Server v1.3.0+ broke real-time scrobbling, this has been
fixed in v1.1.0.7+ of the plugin.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/trakt/Plex-Trakt-Scrobbler/issues/373#issuecomment-263715787>,
or mute the thread

**Comment by eallison978** [comment]
It seems to be consistent with stopping an episode shortly after the
credits begin to roll.  There is probably another 30 seconds to a minute
left to play.  It doesn't necessarily happen only when the episode is deleted.

On Tue, Nov 29, 2016 at 4:44 PM,

> Scrobbling is working. Trakt does show what I am watching. I have noticed
> that thia behavior isn't always there. It may be when I stop playing the
> episode short. I'm not certain yet.
>
>

**Comment by RoNain** [comment]
I have the same behaviour, episode is scrobbling as I've the message "you're watching... during the play, but at the end, the episode is not marked as watched even if I wait for plex to play it completely.

But the new episodes are marked as collected or deleted correctly, only the marked as watched is not working.
Sorry for my poor english, it is not my mother language

I've tried to attach the log file but I have the message "We don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP." event if I zip the file before I attach it

**Comment by RoNain** [comment]
I have the same behaviour, Scrobbling is working as Trakt shows what I'm watching, episode collected and deleted are well taken into account but none are marked as watched.
I've let plex to read the entire episode and waited half an hour before writing this comment.

It seems that I can not attach the log file, even after I've zipped it, I got the message "We don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP."

**Comment by fuzeman** [comment]
Which Plex clients (and version) are you experiencing this issue on? there has been cases of clients incorrectly reporting playback progress which leads to scrobbling issues.

-------------

Does the "Now Playing" view in Plex/Web reflect the status of your client correctly? for example:
 - Item appears when you start watching something
 - Item disappears when you finish (or stop) watching something

If the "Now Playing" view isn't updated correctly (e.g. items are still displayed after you finish watching it), this likely means the client you are using has bugs in it's reporting of playback progress.

**Comment by fuzeman** [comment]
@RoNain 
> It seems that I can not attach the log file, even after I've zipped it, I got the message "We don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP."

Try renaming the `.log` file to `.txt`, or just use something like http://pastebin.com/ or https://gist.github.com/

**Comment by RoNain** [comment]
Hi and thanks for your answer.
I'm using the plex media server for Windows Version 1.2.7.2987 and yes, the now playing is displaying correctly what I'm watching.

Strangely today I  haven't  got any issue with the scrobbling nor the episode marked as watched from plex to Trakt.tv

**Comment by RoNain** [comment]
Today was the worst, none of the episodes I've watched have been marked as seen automatically in Trakt despite multiple restarts of plex and reboots

**Comment by fuzeman** [comment]
@RoNain 
Really need the plugin log files *(after you encounter episodes have been missed)* to investigate this issue further.

I haven't personally encountered any issues with scrobbling on OpenPHT, but there might be issues with other clients if their progress reporting hasn't been implemented correctly. I could do some tests if you let me know which client *(Plex/Web, Plex Media Player, etc..)* you are watching media with.

**Comment by RoNain** [comment]
Here is the log.
[com.plexapp.plugins.trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/659410/com.plexapp.plugins.trakttv.txt)

I just watch Shameless (US) S07E11 - Happily Ever After on Plex web Version 2.12.5,
"Now Playing" view in Plex/Web appears when I start watching something and disappears when I finish (or stop) watching something but the episode does not appears as watched in Trakt.TV

**Comment by fuzeman** [comment]
I've found some issues with the progress notifications reported by Plex/Web. It appears the "stopped" notification can be randomly sent with a different session key which results in missed scrobbles.

I'll start working on a fix today, will let you know when it's ready to test.

**Comment by fuzeman** [comment]
This issue should be fixed on the development branch ([develop.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip)), will be doing some final testing before release later this week.

**Comment by RoNain** [comment]
Since I've installed the Trakttv.bundle from the development branch, all the episodes I'm watching on plex are correctly marked as watched on Trakt.tv.
Except for a few mini series whose episodes are less than 5 minutes long (Marvel's agents of shield: slingshot) but it's a very minor inconvenience.
Thanks for your work and your reactivity.

**Comment by fuzeman** [comment]
@RoNain Glad to hear that :smile: Took awhile to figure out what was causing this issue.

> Except for a few mini series whose episodes are less than 5 minutes long (Marvel's agents of shield: slingshot) but it's a very minor inconvenience.

I'm guessing these episodes might not be matched correctly in Plex, they would need to be listed as specials with the correct numbering as displayed on: https://trakt.tv/shows/marvel-s-agents-of-s-h-i-e-l-d/seasons/0

**Comment by fuzeman** [comment]
Released in [v1.2.0](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.2.0)
