### ISSUE TITLE
Not syncing views to trakt

### ISSUE THREAD

**Issue by Elliotsmith** [trakt/Plex-Trakt-Scrobbler#374]
For the last few days, no new views are being synced to Trakt.
It will sync newly added TV Shows and Movies, it will also pull down views from Trakt.

But since Wednesday 23rd Nov after 7:38 PM no views seem to be pushed to Trakt.

**Comment by fuzeman** [comment]
Sounds like issue #372, have you updated the plugin to [v1.1.0.7](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.1.0.7)?

**Comment by dgw** [comment]
I updated both of my machins to PMS 1.3.0 after I finished watching Plex content a couple days ago, and found this morning that Trakt wouldn't pick anything up. Have just finished updating the plugin to v1.1.0.7 and restarting one of two servers; it now works again. Will update the other to keep them in sync.

It's a fair guess that this issue duplicates #372 and will be resolved by updating the plugin (don't forget to restart PMS).

**Comment by Elliotsmith** [comment]
Did an update to v1.1.0.7 and it seems to be working again correctly.
Was a little weird as I did the update a while ago, and it still didn't work, then it started but was a little flaky, but now seems to be working consistently.

So yea I think it was updating to v1.1.0.7 fixed it
