### ISSUE TITLE
 [Exception] Unauthorized - "OAuth must be provided"

### ISSUE THREAD

**Issue by IceSentry** [trakt/Plex-Trakt-Scrobbler#375]
Whenever I try to sync I receive this error message. I realised I was using an old version so I upgraded to the most recent version using the unsupportedAppStore method.

I revoked the authorization in trakt and reactivated it then I put the pin in the settings panel for the trakt.tv channel.

Anything I try to do will not work and simply show me this message:
 [Exception] Unauthorized - "OAuth must be provided"

I tried enabling the debug log but for some reason the logs folder doesn't seem to want to show up

Plugin version: 1.1.0.7
Plex Version: 2.11.0 
Windows 10

I tried it in vivaldi and firefox and it does the same thing

I know it worked in the past, but I forgot about it and wanted to update my trakt.tv account recently and I discovered this bug.

**Comment by fuzeman** [comment]
> I tried enabling the debug log but for some reason the logs folder doesn't seem to want to show up

So there is no "Logs" directory at all? would of expected to at least have a "Plex Media Server.log" file in there, see: https://support.plex.tv/hc/en-us/articles/200250417-Plex-Media-Server-Log-Files

Did you change the "The path where local application data is stored" option in Plex Media Server?

-------------

You could also try using the configuration website [here](http://trakt-for-plex.github.io/configuration) to authenticate your Trakt.tv account.

**Comment by IceSentry** [comment]
Yes I totally forgot I changed the path. I found the logs.

I looked at the configuration website and does properly sees my account and says I'm signed in. It was already like I didn't need to do anything.

Which DEBUG option do you want so I can send you the logs

**Comment by fuzeman** [comment]
> I looked at the configuration website and does properly see my account and says I'm signed in. It was already like that I didn't need to do anything.

You could try re-authenticate your Trakt.tv account via the configuration website (e.g. disconnect it with the red `x` button, and then login again).

No idea if this will work, just a guess..

> Which DEBUG option do you want so I can send you the logs?

Just the "Logging - Plugin" and "Logging - Libraries" options set to DEBUG should provide enough detail. Remember to reproduce the issue again after changing this option (run a sync, etc..).

**Comment by Ireney** [comment]
The scenario outlined by IceSentry is exactly the issue I've ran into.  I've used the configuration website to re-authenticate my Trakt.tv account after I previously revoked access. However, I used the edit method to get a new PIN.  The option to disconnect it with the red x button does not appear to work. After clicking that button, the indeterminate progress indicator just spins and nothing happens. However,  using the edit method,  I can see the app been authenticated as it now shows on the "Connected Apps" page on Trakt.  I've also updated the PIN within Plex channel settings.  I see exact same exception ("[Exception] Unauthorized - "OAuth must be provided").

I am using 1.1.0.7-master version of the plugin on server version 1.3.0.3059 hosted on a QNAP NAS.

I've attached the log.  A couple of lines from it seem suspicious to me. I don't understand the system, but perhaps the first line at least suggests that the credentials haven't been updated after the trakt plugin has been re-authenticated?

2016-12-09 15:08:25,768 - plugin.modules.migrations.account (7f1397a23700) :  DEBUG (plugin.modules.migrations.account:205) - Ignoring basic credential update for <TraktAccount username: u'evilbyte'>, already exists (ConstraintError: UNIQUE constraint failed: trakt.credential.basic.account_id)
2016-12-09 15:08:25,770 - plugin.models.m_trakt.account    (7f1397a23700) :  DEBUG (plugin.models.m_trakt.account:88) - Using oauth authorization for <TraktAccount username: u'evilbyte'>

[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/643343/com.plexapp.plugins.trakttv.log.txt)

**Comment by fuzeman** [comment]
@Ireney Just released a fix for that Trakt.tv disconnection issue on the configuration interface, could you try reconnect your Trakt.tv account again? *(disconnect, then connect)*

------

Editing the existing account probably won't work as the configuration interface only applies changes, if the account username is still the same no changes will be applied..

The application will be displayed in the "Connected Apps" page because the authentication is handled client-side, and is then sent to your server (if there is any changes).

**Comment by Ireney** [comment]
@fuzeman The fix did it.  I was able to disconnect, reconnect, and run a full sync successfully. Good work.

**Comment by gdolla** [comment]
That was a fav pic of mine it meant no harm
