### ISSUE TITLE
Not updating viewcount

### ISSUE THREAD

**Issue by AllanMar** [trakt/Plex-Trakt-Scrobbler#376]
I'm wondering if this is a known limitation or bug? I'm trying to switch from Kodi over to Plex and I was hoping trakt would sync my library stats over. It has done a good job with the watched status, but all of the watched media viewcounts are 1 in plex and not the value that is in trakt.

Any suggestions?
I am using v1.1.0.7

**Comment by fuzeman** [comment]
Currently the plugin only imports items as watched, play counts aren't considered at all in the syncing process.

I'll investigate if this could be implemented in the future (by directly modifying the Plex Media Server database), but you likely won't see this available any time soon.
