### ISSUE TITLE
This channel is not responding (Windows)

### ISSUE THREAD

**Issue by tmyflyte** [trakt/Plex-Trakt-Scrobbler#377]
hello I'm having this problem when trying to use the scrobbler. 

traktv scrobbler version 1.1.0.7-master (through webtools utility)
windows 7
plex media server 1.3.0.3059-6277334

what am I doing wrong? :(

**Comment by tmyflyte** [comment]
btw here is the log file

[com.plexapp.plugins.trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/634296/com.plexapp.plugins.trakttv.txt)

**Comment by tmyflyte** [comment]
anyone? please?

**Comment by fuzeman** [comment]
It looks like your Trakt.tv account isn't authenticated anymore, try re-authenticating by entering a new pin into the settings dialog (via Plex/Web) or by using the [configuration site](http://trakt-for-plex.github.io/configuration).

**Comment by rodrigorf** [comment]
Mine is showing this msg too everytime i force any sync, although when i return the page it shows that the syncing operation has sucessfully run.

**Comment by fuzeman** [comment]
@rodrigorf Which client *(Plex/Web, Plex Media Player, etc..)* are you seeing this issue on?

I've fixed an issue on the development branch which caused "not responding" messages on Plex Media Player, some other clients might have similar issues though.

**Comment by rodrigorf** [comment]
Hi fuzeman, thanks for the reply, it was my first download of the plugin so i have downloaded from master, should pull the https://github.com/trakt/Plex-Trakt-Scrobbler/tree/develop version right? I'll give it a try and reply to you soon.  :)

**Comment by rodrigorf** [comment]
It worked @fuzeman, the msg "the channel is not responding" its not showing anymore after syncing.

**Comment by fuzeman** [comment]
Released in [v1.2.0](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.2.0)

**Comment by fuzeman** [comment]
@smithinoz Interesting.. I'll do some more testing with local connections to Plex Media Server later today.
