### ISSUE TITLE
Scrobble error

### ISSUE THREAD

**Issue by Bazzu85** [trakt/Plex-Trakt-Scrobbler#383]
Hi, i'm using last version updated from unsupported web store.

From days (maybe when I installed last version) I continually see this type of message:

[38 minutes ago] ConnectionError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /scrobble/pause (Caused by ProtocolError('Connection aborted.', error(10054, "Connessione in corso interrotta forzatamente dall'host remoto")))

suggestions?
have to downgrade to other versions?

**Comment by OmgImAlexis** [comment]
I'm getting the same issue.
```
[3 days ago] ConnectionError: HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /sync/collection (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Read timed out. (read timeout=24)",))
```

**Comment by Kylapaallikko** [comment]
I have had this same issue at least for two weeks now. `1.1.0.7-master`

`[Exception]
 HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Max retries exceeded with url: /scrobble/stop (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api-v2launch.trakt.tv', port=443): Read timed out. (read timeout=24)",))`

`[Exception] HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/1/store/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fe7f4853550>: Failed to establish a new connection: [Errno -2] Name or service not known',))`

**Comment by fuzeman** [comment]
**`Connection aborted`**

Not sure what is causing these errors yet, will be doing some further testing later this week.

------------

**`The read operation timed out` or `Read timed out.`**

These errors can be returned by the Trakt.tv API for no apparent reason, usually they can be ignored as the actions are still being applied to your profile anyway..

--------------

There is a chance these connection issues are a bug in a recent update to [requests](https://github.com/kennethreitz/requests) or [urllib3](https://github.com/shazow/urllib3). I currently can't test past versions of these libraries though as I haven't personally experienced any of these connection issues.

Let me know if you find previous versions of the plugin to be more reliable, might be able to compare the two versions of these libraries and find the issue.

**Comment by OmgImAlexis** [comment]
The bug shouldn't be in either of those as I'm a dev for Medusa/Sickrage and we use them quite a bit, I haven't had a single user report an issue with either library lately and I'm guessing we'd get a few more reports than you.

The older version before adding in multiple users had the same issue for me I just didn't realise there was a Github repo to report them to until recently.

**Comment by fuzeman** [comment]
@OmgImAlexis Well it's either an issue with your Internet connection, CloudFlare, Trakt.tv API, or one of the libraries or extensions we use to perform HTTP(S) requests. Read timeout errors have been happening for quite a long time (#185, #226) with no obvious cause.

FYI, It appears `Read timed out.` errors for the Trakt.tv API have been encountered in Medusa as well: https://github.com/pymedusa/Medusa/issues/954, https://github.com/pymedusa/Medusa/issues/928

-----------------------

The `Connection aborted.` exception is a new error that I'm looking into, currently thinking it might be an issue with the handling of keep-alive connections...

**Comment by OmgImAlexis** [comment]
@ratoaq2 @fernandog @p0psicles did we workout the issue with Trakt and other services having timeout issues?

**Comment by fuzeman** [comment]
Could users that experience `Connection aborted` or `Read timed out.` errors install the development branch ([develop.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip)) and test the plugin with the advanced configuration parameters provided below.

Please let me know if you find certain configuration parameters fixes your connection issues, will update the plugin defaults if this is the case.

----------

Advanced configuration parameters are defined in the file at: *(create the file if it doesn't exist)*:
```
Plug-in Support\Data\com.plexapp.plugins.trakttv\advanced.ini
```
Once you've updated that file, restart Plex Media Server to apply the changes.

-------------

I would recommend testing each group of configuration parameters individually at first, feel free to try other combinations of parameters if nothing appears to be working though.

**Increase timeouts**
```
[trakt]
connect_timeout=15
read_timeout=60
```

**Disable keep-alive**
```
[trakt]
keep_alive=false
```

**Switch to HTTP connections**
```
[trakt]
protocol=http
```

**Comment by Bazzu85** [comment]
with last update the chanel seems to work.
but I have issue with a newly added secondary account. all configured with http://trakt-for-plex.github.io/ and the 2 users as displayed. when entering my GF user say "chanel not responding".
suggestions?

**Comment by fuzeman** [comment]
@Bazzu85 Looks like you haven't linked a Plex account to your new user *(you should see a green tick, instead of a gray minus sign)*, the scrobbling rules should also be changed to look like:
![](https://i.imgur.com/ZRMIoJS.png)

If you are still experiencing issues opening the sync menu, post the latest plugin log file. *(see [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files) for details)*

**Comment by fuzeman** [comment]
@Bazzu85 Switch the Plex authentication mode to "Home" in the configuration interface:
![](https://i.imgur.com/OzUTAfN.png)

**Comment by Bazzu85** [comment]
thx it's working!

**Comment by Bazzu85** [comment]
so..
here's last sync:
![2016-12-29_182734](https://cloud.githubusercontent.com/assets/7345587/21549717/7fc72a84-cdf4-11e6-941c-609107b63a63.jpg)

**Comment by fuzeman** [comment]
@Bazzu85 I'm not exactly sure what is causing that error as it's basically just a general network error, it could an issue with your Internet connection, Trakt.tv API, or anything in between.

Could you try the "Disable keep-alive" configuration mentioned in https://github.com/trakt/Plex-Trakt-Scrobbler/issues/383#issuecomment-269425600? there is a chance it's related to dropped connections due to keep-alive session timeouts.

**Comment by Bazzu85** [comment]
ok. after I woke up I waked the server and auto sync is started giving the error.
I tried to disable keep alive
![2016-12-30_090030](https://cloud.githubusercontent.com/assets/7345587/21561584/9aeca6ac-ce6e-11e6-8df3-2ada2245fb3c.jpg)
![2016-12-30_090038](https://cloud.githubusercontent.com/assets/7345587/21561585/9cc5884a-ce6e-11e6-8423-86e1464b7140.jpg)
and restarted plex. same error.
I have to delete some chace file?

**Comment by Bazzu85** [comment]
so...
using the develop versione and disabling keep alive the problem doesn't seem to occur..

**Comment by fuzeman** [comment]
@Bazzu85 
> but is normal that my account need about 10 minutes? with kodi required about max 2 minutes..

Disabling keep-alive has probably slowed things down a bit, the plugin possibly needs some more tweaks to how it handles memory usage vs paging data to disk as well *(memory usage doesn't scale based on the available system memory currently)*.

I'll be working on more syncing performance improvements in 2017 *(possibly a complete rebuild)*, so will hopefully get these sync times down more. 😃 

@Bazzu85 
> so...
> using the develop versione and disabling keep alive the problem doesn't seem to occur..

Interesting... This probably means there is an issue with keep-alive in [requests](https://github.com/kennethreitz/requests) or [urllib3](https://github.com/shazow/urllib3).

Please let me know if you see any connection errors again.

**Comment by Bazzu85** [comment]
ok! thanks @fuzeman 

a question. when the plugin do a automatic sync time based, can I do only a push instead of a full?

**Comment by fuzeman** [comment]
@Bazzu85 Currently the automatic syncing mode can't be changed, will consider adding that in a future update.
