### ISSUE TITLE
Syncing

### ISSUE THREAD

**Issue by nanohits** [trakt/Plex-Trakt-Scrobbler#388]
How often does this plugin sync up with trakt? I have it set to Push to Trakt but when I go to Plex, it says last synced 20 hours ago. So when I watch a show or get a new show, does it only update once a day? I know my watched shows up right away but my collection doesnt seem to show up right away. Wonder if I am missing something in the config?

**Comment by fuzeman** [comment]
It depends how you've configured the plugin.

 - Enabling `Sync - Run after library updates` will trigger a full sync after your Plex libraries have been updated (new items added, re-scanned, etc..)
 - `Sync - Run every` will trigger a full sync at the specified interval
 - `Sync - Defer until server is idle` will defer syncs *(for up to 12 hours)* until your server isn't streaming any media to clients
