### ISSUE TITLE
Trakt not syncing with Plex since couple of weeks

### ISSUE THREAD

**Issue by xp0z3d** [trakt/Plex-Trakt-Scrobbler#389]
I am using current Plex server Version 1.3.3.3148  on Mac OS. I had Trakt plug in installed and it was working like a charm till December 14th but since then it has not synced my watch history from Plex. I today even reinstalled Trakt plug in once more to see if I can make it work but no success. 

What can be done to fix it?

**Comment by gdolla** [comment]
Since somebody birthday

**Comment by fuzeman** [comment]
Could you provide the latest plugin log file? see this page for more details: https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files

**Comment by xp0z3d** [comment]
After re-installing yesterday, I forced sync it, and history showed up. 
Here is log http://pastebin.com/rT0huCgp
I do not know what version I have. How can I check?

**Comment by fuzeman** [comment]
Yeah, you've got an old version of the plugin *(can also be found in Plex/Web at `Channels -> Trakt.tv -> About`)*:
```
Current Version: v1.1.0.6-master
```

Update the plugin either via WebTools / UASv2 or manually as described in https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Installation
