### ISSUE TITLE
Plugin still isn't visible

### ISSUE THREAD

**Issue by Sapking** [trakt/Plex-Trakt-Scrobbler#395]
Hi,

I reinstalled the new version but I still can't see it on my Plex.
Please find log attached.

Thanks for your help.

[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/721147/com.plexapp.plugins.trakttv.log.txt)

**Comment by fuzeman** [comment]
```
Server version is 0.9.16.3
```

Not sure if the plugin still works with this *very* old version of Plex Media Server. *(latest release is v1.3.3)*

----------

I could try get the plugin working on Plex Media Server v0.9.16.3 again, but updating to the latest version of PMS is probably your best bet at resolving this issue though.

**Comment by OldMike** [comment]
It remains invisible with Version 1.3.3.3148

**Comment by Sapking** [comment]
It looks like Plex latest working version on my Synology NAS was 0.9.16.6 so I'm not going to be able to update to the latest version.

Thank you very much for your help

**Comment by fuzeman** [comment]
> It looks like Plex latest working version on my Synology NAS was 0.9.16.6 so I'm not going to be able to update to the latest version.

Didn't realize Plex dropped support for some NAS devices, guessing you are referring to [this](https://forums.plex.tv/discussion/212842/armv5-powerpc-and-readynas-ros4-no-longer-supported-starting-with-plex-media-server-0-9-17-0)?

---------

Will try do some tests with PMS v0.9.16.6 later this week, hopefully we can bring back support :smiley:

**Comment by fuzeman** [comment]
The plugin does startup correctly with PMS v0.9.16.6 on Ubuntu 16.04 (64-bit), so there must be something else more specific to your device or setup that is causing this issue.

----------

Which Synology NAS do you have? and have you corrected the plugin permissions as described [here](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Installation%20-%20Synology#fix-permissions)?

Attaching the `Plex Media Server.log` file might help me identify the issue as well.

**Comment by Sapking** [comment]
I didn't know that Plex had dropped support for some NAS devices either.
Off the top of my head I think it is DS212j. 
I'll check the plugin's permissions later at home.

Thanks for your help.

**Comment by Sapking** [comment]
Now it's working thanks to your hint about plugin permissions.

Thanks Fuzeman for your help
