### ISSUE TITLE
Intermittent Authentication Errors

### ISSUE THREAD

**Issue by alibolcakan** [trakt/Plex-Trakt-Scrobbler#396]
Hi,

I had to reinstall my PMS and when I reinstalled Webtools and Trakt, the plugin was never authenticated. I followed the guide, reinstalled 3 times (restarting the server after each new install etc.) but I still doesn't work. Below's my full logs for the last two days.

thanks in advance,

[Trakt logs.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/files/722719/Trakt.logs.zip)

**Comment by fuzeman** [comment]
Try the latest development version of the plugin: [develop.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip)
