### ISSUE TITLE
Critical Error: Unable to import the playhouse.apsw_ext library

### ISSUE THREAD

**Issue by Skaronator** [trakt/Plex-Trakt-Scrobbler#398]
Hey,

just installed this plugin twice and still have the following error: `Critical Error: Unable to import the playhouse.apsw_ext library (Failed to map segment from shared object: operation not permitted)`

![image](https://cloud.githubusercontent.com/assets/2886913/22251698/07cff166-e24c-11e6-94fe-033124bded71.png)

I'm on Debian 8 (OpenMediaVault installation) with latest PMS.

Hardware: Intel G4400 (Skylake), 8GB RAM, 12TB Raid6

**Comment by fuzeman** [comment]
Try the fix detailed here: https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Installation%20-%20Open%20Media%20Vault#fix-error-failed-to-map-segment-from-shared-object-operation-not-permitted

**Comment by Skaronator** [comment]
Oh snap! I was searching on google and in the issues here but not in the Github wiki.

**Comment by Skaronator** [comment]
Worked, thanks.
