### ISSUE TITLE
Movie metadata is missing from most collected movies.

### ISSUE THREAD

**Issue by wolfeinkc** [trakt/Plex-Trakt-Scrobbler#400]
I am using the Trakt API to pull my movie collection including the metadata for a project, but the metadata is missing from over 90% of the movies.
I used the Plex2CSV plugin, and it shows all the metadata when I run a Movie report.
Is there a way to get the plugin to push the metadata for the remaining movies?

**Comment by fuzeman** [comment]
I'm guessing you are talking about the resolution, audio channels and audio codec parameters?

It looks like the plugin won't update the collection metadata if the movie or episode has already been marked as collected on your Trakt.tv profile. Currently the only way to fix this would be removing everything from your Trakt.tv collection, and run another sync from the plugin.

If items aren't being marked as collected at all, this usually indicates the metadata agent you are using isn't supported.

--------------

I'll have a look to see if collection metadata syncing can be improved, it might need to be delayed until the sync overhaul later this year though...

**Comment by wolfeinkc** [comment]
I'll give that a try, thanks!

**Comment by dgw** [comment]
@fuzeman I hope it's OK that I'm commenting here instead of opening a new ticket, because what I'm asking is related.

I see that the collection metadata went live, but I'm at a loss how to import metadata for items already in my collection. Am I correct that the Plex plugin cannot add metadata to already-collected items? The collection timestamps in my library are meaningful, and using the workaround you mentioned would throw them away.

**Comment by rectifyer** [comment]
I'm still investigating more on my end, but I've noticed that movies aren't sending metadata for me, but episodes are. I'll report back when I find more info after looking the logs.

The Trakt API can "update" metadata if the same item is sent. Probably requires a Plex plugin update, but just wanted to mention that. http://docs.trakt.apiary.io/#reference/sync/add-to-collection

**Comment by fuzeman** [comment]
@dgw Yeah, there are definitely some issues with the current collection syncing logic.

I'm currently working on a complete overhaul of the syncing system which aims to resolve a lot of these syncing issues and improve performance. Will probably be a few months away though...

----------

@rectifyer 
> I'm still investigating more on my end, but I've noticed that movies aren't sending metadata for me, but episodes are. I'll report back when I find more info after looking the logs.

Hmm, it looks like movie metadata is being added to my profile.. Not sure what would cause that issue.

**Comment by wolfeinkc** [comment]
I had to go through and remove all my movies from my collection.  Then the Plex Trakt plugin ran and put everything back.

I went to my collection, selected movies, and started with the last page and ran this in the browser console page by page:
$(“.grid-item”).each( function( index) {
actionWatch($(this), “collect”, true)
});

$(“.pagination-top .page.active a”)[0].click();
