### ISSUE TITLE
Full Sync Duration

### ISSUE THREAD

**Issue by Bazzu85** [trakt/Plex-Trakt-Scrobbler#401]
Hi,

I noticed a fact about the duration of a full sync.

If I activate the clean collection flag, full sync is 1 minute long. if I don't activate the flag (like everyday) it takes 15/20 minutes. is this normal?

thx

**Comment by Bazzu85** [comment]
news: now even with clean collection flagged sync duration is 15/20 minutes.
so I can't figure how the 1 minute full sync are worked.. -.-

**Comment by fuzeman** [comment]
Syncs will be faster if no changes have been made to your Trakt.tv profile. *(as we won't need to refresh the Trakt.tv account cache)*

I don't believe the `Clean collection` option is directly causing this, it might be just that it makes changes to your profile which causes a cache refresh in the next sync.
