### ISSUE TITLE
[Exception] 'module' object has no attribute 'sslwrap'

### ISSUE THREAD

**Issue by alias1** [trakt/Plex-Trakt-Scrobbler#404]
Getting this error while trying to sync. Looking at the about, i'm running: `v1.3.1`.

Have had this plugin installed forever, but it seems to have been broken for a while, only just manually updated it to the latest today, still getting this issue.

**Comment by alias1** [comment]
I think it may be related to this: https://github.com/gevent/gevent/issues/477

**Comment by fuzeman** [comment]
Try this: http://forums.plex.tv/discussion/comment/1337267/#Comment_1337267

The paths listed there might be slightly different depending on your system, let me know if you have trouble finding the files.

**Comment by alias1** [comment]
No luck unfortunately. Changed the [same error I was getting with WebTools](https://github.com/ukdtom/WebTools.bundle/issues/259#issuecomment-276794311), but didn't resolve things.
