### ISSUE TITLE
plug-in not appearing 

### ISSUE THREAD

**Issue by buzzawak** [trakt/Plex-Trakt-Scrobbler#410]
plug-in not appearing 
I have turned on debugging and have attached the log.

Any help is appreciated
[com.plexapp.plugins.trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/762566/com.plexapp.plugins.trakttv.txt)
.

**Comment by fuzeman** [comment]
```
ImportError: No module named plugin.core.environment
```

Doesn't look like the plugin has been installed correctly, or Plex Media Server attempted to start the plugin before it was finished being copied into the `Plug-ins` directory.

-------

Try restarting Plex Media Server, or reinstall the plugin with the following steps:
1. Shutdown Plex Media Server
2. Delete the existing `Plug-ins/Trakttv.bundle` directory
3. Copy `Trakttv.bundle` from zip file into the `Plug-ins` directory
4. Start Plex Media Server

**Comment by joaoarthur** [comment]
Hi, i tried to install both ways, "Unsupported AppStore" and "Manual" but neither one or another worked.

In fact, neither the log "com.plexapp.plugins.trakttv.log" was created.

I'm using a "Linux osmc 4.4.27-7-osmc  armv7l GNU/Linux" and i already followed the owner/permissions fix instruction.

So, is there anything that i can do so solve it?

**Comment by joaoarthur** [comment]
Any one?

**Comment by fuzeman** [comment]
Attaching the `Plex Media Server.log` file a few minutes after restarting Plex Media Server might give me some clues.

I haven't tested the plugin with PMS on OSMC, will try do some tests with OSMC later this week.

**Comment by joaoarthur** [comment]
Thanks for the help, Fuzeman.

Ps: this plugin already worked well with PMS on osmc, but as was in older versions of OS, PMS and Plugin, i don't know what can be chance.

[Plex Media Server.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/820036/Plex.Media.Server.txt)

**Comment by fuzeman** [comment]
The `Plex Media Server.txt` log file you attached has no mention of either the `Trakttv.bundle` or `WebTools.bundle` plugins, so my guess is the plugins haven't been installed into the correct directory or have incorrect permissions.

It appears the server is looking for plugins in:
```
/home/osmc/Library/Application Support/Plex Media Server/Plug-ins
```

Is this where you installed the plugins? which permissions have been set on these directories?

**Comment by joaoarthur** [comment]
Thanks @fuzeman! It was exactly that. I haved installed the trakt plugin under the path `/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/` as the instalation guide told to do and it worked well before. 
But as i've changed the way i'm installing PMS, the home PMS directory changes to and i didn't notice it.

So when i copy those plugins to the right directory, both os them started work well.

Ps: Sorry for the noob question.
