### ISSUE TITLE
EAC3 audio codec

### ISSUE THREAD

**Issue by rectifyer** [trakt/Plex-Trakt-Scrobbler#412]
I noticed an audio codec called **EAC3** on one of my media items, and that isn't being sent to Trakt. If possible, it would be great to simply use `ac3` when sending the collection metadata if this audio codec is used.

**Comment by fuzeman** [comment]
The latest development branch commit should map `eac3` to [`dolby_digital_plus`](https://en.wikipedia.org/wiki/Dolby_Digital_Plus). Will include this in a new stable release today.

**Comment by rectifyer** [comment]
Awesome, thank you!

**Comment by fuzeman** [comment]
Released in [v1.3.2](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.3.2)
