### ISSUE TITLE
Not Scrobbling/Syncing

### ISSUE THREAD

**Issue by KevinH5** [trakt/Plex-Trakt-Scrobbler#414]
After I recently purchased Plex Pass and updated Plex to the latest version, the Scrobbler no longer pushes anything to Trakt. I have uninstalled the plugin and reinstalled it and verified settings and that doesn't seem to be the problem. Anyone else have this issue?
[scrobble.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/785603/scrobble.txt)

**Comment by fuzeman** [comment]
Looks like the plugin started up without any issues, the Trakt.tv API is responding with this though:
```
Request failed: "POST /scrobble/start" - 404: "Method exists, but no record found" (Not Found)
```

This indicates you are watching something that can't be found on Trakt.tv, can't confirm if this is correct as the log file doesn't show what you were watching.

Are all shows/movies failing to scrobble? or is it a specific show/movie that isn't working?

-----------

Posting a log file with debug logging will help me identify the issue, see [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files) for more details.

**Comment by KevinH5** [comment]
Sorry about the delay.
All movies and tv shows were not working but I went in and unselected the top option in the settings then selected it again and now it all works. 

Thanks.
