### ISSUE TITLE
No playback progress in Trakt

### ISSUE THREAD

**Issue by RikuXan** [trakt/Plex-Trakt-Scrobbler#417]
My Trakt for Plex plugin doesn't seem to inform Trakt when I start watching an episode, because I'm not getting the playback progress bar (see image) to appear on my profile.
![trakt_progress](https://cloud.githubusercontent.com/assets/3399940/23236461/9d5bd230-f959-11e6-9370-d2cd9566e032.PNG)
I have set `Sync - Playback Progress` to `Synchronize`, but the bar does not appear and the episodes are simply marked as watched about 5 minutes after I'm done with them in Plex. Is there something wrong with my setup, or does Plex-Trakt-Scrobbler not support this?

**Comment by fuzeman** [comment]
The real-time watching status on your profile is completely unrelated to syncs (and the `Sync - Playback Progress` option).

It sounds like you are having issues with real-time scrobbling. Firstly ensure you are on the latest version of the plugin ([v1.3.2](https://github.com/trakt/Plex-Trakt-Scrobbler/releases/tag/v1.3.2)), if you are already running the latest version of the plugin, post the latest plugin log file after watching something in Plex. *(see [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Log-files) for more details)*

**Comment by RikuXan** [comment]
Thanks for your help. I thought I set it up to auto-update but was on version 1.1.0.
