### ISSUE TITLE
I’m trying to install Trakt.tv onto my plex server which is running on Seagate Personal Cloud

### ISSUE THREAD

**Issue by Tdotsown** [trakt/Plex-Trakt-Scrobbler#418]
I’m trying to install Trakt.tv onto my plex server which is running on Seagate Personal Cloud

**Comment by fuzeman** [comment]
Looks like root access is probably required to install third-party plugins on Seagate Personal Cloud devices, see these threads:
 - https://forums.plex.tv/discussion/183152/adding-plugins-plex-on-seagate-personal-cloud
 - https://forums.plex.tv/discussion/174083/locating-plex-plugin-folder-on-seagate-personal-cloud

This is really an issue that only Plex can resolve.
