### ISSUE TITLE
Barely scrobbling the past 2-3 weeks..

### ISSUE THREAD

**Issue by JourneyOver** [trakt/Plex-Trakt-Scrobbler#426]
Trakt plugin version -- 1.3.2
Operating System -- Windows 10 x64 Pro
Plex Media Server -- Version 1.4.4.3495
Plex Client -- Using web browser Version 3.0.1

Dunno exactly what is going on with this plugin but for the past 2-3 weeks now this plugin has barely been working. Sometimes I'll watch a show and the scrobble will happen which is great, but then 90% of the time I'm manually having to go and mark the episode (or movie) watched on trakt because no matter what I do the plugin will not scrobble the episode.

It doesn't even make a difference if I go into the sync thing on the plugin page and do a full/quick sync or a push even as it just ends up saying that it was successful in the end even though it still had not pushed anything to trakt at all, even if I wait an hour or two and try again or just let the scrobbler do it's own thing since I do have it set to run a sync every 15 minutes it still won't push anything at all to trakt in the end so I end up having to go and mark the episode/movie manually. 

Like I said this happens 90% of the time, the other 10% it seems to scrobble things correctly..
Have not changed anything or downloaded anything on my computer that would end up causing this.

These are the latest logs:
https://paste.ee/p/4GhRX#section0
https://paste.ee/p/4GhRX#section1

**Comment by JourneyOver** [comment]
@fuzeman any help on this?? ...

Two new logs, this time while running all logging option at debug status..
https://paste.ee/p/d7GTF#section0
https://paste.ee/p/d7GTF#section1

**Comment by fuzeman** [comment]
```
Unsupported metadata agent: com.plexapp.agents.tvmaze
```

We don't support this metadata agent yet, see [this page](https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/FAQ---General#3-which-metadata-agents-are-supported) for a list of supported metadata agents.

TVmaze could be supported with mappings (similar to AniDB), but this will require a fair bit of setup to get working.

**Comment by JourneyOver** [comment]
@fuzeman Oh well that's lame :c with how the TVDB has been acting the past few weeks I've been wanting to switch away from the TVDB metadata agent plugin.. 

So well guess now I want to call for getting support for the TVmaze metadata agent..

**Comment by fuzeman** [comment]
I've created issue https://github.com/trakt/Plex-Trakt-Scrobbler/issues/430 for this feature request.
