### ISSUE TITLE
Push error "MovieMatch has no attribute identifiiers"

### ISSUE THREAD

**Issue by miracle152004** [trakt/Plex-Trakt-Scrobbler#427]
Hi,

I get the following error on sancing.
I can understand that the sync cannot add the file on which this is happening, but nothing is synced.
It should still sync the other files.
Also there should be a way for looking up which entry is responsible for this error.

Thans

best regards
miracle152004

**Comment by fuzeman** [comment]
Duplicate of https://github.com/trakt/Plex-Trakt-Scrobbler/issues/416, please install the [develop.zip](https://github.com/trakt/Plex-Trakt-Scrobbler/archive/develop.zip) branch for a fix. Will try get this into a stable release this week.
