### ISSUE TITLE
Sync with Plex Cloud

### ISSUE THREAD

**Issue by HeikoBornholdt** [trakt/Plex-Trakt-Scrobbler#439]
Can I use this plugin to sync watched movies/tv shows between plex and trakt?

**Comment by RolluS** [comment]
Unfortunatly Plex CLoud does not support Channels (yet?).

 Is anybody aware of any manual method to push Plex CLoud to Trakt please?

**Comment by bassrock** [comment]
Couldn't we use a third party app that runs and uses the basic plex apis? Then it could become plex agnostic in a way and could be used with plex servers where you can't control the channels.

**Comment by mikaelf** [comment]
I'm also looking for a solution to this issue.

**Comment by soofuzz** [comment]
you could use the kodi plugins for plex and trakt. that seems to work

**Comment by Miladiir** [comment]
@soofuzz Only works on platforms where Kodi is available. My TV for example has an app for Plex, but will probably never get Kodi.
Plex should allow plugins on Plex Cloud. There is probably nothing that Trakt can do until they do.

**Comment by soofuzz** [comment]
@Miladiir yep basically unless someone checks for api availability for plex cloud to see if playback stats can be pinged for.

**Comment by OskarStark** [comment]
any news @soofuzz ?

**Comment by soofuzz** [comment]
@OskarStark none yet. ive been busy with some exams and havent had the time to look into it :( but when i did i hit a deadend
