### ISSUE TITLE
Trakt.tv Scrobbler : The read operation timed out 

### ISSUE THREAD

**Issue by Debojit** [trakt/Plex-Trakt-Scrobbler#442]
All sync attempts end with the error message: The read operation timed out. Latest version of the plugin installed both manually and with WebTools on Plex 1.5.5.3634

[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/993278/com.plexapp.plugins.trakttv.log.txt)

**Comment by RoNain** [comment]
Same here on a plex 1.5.5.3634 installed on a Western Digital PR2100 NAS (Linux).
Here is the log file
[com.plexapp.plugins.trakttv.log.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/993871/com.plexapp.plugins.trakttv.log.txt)

**Comment by TeknoGodz** [comment]
Same here, maybe the update screwed it up?? Trakt.tv is still up... Idk

**Comment by DeviantEng** [comment]
Pretty sure it's a trakt issue.

```
2017-05-11 18:05:16,216 - plugin.api.core.manager          (7ff6c6e6b700) :  ERROR (plugin.api.core.manager:1185) - Exception raised while handling request 'account.update': MaxRetryError: HTTPSConnectionPool(host='api.trakt.tv', port=443): Max retries exceeded with url: /auth/login (Caused by ReadTimeoutError("HTTPSConnectionPool(host='api.trakt.tv', port=443): Read timed out. (read timeout=24)"))
```

Timed out trying to reach api.trakt.tv on port 443 (aka, https://api.trakt.tv), which if I try to browse in Chrome, I get an error 504 with Cloudflare.

Trakt acknowledge some performance issues via Facebook about 14 hours ago, but nothing specifically about the api.

**Comment by Debojit** [comment]
Yeah, looks like it's working fine now.
