### ISSUE TITLE
Videos not being scrobbled recently

### ISSUE THREAD

**Issue by user020** [trakt/Plex-Trakt-Scrobbler#447]
Scrobbling to Trakt has worked fine for me since I first started using Plex over a year ago but no TV episodes have scrobbled at all over the last 10 days or so. I'm running PMS 1.7.3.3937 on Win7 x64 SP1. Rolling back to 1.7.2.3878 or re-authenticating in Plex Web and http://trakt-for-plex.github.io/configuration didn't make any difference. Clients are Plex 6.1.1.656 on Android and Plex Media Player 1.3.3/1.3.4 on Win7 x64 SP1. Please find my com.plexapp.plugins.trakttv.log attached taken straight after finishing an episode.

[com.plexapp.plugins.trakttv.txt](https://github.com/trakt/Plex-Trakt-Scrobbler/files/1091151/com.plexapp.plugins.trakttv.txt)

**Comment by piret28** [comment]
hi guys!!i dont know where to write...i download some days ago trakt and it doesnt open!!of course exodus doesnt authorize now trakt....thats why i try to work trakt without exodus involved...i spoke with support of trakt and they help me giving instructions...when i download it and try to open i couldnt...

**Comment by alfgut** [comment]
Same thing happening to me! Last successful sync was on the 13th of June. When I go to the plugin web interface it does not show up any errors...

**Comment by davemikolaj** [comment]
This also affected me - Downloading the latest version and authorising the application via pin rather than the old login method sync'd fine. This caught up everything since 13th June.

Must be a change in the authorisation or the way Trakt works.

**Comment by user020** [comment]
Removing the Plex-Trakt-Scrobbler plugin, downloading the latest version, reinstalling it then re-authorising via PIN worked for me too. Looks like I was running an old version of the plugin and 'Check for updates' in Plex web -> Channels wasn't actually picking up the latest version. Many thanks!
