### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by rdybro** [trakt/Plex-Trakt-Scrobbler#473]
Hi. I am getting an error when trying to pull information from Trakt through my newly installed Plex plug-in. It is running inside a Docker, using the official Plex Docker-image.

It seems to be because of an expired SSL certificate for https://sentry.skipthe.net/api/1/store/. I have no idea what that URL are for, and why the plug-in is calling it, but it is coming up in the log, and I can verify in my browser that the certificate has expired on the 7th of November.

I can provide log-file if necessary.

**Comment by rectifyer** [comment]
The SSL certificate has been updated on this domain so it should resolve that error.
