### ISSUE TITLE
sentry [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

### ISSUE THREAD

**Issue by damien990** [trakt/Plex-Trakt-Scrobbler#474]
This is my issue getting ssl error.
 (Trakt account hasn't been authenticated).
thanks

log attached
[Plex Media Server.log](https://github.com/trakt/Plex-Trakt-Scrobbler/files/1524103/Plex.Media.Server.log)

**Comment by rdybro** [comment]
I am having the same issue. It is logged [here](https://github.com/trakt/Plex-Trakt-Scrobbler/issues/473).

**Comment by ArthurZey** [comment]
<img width="603" alt="screenshot 2017-12-05 11 35 07" src="https://user-images.githubusercontent.com/1697359/33627659-1376d336-d9b3-11e7-8b7f-9c98ecc9c583.png">
<img width="447" alt="screenshot 2017-12-05 11 49 45" src="https://user-images.githubusercontent.com/1697359/33627660-138ce414-d9b3-11e7-8bcc-be19257ce87f.png">

I'm also having the same issue:

Getting the following error message in the Trakt channel in Plex:

[Sentry] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590) (code: 1)

Running version 1.3.2 on Plex 1.10.0.4523 on Synology 1813+ running DSM 5.2-5644 Update 5 with Python 2.7.13.

Steps:
- Stopped Plex
- Removed `/volume1/Plex/Library/Application Support/Plex Media Server/Plug-ins/Trakttv.bundle`
- Extracted `Trakttv.bundle` into same directory from https://github.com/trakt/Plex-Trakt-Scrobbler/archive/master.zip based on installation instructions: https://github.com/trakt/Plex-Trakt-Scrobbler/wiki/Installation---Synology
- `chown -R plex:users Trakttv.bundle`
- `chmod -R 777 Trakttv.bundle`
- Started Plex
- Configured the channel, including authenticating with the PIN (though it somehow remembered a bunch of my settings; not sure where that was being kept)
- Saw the error message
- Currently still syncing

Is the problem possibly the too-permissive permissions on all the files in the bundle?
[com.plexapp.plugins.trakttv.log](https://github.com/trakt/Plex-Trakt-Scrobbler/files/1532689/com.plexapp.plugins.trakttv.log)

**Comment by ArthurZey** [comment]
For what it's worth, it looks like the pull worked for watched status. (That's all I'm doing by way of sync between Trakt and Plex.)

**Comment by rectifyer** [comment]
The SSL certificate has been updated on this domain so it should resolve that error.

**Comment by ewan2395** [comment]
sentry.skipthe.net is refusing connections - #481

**Comment by animosity22** [comment]
@rectifyer  - is skipthe.net coming back or down for good?
