### ISSUE TITLE
Plug-in stops working

### ISSUE THREAD

**Issue by Eric2203** [trakt/Plex-Trakt-Scrobbler#481]
I've been having serious issues with the Plex plugin for a little over a week. It seems to work for a while, then stops working and disappears from the plugins list in the Plex interface. Restarting PMS fixes it for a while, but then it stops again.

PMS version: 1.10.1.4602
Plex-Trakt-Scrobbler version: 1.3.2 (latest Stable)

I see this in the log (which I've now set to debug):

`2018-02-06 08:14:21,312 - sentry.errors (1690) : ERROR (sentry.errors:671) - Sentry responded with an error: MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/1/store/ (Caused by ConnectTimeoutError('Connection to sentry.skipthe.net timed out. (connect timeout=1)')) (url: https://sentry.skipthe.net/api/1/store/)
Traceback (most recent call last):
File "C:\Users\eric2\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\transport\threaded_requests.py", line 26, in send_sync
super(ThreadedRequestsHTTPTransport, self).send(data, headers)
File "C:\Users\eric2\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\transport\requests.py", line 41, in send
timeout=self.timeout
File "C:\Users\eric2\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 110, in post
return request('post', url, data=data, json=json, **kwargs)
File "C:\Users\eric2\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\api.py", line 56, in request
return session.request(method=method, url=url, **kwargs)
File "C:\Users\eric2\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 488, in request
resp = self.send(prep, **send_kwargs)
File "C:\Users\eric2\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\raven\breadcrumbs.py", line 297, in send
resp = real_send(self, request, *args, **kwargs)
File "C:\Users\eric2\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\sessions.py", line 609, in send
r = adapter.send(request, **kwargs)
File "C:\Users\eric2\AppData\Local\Plex Media Server\Plug-ins\Trakttv.bundle\Contents\Libraries\Shared\requests\adapters.py", line 479, in send
raise ConnectTimeout(e, request=request)
ConnectTimeout: MaxRetryError: HTTPSConnectionPool(host='sentry.skipthe.net', port=443): Max retries exceeded with url: /api/1/store/ (Caused by ConnectTimeoutError('Connection to sentry.skipthe.net timed out. (connect timeout=1)'))`

And:

`2018-02-06 08:14:32,686 - root (2358) : DEBUG (root:265) - Exception in I/O handler for fd 1604
Traceback (most recent call last):
File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f54242b6b\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\ioloop.py", line 256, in start
self._handlers[fd](fd, events)
File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f54242b6b\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\stack_context.py", line 128, in wrapped
callback(*args, **kwargs)
File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-f54242b6b\Framework.bundle\Contents\Resources\Platforms\Shared\Libraries\tornado\httpserver.py", line 219, in _handle_events
connection, address = self._socket.accept()
File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\socket.py", line 206, in accept
sock, addr = self._sock.accept()
error: [Errno 10035] A non-blocking socket operation could not be completed immediately`

Any help is appreciated.

**Comment by Eric2203** [comment]
Hello? Anyone reading this? It's still happening. This is what happens when it dies (after the messages I provided in my previous message):

`2018-02-14 15:49:41,635 - plugin.managers.core.base        (21d4) :  DEBUG (plugin.managers.core.base:1147) - or_create() - ex: IntegrityError('ConstraintError: UNIQUE constraint failed: message.type, message.exception_hash',)`

**Comment by animosity22** [comment]
Seems to be dead still. What is sentry.skipthe.net ? I can't auth on any of my systems anymore :(

**Comment by GenerlAce** [comment]
same here. this is what i get no matter what i do. does anyone have a fix ? https://imgur.com/a/2L0UZ

**Comment by mrfacu87** [comment]
Same issue here with oauth. I hope there is a fix for this soon I really loved this feature.

**Comment by Eric2203** [comment]
GenerIAce and mrfacu87, did you go into the settings for the plug-in and provide it with an authentication pin? You can do that via the Plex web interface. I think that's the problem you're having. Not the same as mine.

**Comment by animosity22** [comment]
@Eric2203  - it's the same error with sentry net timing out. You posted logs and he posted the screen shot of the logs.

**Comment by rdemendoza** [comment]
Seems sentry.skipthe.net is dead so no new authentications.

**Comment by rdemendoza** [comment]
Tried with basic auth https://trakt-for-plex.github.io/configuration anyone succeed to use it ?

**Comment by rectifyer** [comment]
Authentication should work correctly now, I just pushed a Trakt fix for that. Let's use #484 to discuss the `sentry.skipthe.net` error. I reached out to the dev to ask if removing that code will cause another issues and pull requests are of course welcome!

**Comment by GenerlAce** [comment]
working now for me! try it again everyone.

**Comment by vince105** [comment]
This works for me as well. Thanks so much! @rectifyer

**Comment by mrfacu87** [comment]
I was able to authenticate again. Thank you @rectifyer

**Comment by Massaguana** [comment]
same here with 1.3.3

**Comment by animosity22** [comment]
@Massaguana  - what are you seeing for an error? I've tested a few times now and can't see an issue as I can authenticate repeatedly. Did you remove your connected app from trakt? are you setting up something that was working before? Do you have any log files?

**Comment by Massaguana** [comment]
What i see is this
![bildschirmfoto 2018-03-05 um 17 47 05](https://user-images.githubusercontent.com/15521791/36987705-49732256-209d-11e8-9f04-3478cc7487a3.png)
![bildschirmfoto 2018-03-05 um 17 46 14](https://user-images.githubusercontent.com/15521791/36987706-49a74a0e-209d-11e8-953d-9fce92bd6f7b.png)

Yes, i have disconnect from trakt.tv... Strange are that only my external Users are making problems, my own user are works...

**Comment by Eric2203** [comment]
@Massaguana Did you update the authentication pin in the plug-in settings?

**Comment by Massaguana** [comment]
Yes, i test it to update the key in the plug-in settings and over http://trakt-for-plex.github.io/... but it changes nothing... no auth possible

**Comment by GenerlAce** [comment]
@Massaguana try this site, http://trakt-for-plex.github.io/configuration , and make sure to use pin authentication instead of basic. thats what worked for me to authorize the plugin to work.

**Comment by Massaguana** [comment]
this is exactly what I am trying to do all the time but it don´t work...

**Comment by animosity22** [comment]
did you remove the old connected app from trakt or did you ever have one show up there?

**Comment by mrfacu87** [comment]
I receiving the same issue and was able to fix it with the following steps.
1. Go to https://trakt.tv/oauth/authorized_applications and remove the app called trakt (for Plex)
2. Go to the app plugin settings and then visit the link next to Authentication PIN (https://trakt.tv/pin/1234)
3. Sign in to trakt and then copy the code and paste it into the plugin settings.
4. Before the fix, I would hit save after saving the code and nothing would happen. Now, the settings page closes and I can confirm that the app is listed again in trakt settings

**Comment by Massaguana** [comment]
Okay, now my own Account are connected to Plex and Trakt.tv... i must do setup the auth pin over the plug-in seetings, over http://trakt-for-plex.github.io/ its not work...

What must i do to connect the others Users of my Server?

**Comment by Massaguana** [comment]
Interesting... the plex auth also don´t work with  http://trakt-for-plex.github.io/

**Comment by Massaguana** [comment]
Okay, my Trakt.tv Plugin is now working fine... thanks for your help

**Comment by Eric2203** [comment]
Closing this issue then, since it's fixed for me and everyone else.
