### ISSUE TITLE
Settings page missing from Wiki

### ISSUE THREAD

**Issue by tehniemer** [trakt/Plex-Trakt-Scrobbler#534]
The link to the explanation of the plugin settings is broken, just a ```404 error```

https://raw.githubusercontent.com/wiki/trakt/Plex-Trakt-Scrobbler/Configuration

**Comment by NBSDEVApp** [comment]
I have same issue actually

**Comment by Danimatos** [comment]
Same here.

**Comment by MammothJerk** [comment]
same here

**Comment by purposelycryptic** [comment]
There has never been an actual wiki page explaining the settings, to my knowledge (at least, not since I started using the plug-in in early 2018).

I believe they either intended to write one and never did, or intended to link to actual 'Settings' web-app page (see issue #544 ), which doesn't seem to have a proper link to it anywhere on GitHub, despite being required for setup if you're using a newer version of Plex that doesn't expose plug-in settings menus.

**Comment by Xalaxis** [comment]
In case anyone was wondering, I've found the answer to the mysterious missing configuration page, it was deleted by someone called "Zenobia" in commit fbe1fcb59c184c535f329cb8e66242197a656401 to the wiki.  I'm going to post the original content below:

**Comment by Xalaxis** [comment]
| Name                                 | Description                                                                                               |
|:-------------------------------------|-----------------------------------------------------------------------------------------------------------|
| Authentication PIN                   | Authentication PIN for your Trakt.tv account                                                              
| Scrobble                             | Enable real-time scrobbling of watched media   
| Scrobble - Ignore Duplicates for     | The item will be scrobbled once, even if played many times within the time period. Disabling this could lead to many duplicate scrobbles
| Sync - Watched                       | [Mode](#sync-modes) for syncing watch states  
| Sync - Ratings                       | [Mode](#sync-modes) for syncing ratings                                                                   |
| Sync - Ratings - Conflict resolution | Conflict resolution method for ratings                                                                    |
| Sync - Playback Progress             | [Mode](#sync-modes) for syncing playback progress                                                         |
| Sync - Collection                    | [Mode](#sync-modes) for syncing collected media                                                           |
| Sync - Clean collection              | Enable to remove items from your Trakt.tv collection that aren't available in your Plex libraries anymore |
| Sync - Liked Lists (Beta)            | [Mode](#sync-modes) for syncing your liked Trakt.tv lists                                                 |
| Sync - Personal Lists (Beta)         | [Mode](#sync-modes) for syncing your personal Trakt.tv lists                                              |
| Sync - Watchlist (Beta)              | [Mode](#sync-modes) for syncing your Trakt.tv watchlist                                                   |
| Sync - Instant Actions               | *not implemented*                                                                                         |
| Sync - Run after library updates     | Trigger a full sync after your Plex libraries have been updated                                           |
| Sync - Run every                     | Trigger a full sync at the specified interval                                                             |
| Matcher                              | Matcher used for parsing episode identifiers                                                              |
| Global Filter - Users                | [Filter](#filters) to specify the names of users that can scrobble                                        |
| Global Filter - Client Names         | [Filter](#filters) to specify the names of clients that can scrobble                                      |
| Global Filter - Client IPs           | [Filter](#filters) to specify the IP Addresses of clients that can scrobble                               |
| Global Filter - Libraries            | [Filter](#filters) to specify the names of libraries that can be scrobbled                                |
| Activity mode                        | Activity method to use for retrieving watching activity                                                   |
| Logging - Events                     | Minimum logging level for messages from event emitters                                                    |
| Logging - Database                   | Minimum logging level for messages from the database                                                      |
| Logging - Plugin                     | Minimum logging level for messages from the plugin                                                        |
| Logging - Libraries                  | Minimum logging level for messages from third-party libraries                                             |

## Sync Modes

 - **Disabled**
 - **Synchronize** - Synchronize changes between your Trakt.tv profile and Plex
 - **Pull** - Pull changes from your Trakt.tv profile into Plex
 - **Push** - Push changes from Plex to your Trakt.tv profile

## Filters

Filters can be defined as values to allow (e.g. ```one, two```), or values to disallow with a ```-``` prefix (e.g. ```-one, -two```).

#### Client Names

Client names can be found by opening ```Status -> Now Playing``` while you are watching something on the client, the name of the client will be displayed in the top-right of the media artwork.

#### IP Addresses

IP Addresses can be defined as a specific address (e.g. ```192.168.1.100```), or an entire network (e.g. ```192.168.1.0/24```).

**Comment by an3k** [comment]
I got slightly triggered by that missing page ... so I re-created it using the original markdown. If @tehniemer would close this issue I could sleep peacefully again :)
