### ISSUE TITLE
Activity from all users gets synced to my trakt

### ISSUE THREAD

**Issue by droopified** [trakt/Plex-Trakt-Scrobbler#573]
I installed this to my server and added my trakt info without much configuration. It worked fine when I watched a movie but what I didn't know is that it's a global setup. How do I only make my account active and ignore all other accounts on Plex from using my trakt?

**Comment by briancwelch** [comment]
Go to Plex Settings > Plugins > Trakt.tv (Scrobbler), click gear icon to go to plugin settings, scroll down to where you see:
`Global Filter - Users (comma separated)`
Enter your **_Plex_** username in that field and hit save.

**Comment by droopified** [comment]
thanks!!! tested it and works as it should now. no more watched history from other accounts from my plex server!
