### ISSUE TITLE
How to specify client names under "Scrobble - Client names"

### ISSUE THREAD

**Issue by enz1ey** [trakt/Plex-Trakt-Scrobbler#73]
I use an Apple TV 3 running plexconnect with the trakt.tv plugin installed on my PMS. I also have multiple users sharing my library, so I only want my activity logged. I have my Plex username specified under "Scrobble - myPlex Users" but that doesn't track any of my activity since plexconnect on the Apple TV doesn't support myPlex login. How should I specify the client under "Scrobble - Client names" specifically? Right now I just entered "Apple TV" but it doesn't seem to be working.

**Comment by Brianbrifri** [comment]
What would be an example of a client name I should enter for the client filter? Basically, All I want is for me and only me, not my friends who I've shared my library with, to scrobble to trakt

**Comment by tijptjik** [comment]
Is it possible to filter clients based on the operating system that the client is running on? Say 'OSX' instead of `Plex Web (Chrome)` ?

**Comment by fuzeman** [comment]
@tijptjik Filtering by operating system isn't possible.

The new configuration interface *(hopefully released this week)* will support filtering by specific client identifiers *(every browser session has a unique client identifier)*, so this will likely be a solution to your filtering issue.

Subscribe to #193 for a notification when this is available.

**Comment by tijptjik** [comment]
Thanks for the update, indeed it would!
